### ISSUE TITLE
和 PyTorch 是否有兼容问题

### ISSUE THREAD

**Issue by cailurus** [HIT-SCIR/pyltp#105]
Hi,

`import torch as t`
`from pyltp import Segmentor`
`seg = Segmentor()`
`seg.load("./cws.model")`

PyTorch 就会出现 RuntimeError: std::bad_cast

不知是pyltp的问题还是PyTorch的问题？

**Comment by liu946** [comment]
已经有多人反应有此问题，暂时先试一下切换python版本，我们会尽快解决。
