### ISSUE TITLE
请问一下在anacoda安装pyltp时会报错

### ISSUE THREAD

**Issue by melisa81** [HIT-SCIR/pyltp#106]
通过下载源码,然后编译安装时,报
gcc: error: /DBOOST_PYTHON_SOURCE: No such file or directory
/DBOOST_PYTHON_STATIC_LIB: No such file or directory
gcc: error: /EHsc: No such file or directory

如何解决啊?

**Comment by zhaosanjin** [comment]
您好，我用pip进行安装，您可以试一下

**Comment by RingWong** [comment]
我也遇到同样的问题，pip install pyltp报错，请问您是怎么解决的？

**Comment by hee0624** [comment]
安装 gcc g++ 就可以了

**Comment by pogevip** [comment]
@hee0624 failed building wheel for pyltp ，错误：C++ 14

**Comment by pogevip** [comment]
如何解决啊
