### ISSUE TITLE
pyltp 1.9.1出现model not loaded

### ISSUE THREAD

**Issue by ElijahLai** [HIT-SCIR/pyltp#109]
导入模型的时候，总是报出model not loaded，不管是使用3.3.1还是3.4.0都出现这个报错

**Comment by lishuyou1986** [comment]
测试发现，路径中含有中文或者其他特殊字符会提示model not loaded

**Comment by ElijahLai** [comment]
嗯，我也发现是这个问题

**Comment by lambdaphy** [comment]
请教一下，安装环境是什么样的？Python版本是多少？C++编译器是哪个版本？

**Comment by ElijahLai** [comment]
windows   3.6以上   直接下载编译好的版本，然后放到anaconda的site-package文件下，然后模型路径不能有中文

**Comment by lambdaphy** [comment]
编译好的版本从哪里下载的？

**Comment by lambdaphy** [comment]
不知道我哪里出问题了，pip安装的时候出现Cannot open include file: 'SplitSentence.h': No such file or directory的错误，SplitSentence.h这个文件找不到。

**Comment by ElijahLai** [comment]
忘了说，应该是之前我有个同事pip成功了，我直接把他的pyltp文件从anaconda那边拿过来用了，没有pip

**Comment by lambdaphy** [comment]
方不方便发个压缩包给我。baofngh@yeah.net
非常感谢。3

**Comment by ElijahLai** [comment]
我现在这台电脑没有，有空发给你

**Comment by lambdaphy** [comment]
好的，多谢。我也是Python 3.6版本的。
额外问一句，这个包需要什么编译环境啊？您了解吗？

**Comment by lambdaphy** [comment]
为什么有的可以pip成功有的不可以呢

**Comment by ElijahLai** [comment]
不需要，只是import的时候好像是要 from pyltp import pyltp.pyltp
具体我不知道，你要问哈工大LTP的成员

**Comment by lambdaphy** [comment]
好的，非常感谢。

**Comment by lambdaphy** [comment]
安装成功了，是从github上下载的压缩包缺少文件。多谢了。

**Comment by Oneplus** [comment]
看起来模型不能加载是由于路径中的中文。
