### ISSUE TITLE
无法使用模型

### ISSUE THREAD

**Issue by evanhasnoclue** [HIT-SCIR/pyltp#110]
您好，我在使用分词示例代码时，最后的分词后运行结果是空的，不知道什么情况。
本人用的是ANACONDA的spyder，python2.7，代码如下
import os
ltp_data_dir="F:\\ltp-models\\3.3.1\\ltp-data"
cws_model_path=os.path.join(ltp_data_dir,"cws.model")
from pyltp import Segmentor
segmentor=Segmentor()
segmentor.load(cws_model_path)
words=segmentor.segment("元芳你怎么看？")
print "\t".join(words)
结果为空
print list(words)
运行结果为： []

是否是我的模型问题，在百度云里下载下来的模型里面有两个压缩包，一个是ltp-data-v3.3.1.zip ,一个是ltp-data-v3.3.1.tar.bz2。 应该解压哪一个？

谢谢解答。

**Comment by evanhasnoclue** [comment]
问题已解决。。。

**Comment by Clifnich** [comment]
请问百度云的下载链接在哪，我需要分词模型文件

**Comment by ditingdapeng** [comment]
> 问题已解决。。。

你好老哥,我遇到了和你同样的问题,请问你怎样解决的?
邮箱:15713710944@153.com

**Comment by ditingdapeng** [comment]
> 问题已解决。。。

你好老哥,我遇到了和你同样的问题,请问你怎样解决的?
邮箱:15713710944@163.com
