### ISSUE TITLE
Anaconda 4.4.0 (64-bit) 安装pyltp报错

### ISSUE THREAD

**Issue by fancybian** [HIT-SCIR/pyltp#113]
有谁知道这个报错是由于什么问题吗，我尝试了 pip install pyltp 和使用git clone的方法都报的同样的问题。
`LINK : warning LNK4001: no object files specified; libraries used
LINK : warning LNK4068: /MACHINE not specified; defaulting to X86
LINK : fatal error LNK1159: no output file specified
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status
1159`
有哪位大佬知道如何解决？感谢！！！！

**Comment by shiningliang** [comment]
@fancybian 我也是同样的问题，之前还装了VC Builder。。。

**Comment by liu946** [comment]
合并到 #90 解决。另外提示Windows下编译pyltp 0.2.0版本 用python2默认的VC编译器是无法编译的。

**Comment by liyi193328** [comment]
同遇到这个这个问题， 用git clone的方法安装的， 没看到解决方案啊？

**Comment by liyi193328** [comment]
D:\vs2015\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Anaconda3\libs /LIBPATH:D:\Anaconda3\PCbuild\amd64 /LIBPATH:D:\vs2015\VC\LIB\amd64 /LIBPATH:D:\vs2015\VC\ATLMFC\LIB\amd64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64"" /EXPORT:PyInit_pyltp build\temp.win-amd64-3.5\Release\src\pyltp.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\cpp_regex_traits.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\cregex.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\c_regex_traits.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\fileiter.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\icu.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\instances.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\posix_api.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\regex.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\regex_debug.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\regex_raw_buffer.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\regex_traits_defaults.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\static_mutex.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\usinstances.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\w32_regex_traits.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\wc_regex_traits.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\wide_posix_api.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\regex\src\winstances.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\cmdline.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\config_file.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\convert.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\options_description.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\parsers.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\positional_options.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\split.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\utf8_codecvt_facet.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\value_semantic.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\variables_map.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\program_options\src\winmain.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\archive_exception.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_archive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_iarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_iserializer.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_oarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_oserializer.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_pointer_iserializer.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_pointer_oserializer.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_serializer_map.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_text_iprimitive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_text_oprimitive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_text_wiprimitive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_text_woprimitive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\basic_xml_archive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\binary_iarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\binary_oarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\binary_wiarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\binary_woarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\codecvt_null.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\extended_type_info.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\extended_type_info_no_rtti.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\extended_type_info_typeid.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\polymorphic_iarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\polymorphic_oarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\singleton.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\stl_port.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\text_iarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\text_oarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\text_wiarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\text_woarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\utf8_codecvt_facet.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\void_cast.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_archive_exception.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_grammar.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_iarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_oarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_wgrammar.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_wiarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\serialization\src\xml_woarchive.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\smart_ptr\src\sp_collector.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\boost\libs\smart_ptr\src\sp_debug_hooks.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\aligned-mem-pool.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\cfsm-builder.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\deep-lstm.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\devices.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\dict.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\dim.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\dynet.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\exec.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\expr.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\fast-lstm.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\globals.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\grad-check.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\graph.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\gru.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\hsm-builder.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\init.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\lstm.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\mem.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\model.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\mp.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\nodes-common.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\nodes-contract.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\nodes-conv.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\nodes-conv2d.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\nodes.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\param-nodes.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\pretrain.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\rnn-state-machine.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\rnn.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\saxe-init.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\shadow-params.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\tensor.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\training.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\treelstm.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\dynet\dynet\weight-decay.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\maxent\lbfgs.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\maxent\maxent.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\maxent\owlqn.obj build\temp.win-amd64-3.5\Release\ltp\thirdparty\maxent\sgd.obj build\temp.win-amd64-3.5\Release\ltp\src\splitsnt\SplitSentence.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\decoder.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\extractor.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\model.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\partial_segmentation.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\preprocessor.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\segmentor.obj build\temp.win-amd64-3.5\Release\ltp\src\segmentor\segment_dll.obj build\temp.win-amd64-3.5\Release\ltp\src\postagger\decoder.obj build\temp.win-amd64-3.5\Release\ltp\src\postagger\extractor.obj build\temp.win-amd64-3.5\Release\ltp\src\postagger\postagger.obj build\temp.win-amd64-3.5\Release\ltp\src\postagger\postag_dll.obj build\temp.win-amd64-3.5\Release\ltp\src\ner\decoder.obj build\temp.win-amd64-3.5\Release\ltp\src\ner\extractor.obj build\temp.win-amd64-3.5\Release\ltp\src\ner\ner.obj build\temp.win-amd64-3.5\Release\ltp\src\ner\ner_dll.obj build\temp.win-amd64-3.5\Release\ltp\src\ner\options.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\classifier.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\instance.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\options.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\parser.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\parser_dll.obj build\temp.win-amd64-3.5\Release\ltp\src\parser.n\system.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\DepSRL.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\SRL_DLL.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\common\model\AffineTransformModelBuilder.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\common\model\CNN1dLayerBuilder.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\common\structure\SrlPiSample.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\include\base\config.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\include\base\debug.obj build\temp.win-amd64-3.5\Release\ltp\src\srl\Srl\model\SrlSrlModel.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\dict.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\errors.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\exec.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\import.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\list.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\long.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\module.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\numeric.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object_operators.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object_protocol.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\slice.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\str.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\tuple.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\wrapper.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\class.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\enum.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\function.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\function_doc_signature.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\inheritance.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\iterator.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\life_support.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\pickle_support.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\object\stl_iterator.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\converter\arg_to_python_base.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\converter\builtin_converters.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\converter\from_python.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\converter\registry.obj build\temp.win-amd64-3.5\Release\patch\libs\python\src\converter\type_id.obj /OUT:build\lib.win-amd64-3.5\pyltp.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\src\pyltp.cp35-win_amd64.lib
