### ISSUE TITLE
安装pyltp需要那个版本的boost库和Visual C++编译器？

### ISSUE THREAD

**Issue by lambdaphy** [HIT-SCIR/pyltp#116]
我的python环境是3.6，操作系统是window 10。
使用pip安装时候编译出错，猜测是C++环境的问题，我安装的是Visual Studio Community 2017，boost库是最新的1.65.1，安装出错的提示如下：
NOTE: Use of this header (boost/type_traits/config.hpp) is deprecated
  patch/include/boost/python/detail/caller.hpp(55): warning C4244: 'return': conversion from 'Py_ssize_t' to 'unsigned int', possible loss of data
  NOTE: Use of this header (ice_or.hpp) is deprecated
  NOTE: Use of this header (ice_and.hpp) is deprecated
  NOTE: Use of this header (ice_not.hpp) is deprecated
  NOTE: Use of this header (ice_eq.hpp) is deprecated
  src\pyltp.cpp(17): fatal error C1083: Cannot open include file: 'SplitSentence.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
-------------------------------------------------------------------------------------------------

**Comment by lambdaphy** [comment]
这个项目目前还在维护吗

**Comment by lambdaphy** [comment]
原来是从github下载的包有问题。。。ltp文件夹里面没有src文件夹。

**Comment by pogevip** [comment]
@lambdaphy  请问是如何解决？
