### ISSUE TITLE
词性标注使用自定义词典不起作用，没有效果呢

### ISSUE THREAD

**Issue by pinweihelai** [HIT-SCIR/pyltp#117]
词性标注使用自定义词典不起作用，没有效果呢

**Comment by liu946** [comment]
参考 http://ltp.ai/faq.html 第3个问题。

**Comment by liu946** [comment]
ltp的词性标注模块 并非采用词典匹配的策略 ，外部词典以特征方式加入机器学习算法，并不能保证所有的词都是按照词典里的方式进行分词。 如果要完全按照词典匹配的方式标注，您可以尝试对结果进行后处理。

**Comment by yongyuan923** [comment]
# 代码
# -*- coding: utf-8 -*-
import os
LTP_DATA_DIR = 'F:/LTP_cs/ltp_data'  # ltp模型目录的路径
cws_model_path = os.path.join(LTP_DATA_DIR, 'cws.model')  # 分词模型路径，模型名称为`cws.model`

from pyltp import Segmentor
segmentor = Segmentor()  # 初始化实例
segmentor.load_with_lexicon(cws_model_path, 'F:\LTP_cs\ltp_data\lexicon1.txt') # 加载模型，第二个参数是您的外部词典文件路径
#segmentor.load(cws_model_path)
words = segmentor.segment('李克强调研同盾科技,欧几里得是西元前三世纪的希腊数学家。')
print ('\t'.join(words))
segmentor.release()
# 外部词典
同盾科技
亚硝
酸盐
欧几里得
# 运行结果
[INFO] 2018-03-20 14:14:08 loaded 4 lexicon entries
李克强	调研	同盾	科技	,	亚硝酸盐	是	一	种	化学	物质	,	欧	几	里	得	是	西元前	三	世纪	的	希腊	数学家	。
# 请问，这个问题你解决了吗？谢谢！@pinweihelai

**Comment by yongyuan923** [comment]
请问，pyltp分词中外部词典匹配没有效果，可以使用个性化分词模型能解决吗?@liu946

**Comment by youngjt** [comment]
都设置外部字典了，为什么分词还不按照外部的字典进行分词呢？

**Comment by gbolin** [comment]
时间都过去这么久了，问题还是存在

**Comment by xienan0326** [comment]
plz use force_lexicon_path=None
