### ISSUE TITLE
ArgumentError Occur when call ner.recognize()

### ISSUE THREAD

**Issue by Sewens** [HIT-SCIR/pyltp#118]
Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

## *What* is affected by this bug?

**Runtime Error**

## *When* does this occur?

Errror occur when every time i use NamedEntityRecognizer tools for recognize sentences. While other tools such as segment tools working normally.

## *Where* on the code does it happen?

Here's my code:
``` python
from pyltp import NamedEntityRecognizer
nerLtp = NamedEntityRecognizer()
nerLtp.load('/home/why_this_happen/ltp_data/ltp_data_v3.3.1/ner.model')
nerLtp.recognize('你好祖国') #!!!error location!!!
```
When call NER.recognize. My IDE told me these error info:
```
ArgumentError                             Traceback (most recent call last)
<ipython-input-9-06aba9465bd1> in <module>()
----> 1 nerLtp.recognize('你好祖国')
ArgumentError: Python argument types in
    NamedEntityRecognizer.recognize(NamedEntityRecognizer, str)
did not match C++ signature:
    recognize(NamedEntityRecognizer {lvalue}, boost::python::list, boost::python::list)
    recognize(NamedEntityRecognizer {lvalue}, boost::python::list, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)
    recognize(NamedEntityRecognizer {lvalue}, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::python::list)
    recognize(NamedEntityRecognizer {lvalue}, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)
```

## *How* do we replicate the issue?

Maybe try my code up there.

## Your environment information

```
OS: Ubuntu 16.04-desktop-LTS
Python Version: Python 3.6.1 |Anaconda custom (64-bit)
GCC: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
LTP: pyltp-0.1.10-py3.6-linux-x86_64.egg
Modle: /ltp_data/ltp_data_v3.3.1/ner.model
```
## Expected behavior (i.e. solution)

Fix this or just tell me how to use.
## Other Comments
Maybe here's some solution about this issue:
[boost.python: Argument types did not match C++ signature](https://stackoverflow.com/questions/20825662/boost-python-argument-types-did-not-match-c-signature)
I've found this but I got no idea how to fix it.
Pls do me a favour.
中文解答就可以了，其实。。

**Comment by endyul** [comment]
ner输入的是分词和词性标注结果，请参考文档里的示例代码

发自我的 iPhone
