### ISSUE TITLE
调用3.4.0模型的语义分析

### ISSUE THREAD

**Issue by FannyChung** [HIT-SCIR/pyltp#120]
最近可以调用3.4的模型，但是我调用语义角色分析的时候，出现：`error: cannot open model:F:\myModel\segModel\ltp_data\pisrl.model/srl.model`.，出错位置是`roles = labeller.label(words, postags, arcs)`，相关提示是`Boost.Python.ArgumentError: Python argument types in
    SementicRoleLabeller.label(SementicRoleLabeller, VectorOfString, VectorOfString, VectorOfParseResult)`，请问可以怎样改呢？
调用前面的分词、实体、依存都能够正确的进行，只有这个语义分析出错。
个人使用的代码就是example里面的代码：
```python
labeller = SementicRoleLabeller()
labeller.load(os.path.join(MODELDIR, "pisrl.model"))
roles = labeller.label(words, postags, arcs)
```

**Comment by liu946** [comment]
看样子是你没有更新到新的0.2.0的pyltp，需要重新编译安装一下本仓库master代码。

**Comment by FannyChung** [comment]
@liu946 感谢！我在安装的过程中用源代码的方式，在python install出现卡在一半的情况，不知道是为什么？系统是64位的，
![image](https://user-images.githubusercontent.com/5433467/33823520-6182b954-de96-11e7-9276-b4dc072dea0f.png)

请问是否还需要安装其他的组件或者什么才能把2.0的pyltp安装成功？

**Comment by FannyChung** [comment]
我是重新clone了新的github上的源码

**Comment by liu946** [comment]
这个问题我在 #88 回复了。
