### ISSUE TITLE
undefined symbol: _ZTISt19__codecvt_utf8_baseIwE

### ISSUE THREAD

**Issue by billgavin** [HIT-SCIR/pyltp#121]
模块加载

Python导入模块
from pyltp import SentenceSplitter

Ubuntu 16.04 64bit
Python 3.6.1 |Anaconda custom (64-bit)

pyltp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTISt19__codecvt_utf8_baseIwE

**Comment by liu946** [comment]
兼容Conda编译器有些问题。暂时不支持。用原生python编译安装。
