### ISSUE TITLE
Mac OS X 10.13.2 不能安装也不能从源码安装

### ISSUE THREAD

**Issue by goat98** [HIT-SCIR/pyltp#124]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 运行环境

我把121行的MACOSX_DEPLOYMENT_TARGET改为10.13后编译报错：我的系统版本是10.13

patch/include/boost/python/detail/caller.hpp:55:12: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'unsigned int'
      [-Wshorten-64-to-32]
    return PyTuple_GET_SIZE(args_);
    ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/tupleobject.h:51:33: note: expanded from macro 'PyTuple_GET_SIZE'
#define PyTuple_GET_SIZE(op)    Py_SIZE(op)
                                ^~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:116:56: note: expanded from macro 'Py_SIZE'
#define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
src/pyltp.cpp:17:10: fatal error: 'SplitSentence.h' file not found
#include "SplitSentence.h"
         ^~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
error: command 'clang++' failed with exit status 1

<!-- 中文模板结束, end of Chinese template -->

**Comment by jangleise** [comment]
我执行了git submodule相关指令了，但是也是和一楼一样出现了同样的问题，请问解决了吗？

src/pyltp.cpp:17:10: fatal error: 'SplitSentence.h' file not found
#include "SplitSentence.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
error: command 'clang++' failed with exit status 1

**Comment by liu946** [comment]
如果正常的话，您缺失的文件在项目文件夹下 ltp/src/splitsnt/SplitSentence.h，您能人工检查一下是否存在么？

**Comment by goat98** [comment]
今天在Mac OS 10.13 上源码安装了哈工大分词器。
解决方法看文档，
https://www.cnblogs.com/herosoft/p/9787164.html

**Comment by wangliangster** [comment]
如果是python### 3.7编译报错，这是Clang编译器对代码要求更严格造成的。
"patch/libs/python/src/converter/builtin_converters.cpp"作如下修改
![image](https://user-images.githubusercontent.com/2356766/50571232-076e1100-0de0-11e9-93a6-525dcbe1d19a.png)

若是 python2.7/3.6自带的GCC编译器，没问题，我试过很多遍了

**Comment by fighting41love** [comment]
很多人遇到的问题可能是因为readme.md漏掉了一个细节导致的。

>  $ git clone https://github.com/HIT-SCIR/pyltp  
 $ git submodule init
 $ git submodule update
 $ python setup.py install

实际上是：
>  $ git clone https://github.com/HIT-SCIR/pyltp 
 **$ cd pyltp**  
 $ git submodule init
 $ git submodule update
 $ python setup.py install

**Comment by wangliangster** [comment]
不至于吧～

**Comment by Thons** [comment]
> 如果是python### 3.7编译报错，这是Clang编译器对代码要求更严格造成的。
> "patch/libs/python/src/converter/builtin_converters.cpp"作如下修改
> ![image](https://user-images.githubusercontent.com/2356766/50571232-076e1100-0de0-11e9-93a6-525dcbe1d19a.png)
> 
> 若是 python2.7/3.6自带的GCC编译器，没问题，我试过很多遍了

macOS 10.4.3 & Python 3.7.3，按照此方法，成功！

**Comment by hahawhy** [comment]
> > 如果是python### 3.7编译报错，这是Clang编译器对代码要求更严格造成的。
> > "patch/libs/python/src/converter/builtin_converters.cpp"作如下修改
> > ![image](https://user-images.githubusercontent.com/2356766/50571232-076e1100-0de0-11e9-93a6-525dcbe1d19a.png)
> > 若是 python2.7/3.6自带的GCC编译器，没问题，我试过很多遍了
> 
> macOS 10.4.3 & Python 3.7.3，按照此方法，成功！

感恩的心，同遇到安装报错的问题，按照此方法，安装成功！
