### ISSUE TITLE
既然官网提供了LTP的二进制版本和模型，能否提供python的免编译库？

### ISSUE THREAD

**Issue by yaleimeng** [HIT-SCIR/pyltp#128]
## 问题
使用pip安装总是中途make失败，下载后执行setup也无法正常编译，也是中途报错。
无论是pip还是执行setup，都是上来就开始进行代码编译，中间报错是难免的。
f:\pyltp-master\ltp\src\srl\include\extractor\Converter.h(32): error C3861: 'convert': identifier not found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

我打开src\srl\include\extractor\Converter.h 也看了。。里面有定义这个虚函数。
而且把 函数声明后面的 =0改为 { }也不行。不知道什么情况。

## 运行环境
 python3.5.4、3.6.2均不行【非Anaconda 】。 操作系统：Win10 64位，已装微软VC++ Builder工具包。

## 期望结果
官网已经提供了二进制执行包和训练模型，python库能不能就不要make了？ 能否提供与二进制包和模型搭配使用的、免编译的python库？

盼复。感谢！

**Comment by dafuh** [comment]
我试了好多次，终于发现不支持python 3。白费了好多力气，你没发现所有的地方都没有说python的版本吗？
也不能怪人家，这种公益性质的事情本来就没人做。更何况这是一个学校负责的项目，那些研究生有几个会去搞这些公益性的开发。

**Comment by liu946** [comment]
@dafuh 感谢理解。但是事情也不是你想的那样。pyltp支持python3 的编译安装。目前pyltp支持的linux、OSX下的python2/3和win下的python3。具体的支持版本可以在 https://travis-ci.org/HIT-SCIR/pyltp，https://ci.appveyor.com/project/liu946/pyltp 参考。我们也不是功能完成之后就立马发布的，肯定也是经过一系列不同系统的编译测试之后才能够发布。但是由于本软件的复杂性，也是计算机环境的复杂性，才导致部分同学编译不能通过，我们也在尽力解决这些问题。会在近期给大家一个新版本安装方法和可以运行的环境的文档给大家参考。但是确实考虑到个人精力有限，问题只能一个个解决，事情也是只能一件一件做。还望大家谅解。如果着急使用或想得知什么环境可以正常编译，目前可以先参考ci的编译环境。如果有突破还请帮助其他人解决一下相似的问题。

**Comment by ELI95** [comment]
ltp/thirdparty/dynet/dynet/dim.h: In constructor ‘dynet::Dim::Dim(const std::vector<long int, std::allocator<long int> >&)’:
    ltp/thirdparty/dynet/dynet/dim.h:71: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:72: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h: In constructor ‘dynet::Dim::Dim(const std::vector<long int, std::allocator<long int> >&, unsigned int)’:
    ltp/thirdparty/dynet/dynet/dim.h:80: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/dim.h:81: error: expected ‘;’ before ‘}’ token
    In file included from ltp/thirdparty/dynet/dynet/tensor.h:18,
                     from ltp/thirdparty/dynet/dynet/dynet.h:19,
                     from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/devices.h: In constructor ‘dynet::Device::Device(int, dynet::DeviceType, dynet::MemAllocator*)’:
    ltp/thirdparty/dynet/dynet/devices.h:33: error: ‘nullptr’ was not declared in this scope
    ltp/thirdparty/dynet/dynet/devices.h: At global scope:
    ltp/thirdparty/dynet/dynet/devices.h:73: error: cannot declare field ‘dynet::Device_CPU::cpu_mem’ to be of abstract type ‘dynet::CPUAllocator’
    ltp/thirdparty/dynet/dynet/mem.h:26: note:   because the following virtual functions are pure within ‘dynet::CPUAllocator’:
    ltp/thirdparty/dynet/dynet/mem.h:16: note: 	virtual void* dynet::MemAllocator::malloc(size_t)
    ltp/thirdparty/dynet/dynet/mem.h:17: note: 	virtual void dynet::MemAllocator::free(void*)
    ltp/thirdparty/dynet/dynet/mem.h:18: note: 	virtual void dynet::MemAllocator::zero(void*, size_t)
    In file included from ltp/thirdparty/dynet/dynet/dynet.h:19,
                     from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/tensor.h: In constructor ‘dynet::Tensor::Tensor()’:
    ltp/thirdparty/dynet/dynet/tensor.h:56: error: ‘nullptr’ was not declared in this scope
    In file included from ltp/thirdparty/dynet/dynet/dynet.h:19,
                     from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/tensor.h: In constructor ‘dynet::IndexTensor::IndexTensor()’:
    ltp/thirdparty/dynet/dynet/tensor.h:403: error: ‘nullptr’ was not declared in this scope
    In file included from ltp/thirdparty/dynet/dynet/dynet.h:20,
                     from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/model.h: At global scope:
    ltp/thirdparty/dynet/dynet/model.h:85: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:88: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:89: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:92: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:95: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:96: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:143: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:146: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:147: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:150: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:153: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:154: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:414: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:440: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:456: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:471: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:489: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:504: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:521: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:537: error: expected ‘;’ before ‘override’
    In file included from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/dynet.h:544: error: expected ‘;’ before ‘final’
    ltp/thirdparty/dynet/dynet/dynet.h:558: error: expected ‘;’ before ‘final’
    ltp/thirdparty/dynet/dynet/graph.cc: In function ‘void dynet::graph_optimize(dynet::ComputationGraph*)’:
    ltp/thirdparty/dynet/dynet/graph.cc:17: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:15: warning: unused variable ‘v’
    ltp/thirdparty/dynet/dynet/graph.cc:16: warning: unused variable ‘lp’
    ltp/thirdparty/dynet/dynet/graph.cc:26: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected ‘;’ before ‘}’ token
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8vf2d8rg/pyltp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_966dxfs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8vf2d8rg/pyltp/

**Comment by skyhiter** [comment]
这是两个链接。。。。。

**Comment by xxxspy** [comment]
可以尝试利用社区的力量，毕竟是开源软件

**Comment by xxxspy** [comment]
感谢@dafuh的patch， 我封装了两个wheel， 可以方便在windows安装，亲测可用：
- (pyltp-0.2.1-cp35-cp35m-win_amd64.whl)[http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp35-cp35m-win_amd64.whl]
- (pyltp-0.2.1-cp36-cp36m-win_amd64.whl)[http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp36-cp36m-win_amd64.whl]

用的时候只要`pip install wheel_file_name`

**Comment by yaleimeng** [comment]
@xxxspy 感谢您的whl文件。我下载了py3.5版本的，亲测可用。
@liu946 同时感谢ltp、pyltp团队的辛苦工作。此Issue可以完美关闭了。

**Comment by whaozl** [comment]
这里放出ltp的linux版本的编译好的whl文件
[pyltp-0.2.1-cp35-cp35m-linux_x86_64.whl](https://download.csdn.net/download/zhulinniao/10540535)

**Comment by sc-lj** [comment]
> 感谢@dafuh的patch， 我封装了两个wheel， 可以方便在windows安装，亲测可用：
> 
> * [pyltp-0.2.1-cp35-cp35m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp35-cp35m-win_amd64.whl)
> * [pyltp-0.2.1-cp36-cp36m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp36-cp36m-win_amd64.whl)
> 
> 用的时候只要`pip install wheel_file_name`
大神，能不能提供mac版本的pyltp编译好的版本呀？我目前mac 系统版本是macos mojave 10.14.2版本，安装的时候始终出现'iostream' file not found问题。

**Comment by sc-lj** [comment]
> 这里放出ltp的linux版本的编译好的whl文件
> [pyltp-0.2.1-cp35-cp35m-linux_x86_64.whl](https://download.csdn.net/download/zhulinniao/10540535)
> 或者链接：https://pan.baidu.com/s/1EKPAQqTr0G2ztM4i4XC36w 密码：wpii
> 如果是Ubuntu 请把m修改为mu


大神，能不能提供mac版本的pyltp编译好的版本呀？我目前mac 系统版本是macos mojave 10.14.2版本，安装的时候始终出现'iostream' file not found问题。

**Comment by sc-lj** [comment]
> 感谢@dafuh的patch， 我封装了两个wheel， 可以方便在windows安装，亲测可用：
> 
> * [pyltp-0.2.1-cp35-cp35m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp35-cp35m-win_amd64.whl)
> * [pyltp-0.2.1-cp36-cp36m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp36-cp36m-win_amd64.whl)
> 
> 用的时候只要`pip install wheel_file_name`



大神，能不能提供mac版本的pyltp编译好的版本呀？我目前mac 系统版本是macos mojave 10.14.2版本，安装的时候始终出现'iostream' file not found问题。

**Comment by whaozl** [comment]
我没有amc环境，sorry哈。

**Comment by zifeiYv** [comment]
> 这里放出ltp的linux版本的编译好的whl文件
> [pyltp-0.2.1-cp35-cp35m-linux_x86_64.whl](https://download.csdn.net/download/zhulinniao/10540535)
> 或者链接：https://pan.baidu.com/s/1EKPAQqTr0G2ztM4i4XC36w 密码：wpii
> 如果是Ubuntu 请把m修改为mu

能不能提供一个python3.6版本的l呢？最好是centos系统

**Comment by andglf** [comment]
> 这里放出ltp的linux版本的编译好的whl文件
> [pyltp-0.2.1-cp35-cp35m-linux_x86_64.whl](https://download.csdn.net/download/zhulinniao/10540535)
> 或者链接：[https](https://pan.baidu.com/s/1EKPAQqTr0G2ztM4i4XC36w)：//pan.baidu.com/s/1EKPAQqTr0G2ztM4i4XC36w密码：wpii 
> 如果是Ubuntu请把m修改为亩

亲测可用^_^，但是我还需要一个py36或者py37的，您可以提供一个编译包或者编译方法吗？
万分感谢

**Comment by yaleimeng** [comment]
@zifeiYv  我在CentOS 7上是能直接pip安装编译成功的啊。。Ubuntu上以前弄过好像也是能直接编译通过的。

**Comment by andglf** [comment]
> @zifeiYv 我在CentOS 7上是能直接pip安装编译成功的啊。。Ubuntu上以前弄过好像也是能直接编译通过的。

因为我使用的是anaconda所以一直编译一直不通过

**Comment by yaleimeng** [comment]
Linux环境就不需要anaconda来凑热闹了吧。。Windows上很多库安装困难，新手才需要它。

**Comment by andglf** [comment]
@yaleimeng 因为多个环境conda管理比较方便，用的比较习惯吧

**Comment by andglf** [comment]
@yaleimeng 您平时使用什么方式进行管理呀

**Comment by whaozl** [comment]
@andglf  不好意思哈 可以自己编译的 没关系 很简单的 不难 我这里只有35环境 一般用35就够了

**Comment by jh-deng** [comment]
@andglf 请问现在有py36的编译包吗？装了一天实在编译不过，能否帮忙打包一个？

**Comment by Garbage-boop** [comment]
py3.8 windows环境 安装wheel文件失败，pyltp这个库我装了一上午了，崩溃，炸裂的那种

**Comment by carfly** [comment]
LTP更新到了4.0版本，提供Python的原生支持，建议直接使用：https://github.com/HIT-SCIR/ltp

-Wanxiang (http://ir.hit.edu.cn/~car/)
