### ISSUE TITLE
如何添加自己的命名实体类别

### ISSUE THREAD

**Issue by Mariobai** [HIT-SCIR/pyltp#129]
目前的LTP工具只支持三种基本的命名实体类型，我怎么添加自己的命名实体类型，比如货币、日期、数字等。这些怎么添加，

**Comment by liu946** [comment]
目前暂时不支持。

**Comment by zhaobinnian** [comment]
这个我可以自己训练模型，新增命名实体类型吗？

**Comment by xbc0112** [comment]
在语言云平台的简介中看到说“用户可以很容易将实体类型拓展成品牌名、软件名等实体类型”，请问现在是可以扩展命名实体类别了吗，要怎么做呢？

**Comment by AlongWY** [comment]
自己训练新模型就可以了
