### ISSUE TITLE
使用词性标注外部词典无效

### ISSUE THREAD

**Issue by yanqiangmiffy** [HIT-SCIR/pyltp#132]
pos_model_path=os.path.join(LTP_DATA_DIR,'pos.model')
postagger=Postagger()
postagger.load(pos_model_path)
words=['阿里巴巴','与','福特汽车','签署','战略','合作','协议','，','探索','新','的','零售','机会']
postags=postagger.postag(words)
print ' '.join(postags)
postagger.release()  # 释放模型

自定义词典：
福特汽车 ni nt
阿里巴巴 ni nt

但是输出的结果为：
nz p n v n v n wp v a u v n
标注ni无效

**Comment by liu946** [comment]
refer http://ltp.ai/faq.html#collapse-3
