### ISSUE TITLE
请问当前的pyltp版本是不是不再支持LTP3.3.1？如果安装LTP3.4.0，pyltp就可以成功安装;而安装LTP3.3.1，pyltp就安装失败

### ISSUE THREAD

**Issue by zyn412** [HIT-SCIR/pyltp#134]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by liu946** [comment]
是的，如果要使用3.3.0，请使用之前版本的pyltp。
