### ISSUE TITLE
使用分词外部词典与使用本身词典，结果不一致

### ISSUE THREAD

**Issue by wharstr9027** [HIT-SCIR/pyltp#135]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

使用分词外部词典与使用本身词典，分词结果不一致
## 出错*场景*

第一次未加载外部词典，分词结果为两个词“4”和“类”，使用外部词典之后，分词结果为一个词“4类”，但是外部词典中并无相关词
具体case：2016-08-26 兰州今年将启动12类重点城建项目，该桥被评定为4类危桥，新建续建32座过街天桥  2016-08-18 兰州一老人坠落人行天桥 险遭疾驰轿车碾压  2016-08-06 甘肃 社会 政务 通讯员 文娱
运行结果对比： 
本身词典结果：2016-08-26 兰州 今年 将 启动 12 类 重点 城建 项目 ， 该桥 被 评定 为 4 类 危桥 ， 新建 续建 32 座 过街天桥 2016-08-18 兰州 一 老人 坠落 人行 天桥 险 遭 疾驰 轿车 碾压 2016-08-06 甘肃 社会 政务 通讯员 文娱
[INFO] 2018-01-15 15:47:57 loaded 358127 lexicon entries
外部词典结果：2016-08-26 兰州 今年 将 启动 12 类 重点 城建 项目 ， 该桥 被 评定 为 4类 危桥 ， 新建 续建 32 座 过街天桥 2016-08-18 兰州 一 老人 坠落 人行天桥 险 遭 疾驰 轿车 碾压 2016-08-06 甘肃 社会 政务 通讯员 文娱
## 代码片段

# -*- coding: utf-8 -*-
import sys
import os
from pyltp import Segmentor, SentenceSplitter

# 分词
cws_model_path = os.path.join('../models', 'cws.model')
segmentor = Segmentor()  # 初始化实例
segmentor.load(cws_model_path)

sentence = '2016-08-26 兰州今年将启动12类重点城建项目，该桥被评定为4类危桥，新建续建32座过街天桥  2016-08-18 兰州一老人坠落人行天桥 险遭疾驰轿车碾压  2016-08-06 甘肃 社会 政务 通讯员 文娱'
words = segmentor.segment(sentence)  # 分词
print ' '.join(words)

segmentor_lexicon = Segmentor()
segmentor_lexicon.load_with_lexicon('../models/cws.model', '../models/dict.txt')
words_l = segmentor_lexicon.segment(sentence)
print ' '.join(words_l)
## 如何复现这一错误

直接运行我的代码就可以
## 运行环境

python2.7.5,Linux
## 期望结果

无论加载外部词典，分词结果应该保持一致。

**Comment by liu946** [comment]
ltp分词为概率模型。而且分词是前后有依赖的，不能保证分词结果一致。在系统实现方面可能没有办法帮你解决问题。你可以尝试预、后处理，或者使用两个不同的模型预测之后再整合结果。

**Comment by yongyuan923** [comment]
![default](https://user-images.githubusercontent.com/32128235/37599376-953512bc-2bbf-11e8-89c5-626f50ccf54f.jpg)
![default](https://user-images.githubusercontent.com/32128235/37599378-957118ca-2bbf-11e8-8c7e-9270c50511e2.jpg)
词典文件：
同盾科技
性价比
好用
指纹解锁
苹果6
分词结果：
[INFO] 2018-03-19 21:47:38 loaded 5 lexicon entries
﻿	高端	大气	上次	，	颜值	高	，	速度	快	，	值得	拥有	。	
	机器	不错	，	上手	容易	。	物流	很	快	。	
	外观	好看	手机	非常	好	用	，	这	一	款	手机	偏	厚实	，	应用	反应	速度	很	快	。	支持	国产	。
刚	用	了	一	天	，	还	在	探索	中	，	外形	很	好看	，	包装	也	很	大气	，	指纹	解锁	特别	好	用	，	比	我	那个	苹果	6	好	用	很多	。	不过	我	担心	充电	的	那个	位置	，	那	一	块	板	会	不	会	断	啊	?	京东	快递	就	是	快	辛苦	了	。	
	华为	，	真的	挺棒	，	之前	用	的	mate7	用	了	两	年	多	，	支持	国货	！	
	李克强	调研	同盾	科技
需解决的问题：
已经载入了词典，怎么还是跟没有载入词典的效果一样啊？
谢谢！望回复，万分感激。

**Comment by liu946** [comment]
如果你希望将所有出现在词表中的词都准确分出，可以进行后处理。
