### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by eli95** [HIT-SCIR/pyltp#137]
’
    ltp/thirdparty/dynet/dynet/model.h:153: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:154: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:414: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:440: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:456: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:471: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:489: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:504: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:521: error: expected ‘;’ before ‘override’
    ltp/thirdparty/dynet/dynet/model.h:537: error: expected ‘;’ before ‘override’
    In file included from ltp/thirdparty/dynet/dynet/graph.cc:2:
    ltp/thirdparty/dynet/dynet/dynet.h:544: error: expected ‘;’ before ‘final’
    ltp/thirdparty/dynet/dynet/dynet.h:558: error: expected ‘;’ before ‘final’
    ltp/thirdparty/dynet/dynet/graph.cc: In function ‘void dynet::graph_optimize(dynet::ComputationGraph*)’:
    ltp/thirdparty/dynet/dynet/graph.cc:17: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:23: error: expected ‘;’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:15: warning: unused variable ‘v’
    ltp/thirdparty/dynet/dynet/graph.cc:16: warning: unused variable ‘lp’
    ltp/thirdparty/dynet/dynet/graph.cc:26: error: expected initializer before ‘:’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected ‘)’ before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected primary-expression before ‘}’ token
    ltp/thirdparty/dynet/dynet/graph.cc:30: error: expected ‘;’ before ‘}’ token
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8vf2d8rg/pyltp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_966dxfs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8vf2d8rg/pyltp/

**Comment by albertwy** [comment]
查看一下自己的gcc与g++version，我之前用的4.8一直出错，后来升成5.4就可以了。
