### ISSUE TITLE
语义角色标注最新版本出错

### ISSUE THREAD

**Issue by CrazyTianC** [HIT-SCIR/pyltp#138]
pyltp版本0.2.1，模型版本3.4.0

1.在进行语义角色标注的时候，按照文档说明
roles = labeller.label(words, postags, arcs)执行，会报错。
应该还要加上实体识别。
这个问题是文档疏忽写错了，还是版本的问题？

2.加上实体识别之后
roles = labeller.label(words, postags, netags，arcs)
roles的结果一直是为空。是版本问题么？

**Comment by CrazyTianC** [comment]
出错是在ipthon的环境下，其他不会有问题。
虽然解决了，但是如果有人能告诉我为什么，感激不尽。

**Comment by liu946** [comment]
目前语义角色标注应该依赖的输入是，词word，词性postags，和句法关系。而不依赖命名实体信息。

**Comment by yongyuan923** [comment]
现在使用的版本是：
win7 、64位、Python3.6、pyltp0.1.9.1、LTP模型3.4.0。
现在的文档中是加载模型3.3.1中语义标注的方法（加载的是SRL目录形式）。
请问，怎样加载模型3.4.0的SRL文件，而不是加载目录？
谢谢！感激不尽。@liu946

**Comment by liu946** [comment]
pyltp0.1.9.1 对应的是目录形式SRL模型，不能加载3.4.0的模型。

**Comment by yongyuan923** [comment]
非常感谢您的回复！
因为前期安装的时候pyltp 0.2.1和模型3.4.0没有成功，询问了实验室同学后，改成了pyltp0.1.9.1，模型就能正常加载使用。
那如果我要在现有的环境中加载SRL模型，是不是需要pyltp 0.2.1才可以啊？或者把LTP模型安装低一版本的？
