### ISSUE TITLE
cygwin下编译失败

### ISSUE THREAD

**Issue by chivychao** [HIT-SCIR/pyltp#14]
Env: Win7 + cygwin x64
Python: [GCC 4.8.3] on cygwin
GCC: 4.9.2

无论是pip安装还是开发版安装均编译失败，错误信息如下：
running build
running build_ext
building 'pyltp' extension
gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/build=/usr/src/debug/python-2.7.8-1 -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/src/Python-2.7.8=/usr/src/debug/python-2.7.8-1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/__util/ -Iltp/src/srl/ -Ipatch/include/ -I/usr/include/python2.7 -c src/pyltp.cpp -o build/temp.cygwin-1.7.35-x86_64-2.7/src/pyltp.o
cc1plus: 警告：command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from patch/include/boost/python/detail/prefix.hpp:13:0,
                 from patch/include/boost/python/args.hpp:8,
                 from patch/include/boost/python.hpp:11,
                 from src/pyltp.cpp:14:
patch/include/boost/python/detail/wrap_python.hpp:88:0: 警告：“SIZEOF_LONG”重定义
 #  define SIZEOF_LONG 4
 ^
In file included from patch/include/boost/python/detail/wrap_python.hpp:50:0,
                 from patch/include/boost/python/detail/prefix.hpp:13,
                 from patch/include/boost/python/args.hpp:8,
                 from patch/include/boost/python.hpp:11,
                 from src/pyltp.cpp:14:
/usr/include/python2.7/pyconfig.h:1013:0: 附注：这是先前定义的位置
 #define SIZEOF_LONG 8
 ^
In file included from /usr/include/python2.7/Python.h:58:0,
                 from patch/include/boost/python/detail/wrap_python.hpp:142,
                 from patch/include/boost/python/detail/prefix.hpp:13,
                 from patch/include/boost/python/args.hpp:8,
                 from patch/include/boost/python.hpp:11,
                 from src/pyltp.cpp:14:
/usr/include/python2.7/pyport.h:886:2: 错误：#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^
In file included from patch/include/boost/python/object/make_instance.hpp:9:0,
                 from patch/include/boost/python/object/make_ptr_instance.hpp:8,
                 from patch/include/boost/python/to_python_indirect.hpp:11,
                 from patch/include/boost/python/converter/arg_to_python.hpp:10,
                 from patch/include/boost/python/call.hpp:15,
                 from patch/include/boost/python/object_core.hpp:14,
                 from patch/include/boost/python/args.hpp:25,
                 from patch/include/boost/python.hpp:11,
                 from src/pyltp.cpp:14:
patch/include/boost/python/object/instance.hpp:14:36: 警告：类型属性在定义后被忽略 [-Wattributes]
   struct BOOST_PYTHON_DECL_FORWARD instance_holder;
                                    ^
error: command 'gcc' failed with exit status 1

请问该如何解决，谢谢。

**Comment by Oneplus** [comment]
尝试一下用windows的二进制文件安装呢？https://pypi.python.org/packages/2.7/p/pyltp/pyltp-0.1.5.win-amd64-py2.7.exe#md5=bbb3ec6821a196f8f29614ef691c618c

**Comment by chivychao** [comment]
谢谢。在win32的python环境下有效。
但是cygwin中的python似乎无法使用这个预编译版本。

尝试将Lib/site-packages中的安装的pyltp复制到cygwin版本的相应位置，导入时仍提示`ImportError: No module named pyltp`

**Comment by endyul** [comment]
我重现了此问题，原因是你使用了64位的gcc而Python是32位的。请尝试安装32位的cygwin和gcc进行编译。另外貌似现在pyltp对cygwin下boost python的兼容性还没做好，pip安装时候请使用命令`CFLAGS=-DBOOST_PYTHON_SOURCE pip install pyltp`

**Comment by Oneplus** [comment]
@endyul nice bug shooting!

**Comment by chivychao** [comment]
>我重现了此问题，原因是你使用了64位的gcc而Python是32位的。

我的cygwin是64位没错，但python亦是64位。请见图 ：
![e](https://cloud.githubusercontent.com/assets/6171458/6864264/d3ffc328-d499-11e4-863a-7cef3a58a34d.PNG)

>pip安装时候请使用命令CFLAGS=-DBOOST_PYTHON_SOURCE pip install pyltp

仍然出错，错误信息太长，先不贴了。但主要错误还是
`/usr/include/python2.7/pyport.h:886:2: 错误：#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."`

这个错误似乎是宏SIZEOF_LONG的多次定义的有关：
python头文件`/usr/include/python2.7/pyport.h`将SIZEOF_LONG定义为8
而`patch/include/boost/python/detail/wrap_python.hpp`又将SIZEOF_LONG定义为4
于是触发了`pyport.h`文件886行的error

**Comment by endyul** [comment]
sorry我刚才的解释有问题。python和gcc确实都是64位的。问题出在boost python，它只在cygwin gcc环境下，会把`SIZEOF_LONG`定义为4，导致64位python的`pyport.h`检查不通过(应为8)。
所以，我觉得是boost python的责任，很抱歉现在我还没有找到很好的解决方案，建议切换到32位的环境下解决。目前32位下，-DBOOST_PYTHON_SOURCE的选项是需要的，这会在下一个版本的pyltp解决。

**Comment by Di-Kai** [comment]
你在boost里面那个wrap_python.hpp中做如下改动：

    #if defined(_WIN32) || defined(__CYGWIN__)
    # if defined(__GNUC__) && defined(__CYGWIN__)
    #  define SIZEOF_LONG 8
注意把4改成8，就可以编译通过了。
