### ISSUE TITLE
error C3861: 'convert': identifier not found

### ISSUE THREAD

**Issue by starbaby01** [HIT-SCIR/pyltp#142]
error C3861: 'convert': identifier not found
windows 8.1系统，已安装VC++ BUILD TOOLS，下载pyltp 0.2.1解压到本地硬盘后，源码安装。
执行命令：python setup.py install
安装过程提示如下错误：

d:\data\pyltp-0.2.1\ltp\src\srl\include\extractor\Converter.h(35): error C3861: 'convert': identifier not found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
请问这个问题怎么解决，查了其他.h文件，没有convert

**Comment by starbaby01** [comment]
也没有给出解决方案，或者说明在哪个版本修复相关问题，怎么就关闭了？
问题并没有重复啊，我查过了相关问题，没有报'convert' 标识符错误的。

**Comment by liu946** [comment]
https://github.com/HIT-SCIR/ltp/issues/289

**Comment by liu946** [comment]
python 还没有更新
