### ISSUE TITLE
win10系统下尝试各种安装方法和条件一整天无法安装

### ISSUE THREAD

**Issue by little-yellow** [HIT-SCIR/pyltp#143]
安装失败包括pip install 和 下载代码python setup.py install，easy install等一系列能从issue里找到的方法

Win10 64bits / Python 3.6.4 on win32 官网下载版本 / Visual C++ 2015 Build Tools & VS 9.0

主要错误 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

代码
nodes-conv.cc
c:\users\74437\desktop\pyltp-master\ltp\thirdparty\eigen\eigen\src/Core/arch/CUDA/Half.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
c:\users\74437\desktop\pyltp-master\ltp\thirdparty\eigen\unsupported\eigen\cxx11\src/Tensor/Tensor.h(76): warning C4554: '&': check operator precedence for possible error; use parentheses to clarify precedence
c:\users\74437\desktop\pyltp-master\ltp\thirdparty\eigen\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(31): note: see reference to class template instantiation 'Eigen::Tensor<float,1,0,Eigen::DenseIndex>' being compiled
ltp/thirdparty/dynet/dynet/tensor.h(97): note: see reference to class template instantiation 'Eigen::TensorMap<Eigen::Tensor<float,1,0,Eigen::DenseIndex>,0,Eigen::MakePointer>' being compiled
ltp/thirdparty/dynet/dynet/weight-decay.h(27): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
ltp\thirdparty\dynet\dynet\nodes-conv.cc(179): warning C4838: conversion from 'unsigned int' to 'int' requires a narrowing conversion
ltp\thirdparty\dynet\dynet\nodes-conv.cc(182): note: see reference to function template instantiation 'void dynet::AverageColumns::backward_dev_impl<dynet::Device_CPU>(const dynet::Device_CPU &,const std::vector<const dynet::Tensor *,std::allocator<_Ty>> &,const dynet::Tensor &,const dynet::Tensor &,unsigned int,dynet::Tensor &) const' being compiled
        with
        [
            _Ty=const dynet::Tensor *
        ]
ltp\thirdparty\dynet\dynet\nodes-conv.cc(337): warning C4838: conversion from 'const unsigned int' to 'int' requires a narrowing conversion
ltp\thirdparty\dynet\dynet\nodes-conv.cc(344): note: see reference to function template instantiation 'void dynet::FoldRows::backward_dev_impl<dynet::Device_CPU>(const dynet::Device_CPU &,const std::vector<const dynet::Tensor *,std::allocator<_Ty>> &,const dynet::Tensor &,const dynet::Tensor &,unsigned int,dynet::Tensor &) const' being compiled
        with
        [
            _Ty=const dynet::Tensor *
        ]
ltp\thirdparty\dynet\dynet\nodes-conv.cc(368): warning C4018: '<': signed/unsigned mismatch
ltp\thirdparty\dynet\dynet\nodes-conv.cc(430): note: see reference to function template instantiation 'void dynet::KMaxPooling::forward_dev_impl<dynet::Device_CPU>(const dynet::Device_CPU &,const std::vector<const dynet::Tensor *,std::allocator<_Ty>> &,dynet::Tensor &) const' being compiled
        with
        [
            _Ty=const dynet::Tensor *
        ]
c:\users\74437\desktop\pyltp-master\ltp\thirdparty\eigen\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(242): error C2397: conversion from 'unsigned int' to 'int' requires a narrowing conversion
ltp\thirdparty\dynet\dynet\nodes-conv.cc(373): note: see reference to function template instantiation 'int &Eigen::TensorMap<Eigen::Tensor<Eigen::DenseIndex,4,0,Eigen::DenseIndex>,0,Eigen::MakePointer>::operator ()<unsigned int,unsigned int>(int,int,unsigned int,unsigned int)' being compiled
ltp\thirdparty\dynet\dynet\nodes-conv.cc(373): note: see reference to function template instantiation 'int &Eigen::TensorMap<Eigen::Tensor<Eigen::DenseIndex,4,0,Eigen::DenseIndex>,0,Eigen::MakePointer>::operator ()<unsigned int,unsigned int>(int,int,unsigned int,unsigned int)' being compiled
ltp\thirdparty\dynet\dynet\nodes-conv.cc(430): note: see reference to function template instantiation 'void dynet::KMaxPooling::forward_dev_impl<dynet::Device_CPU>(const dynet::Device_CPU &,const std::vector<const dynet::Tensor *,std::allocator<_Ty>> &,dynet::Tensor &) const' being compiled
        with
        [
            _Ty=const dynet::Tensor *
        ]
c:\users\74437\desktop\pyltp-master\ltp\thirdparty\eigen\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(245): error C2397: conversion from 'unsigned int' to 'int' requires a narrowing conversion
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

希望告知一个可以稳定安装的环境条件，包括Python版本，C++版本和安装方式（pip or 源代码）

**Comment by Joey-Liu** [comment]
这个问题我也遇到过， 最后安装了pyltp 0.1.9版本

**Comment by lovingxiuxiu** [comment]
如何选择版本安装呢？默认安装最新版

**Comment by Joey-Liu** [comment]
网络搜索 pip 使用方法

**Comment by little-yellow** [comment]
在多次尝试后，用了如下方法解决：
系统：win10
python： 官网 2.7版本
支持： Visual C++ 2015 Build Tools & VS 9.0
安装0.1.9版本，和对应模型
