### ISSUE TITLE
執行分詞範例時出錯

### ISSUE THREAD

**Issue by ChocolaNeko** [HIT-SCIR/pyltp#144]
安裝完成後，要執行分詞範例時(程式碼如下)

# -*- coding: utf-8 -*-
import sys
import os
from pyltp import Segmentor

#分詞
segmentor = Segmentor()
segmentor.load("C:\ltp_data_v3.4.0\cws.model")
words = segmentor.segment("元芳你怎麼看")
print "|".join(words)
segmentor.release()

跳出以下錯誤訊息

  File "C:/Users/user/Desktop/NLP/ltp_test.py", line 8, in <module>
    segmentor.load("C:\ltp_data_v3.4.0\cws.model")

RuntimeError: Invalid or unterminated Perl (?...) sequence.  The error occurred while parsing the regular expression fragment: 'A-Za-z\-](>>>HERE>>>(?�|[\-'\'.

使用作業系統為Windows 7 64bit 專業版
開發環境為 Anaconda2 (64-bit) 的 Spyder
Python版本為 2.7.13
Pyltp版本為 0.1.9.1 (由於0.2.0安裝會失敗，因此改裝舊版)

請問是否有其他人出現此狀況，解法為何?
感謝!!

**Comment by liu946** [comment]
不推荐使用anaconda安装。

**Comment by ChocolaNeko** [comment]
相同程式碼
改用python IDLE 執行時
仍然出現此錯誤訊息

Traceback (most recent call last):
  File "C:\Users\user\Desktop\NLP\ltp_test.py", line 8, in <module>
    segmentor.load("C:\ltp_data_v3.4.0\cws.model")
RuntimeError: Invalid or unterminated Perl (?...) sequence.  The error occurred while parsing the regular expression fragment: 'A-Za-z\-](>>>HERE>>>(?ﾔ||[\-'\'.
