### ISSUE TITLE
Boost.Python.ArgumentError: 

### ISSUE THREAD

**Issue by yongyuan923** [HIT-SCIR/pyltp#146]
# 代码
# -*- coding: utf-8 -*-
import os
from pyltp import SentenceSplitter
from pyltp import Postagger
from pyltp import Segmentor
from pyltp import NamedEntityRecognizer  
from pyltp import Parser
#模型路径
LTP_DATA_DIR = 'F:/LTP_cs/ltp_data'  # ltp模型目录的路径  
cws_model_path = os.path.join(LTP_DATA_DIR, 'cws.model')  # 分词模型路径，模型名称为`cws.model`  
pos_model_path = os.path.join(LTP_DATA_DIR, 'pos.model')  # 词性标注模型路径，模型名称为`pos.model`  
ner_model_path = os.path.join(LTP_DATA_DIR, 'ner.model')  # 命名实体识别模型路径，模型名称为`pos.model`  
par_model_path = os.path.join(LTP_DATA_DIR, 'parser.model') 
#初始化实例化
segmentor = Segmentor()
postagger = Postagger()
recognizer = NamedEntityRecognizer()
parser = Parser()
#加载模型路径
segmentor.load(cws_model_path)
postagger.load(pos_model_path)
recognizer.load(ner_model_path)
parser.load(par_model_path)
#读取文件
file=open("F:/cs/8.txt",'r',encoding='utf8')
s=file.read().encode('utf-8').strip()
#分句
sent=SentenceSplitter.split(s)
print('\n'.join(sent))
#print(type(sent))
#分词
words = segmentor.segment(sent) # 分词
words_list=list(words)
print ('\t'.join(words_list))
print(type(words))
#出现的问题
 words = segmentor.segment(sent) # 分词
Boost.Python.ArgumentError: Python argument types in
    Segmentor.segment(Segmentor, VectorOfString)
did not match C++ signature:
    segment(struct Segmentor {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
 #需解决的问题
对评论数据进行分句，再进行分词。就一直出现这种问题。请问错误怎么解决？
谢谢！望回复，万分感激。

**Comment by liu946** [comment]
目测是pyltp版本和ltp的C++版本不匹配导致的。可以卸载，源码安装重装一次。

**Comment by liu946** [comment]
仔细看示例可以发现 
```
sentence = SentenceSplitter.split(paragraph)[0]
words = segmentor.segment(sentence)
```
而你传入的是整个数组。类型不一致导致的。
