### ISSUE TITLE
model3.4 pyltp 0.2.1 语义角色标注 load问题

### ISSUE THREAD

**Issue by monkey1302** [HIT-SCIR/pyltp#148]
你好，语义角色标注时，load的问题？

我的问题是这样的：
Traceback (most recent call last):
  File "D:\project\comment analysis\ltptest.py", line 84, in <module>
    labeller.load(srl_model_path)
RuntimeError: incompatible native format - size of long

我的代码里：
LTP_DATA_DIR = 'D:/project/pyltp/ltp_data' 
srl_model_path = os.path.join(LTP_DATA_DIR, 'pisrl.model')
并且那个ltp_data文件夹里确实有pisrl.model这个文件

以上是仿照example.py运行的

-------------以下是第二个问题------------
我看文档说srl_model_path要用srl文件夹，而不是一个文件，但是我建好srl文件夹，pisrl.model放进去，结果为空。
srl_model_path = os.path.join(LTP_DATA_DIR, 'srl')

请问到底应该怎么操作？

**Comment by liu946** [comment]
您用的哪个版本？什么操作系统？为什么不按照我们的模板提供一些问题的相关信息呢？你这样问我们也不知道如何帮助你解决。

**Comment by liu946** [comment]
可以参考这个链接下载相应版本的模型。http://ltp.ai/download.html
