### ISSUE TITLE
pip安装pyltp失败

### ISSUE THREAD

**Issue by ghost** [HIT-SCIR/pyltp#150]
OS: win10(64bit)+python:3.6.4+VS2017,
用pip安装pyltp时报错，如下：
![ltp](https://user-images.githubusercontent.com/30196591/38196179-258900e0-36b4-11e8-9049-ef41a2d73fb4.png)
网上查了一下午的解决方法也没能解决问题，请帮我看看是什么原因，谢谢

**Comment by liu946** [comment]
请问你是编译到64位版本吗？

**Comment by WHongtao** [comment]
我直接用指令“pip install pyltp”安装，没指定编译到32位还是64位，不知道它编译到的是多少位的(O_O)

**Comment by WHongtao** [comment]
试了一下安装0.1.9.1版本却能成功

**Comment by Serendytg77** [comment]
遇到同样的问题，请问解决了么

**Comment by syw2014** [comment]
Have you solved this error?

**Comment by SquareWillson** [comment]
遇到同样的问题 一下午都解决不了 不知道怎么办

**Comment by SquareWillson** [comment]
pip install pyltp==0.1.9.1
成功了

**Comment by Chauncydecat** [comment]
> 
> 
> pip install pyltp==0.1.9.1
> 成功了

pyltp退回0.1.9版本后，SRL的加载路径有问题，找不到0.1.9的帮助文档
error: cannot open model:D:/python/ltp_data_v3.4.0\pisrl_win.model/srl.model
SRL: Model not loaded!

**Comment by AlucardNosferatu** [comment]
same issue

**Comment by Qwabee** [comment]
> > pip install pyltp==0.1.9.1
> > 成功了
> 
> pyltp退回0.1.9版本后，SRL的加载路径有问题，找不到0.1.9的帮助文档
> error: cannot open model:D:/python/ltp_data_v3.4.0\pisrl_win.model/srl.model
> SRL: Model not loaded!

same issue

**Comment by washujiang** [comment]
same issue
