### ISSUE TITLE
语义角色标注加载模型时失败

### ISSUE THREAD

**Issue by iceking112** [HIT-SCIR/pyltp#151]
## 问题*类型*
加载模型失败

## 出错*场景*
在使用pyltp做语义角色标注时，加载pisrl.model模型时失败
控制台报错：
    labeller.load(srl_model_path)  # 加载模型
RuntimeError: incompatible native format - size of long

## 代码片段
srl_model_path = os.path.join(LTP_MODEL_PATH, 'pisrl.model') 
labeller = SementicRoleLabeller() # 初始化实例
labeller.load(srl_model_path)  # 加载模型

## 如何复现这一错误
如上述即可复现

## 运行环境
win10，Python3.6，pyltp0.2.1，model3.4.0

## 其他
我是通过下载源码在本地进行编译的，另外readme中提到的在线教程里面语义角色标注部分加载模型时仍然是加载srl目录，请更新

**Comment by jeaken** [comment]
我这也是这个问题，不知道什么原因；
在几台电脑上试的都出现这个问题

**Comment by Asleda** [comment]
我也遇到这个问题，采纳楼上，完美解决

**Comment by Chauncydecat** [comment]
error: cannot open model:D:/python/ltp_data_v3.4.0/pisrl_win.model/srl.model
