### ISSUE TITLE
pyltp 编译失败

### ISSUE THREAD

**Issue by wanghouzhi** [HIT-SCIR/pyltp#157]
ltp/thirdparty/dynet/dynet/nodes.cc: At global scope:
    ltp/thirdparty/dynet/dynet/nodes.cc:2325: error: no ‘void dynet::Sum::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::Sum’
    ltp/thirdparty/dynet/dynet/nodes.cc:2325: error: no ‘void dynet::Sum::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::Sum’
    ltp/thirdparty/dynet/dynet/nodes.cc:2345: error: no ‘void dynet::SumElements::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::SumElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2345: error: no ‘void dynet::SumElements::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::SumElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2377: error: no ‘void dynet::MomentElements::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2377: error: no ‘void dynet::MomentElements::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2405: error: no ‘void dynet::StdElements::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::StdElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2405: error: no ‘void dynet::StdElements::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::StdElements’
    ltp/thirdparty/dynet/dynet/nodes.cc:2437: error: no ‘void dynet::MomentBatches::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2437: error: no ‘void dynet::MomentBatches::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2472: error: no ‘void dynet::MomentDimension::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2472: error: no ‘void dynet::MomentDimension::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::MomentDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2499: error: no ‘void dynet::StdDimension::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::StdDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2499: error: no ‘void dynet::StdDimension::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::StdDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2527: error: no ‘void dynet::StdBatches::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::StdBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2527: error: no ‘void dynet::StdBatches::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::StdBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2568: error: no ‘void dynet::SumBatches::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::SumBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2568: error: no ‘void dynet::SumBatches::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::SumBatches’
    ltp/thirdparty/dynet/dynet/nodes.cc:2597: error: no ‘void dynet::TraceOfProduct::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::TraceOfProduct’
    ltp/thirdparty/dynet/dynet/nodes.cc:2597: error: no ‘void dynet::TraceOfProduct::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::TraceOfProduct’
    ltp/thirdparty/dynet/dynet/nodes.cc:2613: error: no ‘void dynet::Tanh::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::Tanh’
    ltp/thirdparty/dynet/dynet/nodes.cc:2613: error: no ‘void dynet::Tanh::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::Tanh’
    ltp/thirdparty/dynet/dynet/nodes.cc:2639: error: no ‘void dynet::Transpose::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::Transpose’
    ltp/thirdparty/dynet/dynet/nodes.cc:2639: error: no ‘void dynet::Transpose::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::Transpose’
    ltp/thirdparty/dynet/dynet/nodes.cc:2656: error: no ‘void dynet::Zeroes::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::Zeroes’
    ltp/thirdparty/dynet/dynet/nodes.cc:2656: error: no ‘void dynet::Zeroes::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::Zeroes’
    ltp/thirdparty/dynet/dynet/nodes.cc:2673: error: no ‘void dynet::RandomNormal::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomNormal’
    ltp/thirdparty/dynet/dynet/nodes.cc:2673: error: no ‘void dynet::RandomNormal::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomNormal’
    ltp/thirdparty/dynet/dynet/nodes.cc:2690: error: no ‘void dynet::RandomBernoulli::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomBernoulli’
    ltp/thirdparty/dynet/dynet/nodes.cc:2690: error: no ‘void dynet::RandomBernoulli::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomBernoulli’
    ltp/thirdparty/dynet/dynet/nodes.cc:2707: error: no ‘void dynet::RandomUniform::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomUniform’
    ltp/thirdparty/dynet/dynet/nodes.cc:2707: error: no ‘void dynet::RandomUniform::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomUniform’
    ltp/thirdparty/dynet/dynet/nodes.cc:2726: error: no ‘void dynet::RandomGumbel::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomGumbel’
    ltp/thirdparty/dynet/dynet/nodes.cc:2726: error: no ‘void dynet::RandomGumbel::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::RandomGumbel’
    ltp/thirdparty/dynet/dynet/nodes.cc:2775: error: no ‘void dynet::MaxDimension::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::MaxDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2775: error: no ‘void dynet::MaxDimension::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::MaxDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2824: error: no ‘void dynet::MinDimension::forward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const’ member function declared in class ‘dynet::MinDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc:2824: error: no ‘void dynet::MinDimension::backward_impl(const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const’ member function declared in class ‘dynet::MinDimension’
    ltp/thirdparty/dynet/dynet/nodes.cc: In member function ‘void dynet::RestrictedLogSoftmax::forward_dev_impl(const MyDevice&, const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, dynet::Tensor&) const [with MyDevice = dynet::Device_CPU]’:
    ltp/thirdparty/dynet/dynet/nodes.cc:1914:   instantiated from here
    ltp/thirdparty/dynet/dynet/nodes.cc:1888: warning: unused variable ‘logz’
    ltp/thirdparty/dynet/dynet/nodes.cc: In member function ‘void dynet::RestrictedLogSoftmax::backward_dev_impl(const MyDevice&, const std::vector<const dynet::Tensor*, std::allocator<const dynet::Tensor*> >&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const [with MyDevice = dynet::Device_CPU]’:
    ltp/thirdparty/dynet/dynet/nodes.cc:1914:   instantiated from here
    ltp/thirdparty/dynet/dynet/nodes.cc:1907: warning: unused variable ‘z’
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/wanghouzhi/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qgwp6_wd/pyltp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mg4fdtwe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qgwp6_wd/pyltp/

**Comment by wanghouzhi** [comment]
(base) [wanghouzhi@dx-meishi-data-mining01 miniconda3]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

**Comment by DukeEnglish** [comment]
使用pip把

**Comment by pipi2012** [comment]
请问，您这个问题有解决么？
