### ISSUE TITLE
pyltp句法分析接口只有head,relation;没有tail节点。如何确定一条唯一的弧

### ISSUE THREAD

**Issue by DavidJiang** [HIT-SCIR/pyltp#158]
## 代码片段
from pyltp import Parser
parser = Parser() # 初始化实例
parser.load(par_model_path)  # 加载模型
words = ['元芳', '你', '怎么', '看']
postags = ['nh', 'r', 'r', 'v']
arcs = parser.parse(words, postags)  # 句法分析
print "\t".join("%d:%s" % (arc.head, arc.relation) for arc in arcs)

##输出
4:SBV       4:SBV   4:ADV   0:HED

##
我期待的输出是head:4（看）。relation:SBV。  tail：1(元芳)

但是在数据结构arcs中并不能找到tail这样的信息。我打印的属性也没有看到相关信息：

![image](https://user-images.githubusercontent.com/5820413/39869404-e68903b4-548f-11e8-8d23-069bcb6be916.png)

##期待结果
得到一条完整的弧：head:4（看）。relation:SBV。  tail：1(元芳)
期望给予解答，多谢！

**Comment by DavidJiang** [comment]
找到答案了，当前弧所在的节点下标就是对应的tail。如上面例子结果为：
![image](https://user-images.githubusercontent.com/5820413/40211077-12d07718-5a7b-11e8-9f5f-39c6075eca43.png)

结果：4:SBV     4:SBV     4:ADV     0:HED
      4->1      4->2      4->3      0->4

**Comment by jiangweisuc** [comment]
我总觉得是输出的不是head,而是tail,当前节点是head，这样才和图上对应上？是这样的吗？ @DavidJiang

**Comment by liu946** [comment]
@jiangweisuc 输出是按照句子中每个词节点的head的索引。Root对应索引0。

**Comment by jiangweisuc** [comment]
谢谢刘老师@liu946，LTP的输出看懂了。只是我别的文献里看到的和这里有点不一样，比如有向弧<a, b>箭头从a指向b，a是起始点，b是结束点；a是父节点，b是子节点，代表从a到b的有向边，则a是tail，b是head。而结合上图和LTP的输出看，在LTP程序的逻辑上定义了箭头指向的词为tail，箭头的起始词为head，是这样么？谢谢啦
