### ISSUE TITLE
使用外部词性标注词典时出现问题

### ISSUE THREAD

**Issue by Cugfu** [HIT-SCIR/pyltp#160]
操作系统是Linux，python3.5，pyltp0.2.1
代码是：
import os
LTP_DATA_DIR = 'ltp_data' 
pos_model_path = os.path.join(LTP_DATA_DIR, 'pos.model')  
from pyltp import Postagger
postagger = Postagger()
postagger.load(pos_model_path) 
postagger1 = Postagger()
postagger1.load_with_lexicon(pos_model_path, 'u_dict.txt')
words = ['一个标准', '名调']  # 分词结果
postags1 = postagger.postag(words)  # 词性标注
postags2 = postagger1.postag(words)

print('\t'.join(postags1))
postagger.release()
print('\t'.join(postags2))
postagger1.release()

虽然用户词典u_dict.txt中定义了词性，但是分词结果与用户定义完全无关，输出的词性效果与未添加外部词性词典的效果是相同的

**Comment by liu946** [comment]
外部词典不能定义新词性，需要重新构造训练数据。
