### ISSUE TITLE
pyltp命名实体识别结果全为O

### ISSUE THREAD

**Issue by iambyd** [HIT-SCIR/pyltp#168]
## 问题*类型*
命名实体识别模型识别出的内容全为O

## 出错*场景*
命名实体识别结果出错，结果一直不变，任意输入结果均为O

## 代码片段
string = '元芳你怎么看'
segmentor = Segmentor()
segmentor.load('./ltp_data_v3.4.0/cws.model')
words = segmentor.segment(string)
postagger = Postagger()
postagger.load('./ltp_data_v3.4.0/pos.model')
postags = postagger.postag(words)
recognizer = NamedEntityRecognizer()
recognizer.load('./ltp_data_v3.4.0/ner.model')
netags = recognizer.recognize(words, postags)
print('\n'.join(netags))
得到的结果为
O       
O      
O   
O
## 运行环境

操作系统：Ubuntu 18
python版本：3.6
pyltp版本：0.2.1
ltp模型版本：3.4

## 期望结果
官网介绍的结果为：
S-Nh        O       O       O

## 备注：分词和词性标注得到的结果与官方文档保持一致：
words: 元芳  你       怎么      看
postags: nh  r       r       v

**Comment by liu946** [comment]
无法复现您的问题，请详细说明一下您的安装方法。

**Comment by iambyd** [comment]
您好，我是按照你们的指示安装的，命令如下：
 $ git clone https://github.com/HIT-SCIR/pyltp
 $ git submodule init
 $ git submodule update
 $ python setup.py install 
我的环境是ubuntu18，目前命名实体提取的结果全部都是O，分词和词性标注结果没问题，这个是我下载的模型文件有问题，还是安装过程存在问题

**Comment by liu946** [comment]
可以提供一下demo运行时的log吗？

**Comment by iambyd** [comment]
已经调试好了，貌似跟IDE有关，我直接在命令行下运行代码无误，再visual studio code里面运行结果就有问题
