### ISSUE TITLE
Python 2.7.6 通过pip安装pyltp失败

### ISSUE THREAD

**Issue by tslmy** [HIT-SCIR/pyltp#17]
In file included from ltp/src/ner/decoder.cpp:1:
    In file included from ltp/src/ner/decoder.h:8:
    ltp/src/utils/unordered_set.hpp:75:27: error: redefinition of '__gnu_cxx::hash<unsigned long long>'
            template<> struct hash<unsigned long long> {
                              ^~~~~~~~~~~~~~~~~~~~~~~~
    ltp/src/utils/unordered_map.hpp:75:27: note: previous definition is here
            template<> struct hash<unsigned long long> {
                              ^
    In file included from ltp/src/ner/decoder.cpp:1:
    In file included from ltp/src/ner/decoder.h:8:
    ltp/src/utils/unordered_set.hpp:80:37: error: redefinition of 'hash<type-parameter-0-0 *>'
            template<typename T> struct hash<T *> {
                                        ^~~~~~~~~
    ltp/src/utils/unordered_map.hpp:80:37: note: previous definition is here
            template<typename T> struct hash<T *> {
                                        ^
    In file included from ltp/src/ner/decoder.cpp:1:
    In file included from ltp/src/ner/decoder.h:8:
    ltp/src/utils/unordered_set.hpp:85:27: error: redefinition of '__gnu_cxx::hash<std::string>'
            template<> struct hash<std::string> {
                              ^~~~~~~~~~~~~~~~~
    ltp/src/utils/unordered_map.hpp:85:27: note: previous definition is here
            template<> struct hash<std::string> {
                              ^
    In file included from ltp/src/ner/decoder.cpp:1:
    ltp/src/ner/decoder.h:15:8: error: no template named 'unordered_set' in namespace 'std'; did you mean 'unordered_map'?
      std::unordered_set<size_t> rep;
      ~~~~~^~~~~~~~~~~~~
           unordered_map
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__hash_table:217:85: note: 'unordered_map' declared here
        template <class, class, class, class, class> friend class _LIBCPP_TYPE_VIS_ONLY unordered_map;
                                                                                        ^
    In file included from ltp/src/ner/decoder.cpp:1:
    ltp/src/ner/decoder.h:15:8: error: too few template arguments for class template 'unordered_map'
      std::unordered_set<size_t> rep;
           ^

此处省略一堆warning和note。。。

    56 warnings and 5 errors generated.
    error: command 'cc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/pyltp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().

**Comment by Oneplus** [comment]
您能否提供一下c++版本和系统信息？

**Comment by tslmy** [comment]
$ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.0.0/5.0.0/lto-wrapper
    Target: x86_64-apple-darwin14.0.0
    Configured with: ../gcc-5-20141005/configure --enable-languages=c++,fortran
    Thread model: posix
    gcc version 5.0.0 20141005 (experimental) (GCC)

**Comment by runninghack** [comment]
同样遇到了这个问题，请问有解决方法吗？

**Comment by endyul** [comment]
@runninghack 能否提供一下编译器和系统版本信息？ 我今天解决一下

**Comment by runninghack** [comment]
```
RamieldeMacBook-Pro:ltp ramiel$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

系统为OS X Yosemit 10.10.5 (14F27)

谢谢！

**Comment by endyul** [comment]
@runninghack 使用

**Comment by runninghack** [comment]
谢谢。之前的error没有了，不过又报了一个新的error。

```
ltp/src/utils/unordered_map.hpp:25:10: fatal error: 'unordered_map' file not
      found
#include <unordered_map>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by runninghack** [comment]
已解决，setup.py中68行加了两个参数，改为：
```
extra_compile_args += ['-std=c++11', '-Wno-c++11-narrowing',"-mmacosx-version-min=10.8",'-stdlib=libc++']
```

**Comment by endyul** [comment]
@runninghack 感谢
