### ISSUE TITLE
在load cws model和pos model路径的时候出错

### ISSUE THREAD

**Issue by troyddddd** [HIT-SCIR/pyltp#177]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

在传入cws mode和pos model的路径的时候报错:segmentor.load()和postagger.load()
## 出错*场景*

ArgumentError: Python argument types in
    Segmentor.load(Segmentor, unicode)
did not match C++ signature:
    load(Segmentor {lvalue}, std::string)
## 运行环境

python2.7

**Comment by adamwoo** [comment]
segment=Segment()，postagger 也是
