### ISSUE TITLE
运行README.rst中的例子出错：Segmentor: Model not loaded!

### ISSUE THREAD

**Issue by jingjinjingjin** [HIT-SCIR/pyltp#18]
# -*- coding: utf-8 -*-
import os
from pyltp import Segmentor
segmentor = Segmentor()
filename = r'/home/jingjin/code/py_code/ltp_data/cws.model'
if os.path.exists(filename):
	print 'cws.model exists'
else:
	print 'sorry'
segmentor.load(filename)
words = segmentor.segment("元芳你怎么看")
print "|".join(words)

=============================
输出：
cws.model exists
Segmentor: Model not loaded!

环境：
ubuntu 14.04 LTS
32位
python2.7.6

**Comment by jingjinjingjin** [comment]
我在另外一台电脑没问题. 有问题的那台在pip安装pyltp之前, 有用源码安装过,但是没有加sudo,因为权限问题导致安装失败. 不知道是不是这个原因

**Comment by cindymuji** [comment]
使用的是pycharm
提示：
cws.model exists
Segmentor: Model not loaded!

**Comment by endyul** [comment]
@cindymuji 是否用的是repo中ltp_data中的model？
请使用https://github.com/HIT-SCIR/ltp 中的模型，下载地址是http://pan.baidu.com/share/link?shareid=1988562907&uk=2738088569

**Comment by cindymuji** [comment]
选择哪一个版本呢？我之前用的是3.3.0@endyul

**Comment by endyul** [comment]
用3.3.0的模型

**Comment by cindymuji** [comment]
可以了，谢谢

**Comment by leefionglee** [comment]
是不是3.3.1的不行？ 我用的3.3.1的显示加载失败。@endyul

**Comment by endyul** [comment]
@leefionglee 是的，请先按照文档使用 3.3.0 版本模型

**Comment by leefionglee** [comment]
好的，谢谢

**Comment by lxj0276** [comment]
加载分词本地词典有问题的
segmentor = Segmentor()
segmentor.load_with_lexicon('E:/code/LTP/ltp_data/cws.model','E:/code/python_code/extractEventsTestApi/searchTrigger/dict/mydict.txt')，mydict.txt是u8编码，格式如下
恒生
农银信用债
 等等
出现Segmentor: Model not loaded!， 是怎么回事
