### ISSUE TITLE
分词结果与在线演示不同

### ISSUE THREAD

**Issue by Waldenz** [HIT-SCIR/pyltp#181]
例句：
东湖公安分局于22日凌晨对熊某某作出行政拘留10日的处罚。

代码切词结果：
东湖    公安    分局    于      22日    凌晨    对熊    某某    作出    行政    拘留    10日    的  处罚

官网在线演示切词结果：
东湖公安分局  于  22日凌晨  对  熊某某  作出  行政拘留  10日  的  处罚  。

明显在线演示的结果分词效果更好，是做什么处理了吗？

**Comment by shd101wyy** [comment]
同问 +1

**Comment by carfly** [comment]
在线系统是商用版本的效果，做了更多优化。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by shd101wyy** [comment]
打扰作者了，非常感谢您的解答。
请问开源的版本还会继续更新模型吗？
谢谢!
