### ISSUE TITLE
分词结果都是空的

### ISSUE THREAD

**Issue by houwenxin** [HIT-SCIR/pyltp#183]
问题：分词结果都是空的，似乎是加载模型有问题，代码中即使path给的是错的也没有任何报错。
使用python setup.py install安装的，环境为Python 3.6.1 :: Anaconda 4.4.0 (64-bit)，代码是在Spyder运行的，请问是什么原因呢？怎么解决？
代码：
from pyltp import Segmentor
segmentor = Segmentor()
segmentor.load(path)
sample = "你好"
words = segmentor.segment(sample)
print(list(words))

**Comment by houwenxin** [comment]
自己找到了答案，模型的路径中不能出现中文.....我们自己的软件也有这个要求......真实

**Comment by Azuk1** [comment]
我的路径没有中文也不行 第一次测试时出现了 重启内核后再怎么试都不行了。。。。。
