### ISSUE TITLE
支持3.7.2吗

### ISSUE THREAD

**Issue by shenjichenai** [HIT-SCIR/pyltp#184]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by sherlockhoatszx** [comment]
我是python3.7的，用不了。。

**Comment by jtyoui** [comment]
我是python3.7的，用不了。。

**Comment by qwtao** [comment]
> Compile error on 3.7.2 x64: `patch\libs\python\src\converter\builtin_converters.cpp(51): error C2440: 'return': cannot convert from 'const char *' to 'void *'`

我也碰到了这个问题：**error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]**

**Comment by Dobatymo** [comment]
@qwtao 谢谢. There is no such flag on MSVC, but the code change from the issue you linked solved it as well.

**Comment by ReactiveCJ** [comment]
@Dobatymo 
At line 51, change the code to const_cast<char *>(PyUnicode_Check(obj) ? _PyUnicode_AsString(obj) : 0); then you can install without errors

**Comment by DraculaXly** [comment]
> https://github.com/DraculaXly/Python/tree/master/Wheel
win10 + python3.7.3 打包的
偷懒的童鞋可以直接下载WHEEL安装，吼吼

**Comment by cdhx** [comment]
@DraculaXly
首先感谢提供的whl ！
大佬你是怎么编译的呀，不是不支持3.7吗

**Comment by shangbl** [comment]
> > https://github.com/DraculaXly/Python/tree/master/Wheel
> > win10 + python3.7.3 打包的
> > 偷懒的童鞋可以直接下载WHEEL安装，吼吼

你好，python3.7.0 使用时出现 

Traceback (most recent call last):
  File "E:/code_warehouse/data_clustering_classification/test.py", line 260, in <module>
    ner()
  File "E:/code_warehouse/data_clustering_classification/test.py", line 253, in ner
    segmentor = Segmentor(str(model_path))
Boost.Python.ArgumentError: Python argument types in
    None.__init__(Segmentor, str)
did not match C++ signature:
    __init__(struct _object * __ptr64)

初始化 None  有遇到过吗
