### ISSUE TITLE
依存句法分析结果和语言云不一样，model是3.3版本

### ISSUE THREAD

**Issue by zenghsh3** [HIT-SCIR/pyltp#19]
这个python接口是和语言云分析一样的吗，用3.3 model的话？打扰了，谢谢！

**Comment by endyul** [comment]
这是本地版，接口和语言云的rest api不同，使用样例可以见`example/example.py`
model用3.3版本就行

**Comment by zenghsh3** [comment]
感谢那么快的回答，我是想问分析结果会和语言云不一样吗？另外，好像语义角色分析返回None，谢谢！

**Comment by endyul** [comment]
@zenghsh3 因为本地版的模型和语言云使用的模型有一些差别，确实存在有些结果不一样的现象。语义角色返回None可能是这句话没有语义角色。

能否提供具体的例子？

**Comment by zenghsh3** [comment]
谢谢你的回答，确实是有些句子没有语义角色的原因！
