### ISSUE TITLE
发现bug，句法依存分析时，当句子很长的时候，可能会让python异常停止。

### ISSUE THREAD

**Issue by beyondguo** [HIT-SCIR/pyltp#190]
### 当我的words和tags是以下的时候：

[['“', '师者', '，', '所以', '传道', '授业', '解惑', '也', '。', '”', '这', '是', '唐代', '著名', '文学家', '、', '思想家', '韩愈', '先生', '对', '教师', '这', '一', '职业', '的', '经典', '定义', '，', '也', '是', '广大', '师范生', '及', '在校', '教师', '奉', '为', '圭臬', '的', '至理名言', '。', '带', '着', '这样', '的', '标准', '和', '目标', '，', '2018年', '3月', '5日', '，', '我', '怀着', '忐忑', '而', '又', '兴奋', '的', '心情', '来到', '平和县', '大溪', '中学', '，', '开始', '了', '为期', '一', '学期', '的', '实习', '支教', '生活', '。', '在', '三', '个', '多', '月', '的', '时间', '里', '，', '原先', '的', '教学', '理论', '一点点', '转化', '为', '教学', '实践', '，', '模拟', '教学', '变为', '真正', '面对面', '的', '教学', '。', '这', '一', '段', '宝贵', '的', '实习', '支教', '时光', '让', '我', '受益匪浅', '，', '也', '让', '我', '更加', '严格', '地', '要求', '自己', '“', '要', '以', '一', '名', '正式', '老师', '”', '的', '标准', '教书育人', '、', '对', '学生', '负责', '。', '现', '我', '就', '本次', '实习', '支教', '进行', '总结', '。', '一', '、', '班主任', '工作', '作为', '实习班', '主任', '，', '我', '深知', '班主任', '工作', '的', '重要性', '，', '班主任', '不仅仅', '是', '一个', '班级', '的', '组织者', '和', '管理者', '，', '更', '是', '一个', '班级', '的', '教育者', '。', '因此', '在', '实习', '的', '第一', '周', '我', '记', '下', '了', '班', '上', '所有', '同学', '的', '名字', '，', '想', '要', '快', '点', '与', '他们', '熟络', '起来', '、', '融入', '学生', '当中', '。', '每天', '我', '都', '坚持', '到', '班', '上', '看', '早', '读', '，', '一方面', '可以', '管管', '早', '读', '的', '纪律', '，', '一方面', '也', '可', '更', '熟悉', '学生', '、', '与', '学生', '亲近', '，', '可谓', '一举两得', '。', '课余', '时间', '我', '常', '与', '孩子', '们', '聊天', '谈话', '，', '通过', '交流', '可以', '了解', '孩子', '们', '的', '家庭', '情况', '及', '内心', '真实', '的', '想法', '，', '这样', '有利于', '帮助', '他们', '解决', '学习', '上', '和', '生活', '上', '的', '困难', '。', '此外', '，', '我', '给', '同学', '们', '每周', '布置', '了', '两', '篇', '周记', '，', '在', '周记', '中', '孩子', '们', '可以', '畅所欲言', '，', '无', '字数', '和', '形式', '上', '的', '要求', '，', '这样', '学生', '可', '发挥', '的', '空间', '就', '很', '大', '，', '周记', '也', '成为', '了', '我', '和', '孩子', '们', '沟通', '互动', '的', '桥梁', '。', '作为', '班主任', '，', '每周', '一', '次', '的', '主题', '班会', '课', '也', '尤为', '重要', '，', '通过', '班会', '课', '可', '结合', '实际', '对', '学生', '进行', '主题', '教育', '，', '如', '：', '开学', '安全', '教育', '、', '中国', '传统', '节日', '清明节', '、', '良好', '的', '课堂', '纪律', '、', '防止', '校园', '欺凌', '等等', '，', '几', '次', '班会', '课', '下来', '，', '学生', '们', '反映', '良好', '，', '有些', '同学', '还', '会', '在', '周记', '中', '写', '出', '自己', '的', '感悟', '。', '另外', '，', '班主任', '还', '应', '注重', '发挥', '班', '干部', '的', '带头', '作用', '。', '这', '学期', '我', '让', '班', '干部', '联合', '小组长', '管理', '班级', '课堂', '纪律', '，', '采用', '“', '推举制', '”', '表彰', '每周', '“', '守纪', '之', '星', '”', '；', '每月', '一', '次', '的', '班级', '大', '扫除', '也', '由', '班', '干部', '牵头', '进行', '；', '六一', '儿童', '节前', '我', '召开', '了', '班委会', '，', '和', '班', '干部', '们', '一起', '策划', '了', '六一', '主题', '活动', '......', '再者', '，', '孩子', '的', '教育', '离', '不', '开', '老师', '和', '家长', '的', '共同', '协作', '，', '作为', '班主任', '更', '应', '身先士卒', '。', '担任', '实习班', '主任', '期间', '，', '我', '能够', '及时', '与', '部分', '家长', '交流', '学生', '近况', '，', '反映', '相关', '问题', '，', '与', '家长', '做', '好', '沟通', '的', '工作', '。', '总结', '一', '学期', '的', '实习班', '主任', '工作', '，', '仍', '有', '许多', '需要', '改进', '的', '地方', '，', '我', '将', '及时', '总结', '经验', '教训', '，', '继续', '努力', '！', '二', '、', '教学', '工作', '作为', '实习', '语文', '老师', '，', '我', '在', '指导', '教师', '的', '指导', '帮助', '下', '，', '充分', '利用', '课余', '时间', '钻研', '教材', '和', '辅导', '材料', '，', '了解', '学生', '的', '具体', '水平', '，', '有', '针对性', '地', '进行', '备课', '，', '争取', '在', '每', '节', '课', '上课', '前', '把', '将要', '讲', '的', '知识点', '多', '过', '几', '遍', '；', '但是', '，', '仅仅如此', '是', '远远', '不够', '，', '教学', '环节', '会', '出现', '很多', '意想不到', '的', '突发', '情况', '，', '如何', '应对', '和', '解决', '就', '需要', '自己', '主动', '向', '其他', '老师', '虚心', '请教', '并', '逐渐', '积累', '经验', '。', '实习', '前', '几', '周', '，', '我', '坚持', '每周', '听', '4', '节', '课', '以上', '，', '并且', '在', '课', '前', '提前', '跟', '任课', '老师', '打', '好', '招呼', '，', '对', '所', '要', '上', '的', '内容', '进行', '了解', '并', '记', '下', '问题', '，', '带', '着', '问题', '去', '听课', '，', '课后', '及时', '找', '老师', '探讨', '。', '通过', '探讨', '，', '丰富', '了', '我', '对', '这', '一', '课', '教材', '和', '教法', '的', '认识', '。', '听', '过', '十几', '位', '老师', '的', '不同', '的', '授课', '方式', '，', '吸取', '了', '许多', '的', '经验', '，', '发现', '每个', '老师', '都', '有', '各自', '不同', '的', '教学', '风格', '，', '让', '我', '明白', '了', '“', '教', '无', '定论', '”', '的', '真正', '含义', '，', '对', '之后', '的', '教学', '有着', '巨大', '的', '启迪', '作用', '。', '此外', '，', '注重', '课', '后', '落实', '也', '是', '教师', '工作', '中', '的', '重中之重', '。', '我', '采用', '竞争', '奖励', '机制', '，', '每次', '小测', '、', '考试', '前', '让', '同学', '们', '设立', '目标', '，', '之后', '表现', '优异', '的', '同学', '可', '获得', '相应', '的', '奖励', '，', '这种', '办法', '对', '七', '年级', '的', '学生', '尤其', '适用', '。', '对于', '那些', '不', '肯', '落实', '的', '后进生', '，', '我', '会', '根据', '其', '实际', '情况', '酌情', '布置', '其他', '“', '特殊', '任务', '”', '给', '他', '，', '通常', '我', '会', '利用', '放学', '时间', '为', '其', '查', '缺', '补', '漏', '，', '并', '要求', '其', '在', '一定', '时间', '内', '完成', '适量', '的', '落实', '工作', '。', '这样', '“', '减负荷', '”', '的', '任务', '会', '让', '后进生', '更', '有', '自信', '和', '动力', '去', '落实', '，', '一', '学期', '下来', '，', '部分', '后进生', '的', '成绩', '果然', '有所', '提高', '。', '再者', '，', '批改', '作业', '、', '纠正', '学生', '的', '错误', '在', '教学', '工作', '中', '也', '是', '非常', '重要', '的', '。', '我', '在', '纠正', '学生', '错误', '的', '时候', '不', '忘', '写', '上', '激励', '的', '评语', '，', '并', '在', '评语', '中', '强调', '订正', '的', '重要性', '，', '根据', '各个', '学生', '的', '情况', '加以', '勉励', '和', '开导', '。', '最后', '，', '这', '学期', '我', '在', '班', '上', '召开', '了', '两', '次', '校级', '公开课', '：', '《', '河', '中石兽', '》', '和', '《', '课堂', '礼仪', '》', '，', '课堂', '整体', '氛围', '和', '效果', '不错', '，', '但', '仍', '有', '许多', '可', '圈', '可', '点', '之', '处', '，', '课后', '我', '积极', '向', '指导', '老师', '及', '其他', '老师', '请教', '不足', '之', '处', '，', '老师', '们', '提出', '的', '宝贵', '意见', '让', '我', '对于', '怎样', '提高', '课堂', '教学', '质量', '和', '教学', '效率', '有', '了', '更', '深刻', '而', '明确', '的', '方向', '认识', '，', '我', '将', '继续', '努力', '，', '提高', '自己', '的', '教学', '水平', '。', '三', '、', '留守', '儿童', '关爱', '工作', '留守', '儿童', '的', '教育', '是', '在', '社会', '发展', '形势', '下', '学校', '教育', '面临', '的', '新', '课题', '，', '留守', '儿童', '已经', '成为', '社会', '关注', '的', '焦点', '，', '更', '是', '教育者', '进行', '教育', '工作', '的', '重点', '。别林斯基', '说', '过', '：', '“', '爱', '是', '鉴别', '教育', '的', '尺度', '。', '”', '许多', '教育家', '也', '指出', '，', '没有', '对', '学生', '的', '爱', '，', '就', '不', '会', '有', '真正', '的', '教育', '，', '爱', '是', '教育', '学生', '前提', '，', '作为', '“', '童享', '阳光', '”', '项目', '的', '参与者', '，', '我', '坚持', '以', '爱心', '作为', '各项', '关爱', '工作', '的', '宗旨', '。', '开学', '第一', '周', '，', '我', '向', '指导', '班主任', '了解', '了', '班', '上', '学生', '的', '家庭', '情况', '，', '并', '与', '个别', '留守', '儿童', '结', '对子', '开展', '相应', '活动', '。', '通过', '沟通', '、', '交流', '，', '学生', '们', '都', '很', '愿意', '在', '周记', '中', '或', '在', '课后', '与', '我', '分享', '心路', '历程', '，', '而', '我', '也', '常常', '以', '“', '大', '姐姐', '”', '的', '身份', '与', '他们', '分享', '一些', '自己', '的', '感受', '、', '趣事', '，', '无形', '之中', '师生', '之间', '的', '关系', '发生', '了', '微妙', '的', '变化', '。', '另外', '，', '我们', '还', '会', '组织', '相应', '的', '主题', '团辅', '活动', '、', '周末', '读书', '活动', '、', '课', '下', '学科', '辅导', '活动', '，', '通过', '这些', '活动', '，', '使', '孩子', '们', '的', '课余', '生活', '更加', '丰富', '，', '能够', '“', '在', '玩', '中学', '、', '在', '学', '中', '玩', '”', '，', '乐趣', '无穷', '。', '由于', '班', '上', '绝大多数', '学生', '都', '是', '留守', '儿童', '，', '我', '便', '会', '利用', '一些', '时间', '在', '班级', '进行', '集体', '主题', '交流会', '，', '内容', '形式', '不', '限', '，', '如', '“', '电影', '欣赏', '”', '、', '“', '漫步', '太空', '”', '、', '“', '寒食节', '知', '多少', '”', '、', '“', '期中考', '表彰', '大会', '”', '、', '“', '六一', '欢乐', '会', '”', '等', '，', '让', '学生', '在', '主题', '交流会', '上', '畅所欲言', '，', '感受', '学习', '的', '乐趣', '、', '生活', '的', '奥秘', '，', '体会', '老师', '与', '其他', '同学', '的', '温暖', '等等', '。', '时光荏苒', '，', '三', '个', '多', '月', '的', '实习', '支教', '生活', '已', '过去', '。', '这', '一', '段', '时光', '，', '不仅仅', '是', '我', '人生', '中', '一', '段', '珍贵', '的', '记忆', '，', '更', '是', '我', '接下来', '生活', '的', '新', '起点', '。', '今后', '，', '我', '将', '更加', '严格', '地', '要求', '自我', '，', '坚持', '优点', '、', '及时', '改正', '自身', '不足', '，', '更', '进一步', '！'], ['wp', 'n', 'wp', 'c', 'v', 'v', 'v', 'u', 'wp', 'wp', 'r', 'v', 'nt', 'a', 'n', 'wp', 'n', 'nh', 'n', 'p', 'n', 'r', 'm', 'n', 'u', 'n', 'n', 'wp', 'd', 'v', 'b', 'n', 'c', 'v', 'n', 'v', 'v', 'n', 'u', 'i', 'wp', 'v', 'u', 'r', 'u', 'n', 'c', 'n', 'wp', 'nt', 'nt', 'nt', 'wp', 'r', 'v', 'a', 'c', 'd', 'a', 'u', 'n', 'v', 'ns', 'ns', 'n', 'wp', 'v', 'u', 'v', 'm', 'n', 'u', 'v', 'j', 'v', 'wp', 'p', 'm', 'q', 'm', 'n', 'u', 'n', 'nd', 'wp', 'b', 'u', 'v', 'n', 'm', 'v', 'v', 'n', 'v', 'wp', 'v', 'v', 'v', 'd', 'i', 'u', 'v', 'wp', 'r', 'm', 'q', 'a', 'u', 'v', 'j', 'n', 'v', 'r', 'i', 'wp', 'd', 'v', 'r', 'd', 'a', 'u', 'v', 'r', 'wp', 'v', 'p', 'm', 'q', 'a', 'n', 'wp', 'u', 'n', 'i', 'wp', 'p', 'n', 'v', 'wp', 'nt', 'r', 'd', 'r', 'v', 'j', 'v', 'v', 'wp', 'm', 'wp', 'n', 'v', 'v', 'n', 'n', 'wp', 'r', 'v', 'n', 'v', 'u', 'n', 'wp', 'n', 'd', 'v', 'm', 'n', 'u', 'n', 'c', 'n', 'wp', 'd', 'v', 'm', 'n', 'u', 'n', 'wp', 'c', 'p', 'v', 'u', 'm', 'q', 'r', 'v', 'v', 'u', 'n', 'nd', 'b', 'n', 'u', 'n', 'wp', 'v', 'v', 'a', 'q', 'p', 'r', 'v', 'v', 'wp', 'v', 'n', 'nd', 'wp', 'r', 'r', 'd', 'v', 'v', 'n', 'nd', 'v', 'a', 'v', 'wp', 'c', 'v', 'v', 'a', 'v', 'u', 'n', 'wp', 'c', 'd', 'v', 'd', 'v', 'n', 'wp', 'p', 'n', 'v', 'wp', 'v', 'i', 'wp', 'b', 'n', 'r', 'd', 'p', 'n', 'k', 'v', 'v', 'wp', 'p', 'v', 'v', 'v', 'n', 'k', 'u', 'n', 'n', 'c', 'n', 'a', 'u', 'n', 'wp', 'r', 'v', 'v', 'r', 'v', 'v', 'nd', 'c', 'v', 'nd', 'u', 'a', 'wp', 'c', 'wp', 'r', 'p', 'n', 'k', 'r', 'v', 'u', 'm', 'q', 'n', 'wp', 'p', 'n', 'nd', 'n', 'k', 'v', 'i', 'wp', 'v', 'n', 'c', 'n', 'nd', 'u', 'n', 'wp', 'r', 'n', 'v', 'v', 'u', 'n', 'd', 'd', 'a', 'wp', 'n', 'd', 'v', 'u', 'r', 'c', 'n', 'k', 'v', 'v', 'u', 'n', 'wp', 'v', 'n', 'wp', 'r', 'm', 'q', 'u', 'n', 'n', 'n', 'd', 'd', 'a', 'wp', 'p', 'n', 'n', 'v', 'v', 'n', 'p', 'n', 'v', 'n', 'v', 'wp', 'v', 'wp', 'v', 'a', 'v', 'wp', 'ns', 'n', 'n', 'nt', 'wp', 'a', 'u', 'n', 'n', 'wp', 'v', 'n', 'v', 'u', 'wp', 'm', 'q', 'n', 'n', 'v', 'wp', 'n', 'k', 'v', 'a', 'wp', 'r', 'n', 'd', 'v', 'p', 'n', 'nd', 'v', 'v', 'r', 'u', 'v', 'wp', 'c', 'wp', 'n', 'd', 'v', 'v', 'v', 'n', 'n', 'u', 'v', 'n', 'wp', 'r', 'n', 'r', 'v', 'n', 'n', 'v', 'n', 'v', 'n', 'n', 'n', 'wp', 'v', 'wp', 'n', 'wp', 'v', 'r', 'wp', 'n', 'u', 'n', 'wp', 'wp', 'r', 'm', 'q', 'u', 'n', 'd', 'v', 'd', 'p', 'n', 'n', 'v', 'v', 'wp', 'nt', 'n', 'nt', 'r', 'v', 'u', 'j', 'wp', 'p', 'n', 'n', 'k', 'nl', 'v', 'u', 'nt', 'n', 'v', 'wp', 'c', 'wp', 'n', 'u', 'v', 'v', 'd', 'v', 'n', 'c', 'n', 'u', 'b', 'v', 'wp', 'v', 'n', 'd', 'v', 'i', 'wp', 'v', 'n', 'n', 'nd', 'wp', 'r', 'v', 'a', 'p', 'm', 'n', 'v', 'n', 'n', 'wp', 'v', 'v', 'n', 'wp', 'p', 'n', 'v', 'a', 'v', 'u', 'v', 'wp', 'v', 'm', 'n', 'u', 'n', 'n', 'v', 'wp', 'd', 'v', 'm', 'v', 'v', 'u', 'n', 'wp', 'r', 'd', 'a', 'v', 'n', 'n', 'wp', 'v', 'a', 'wp', 'm', 'wp', 'v', 'v', 'v', 'v', 'n', 'n', 'wp', 'r', 'p', 'v', 'n', 'u', 'v', 'v', 'nd', 'wp', 'a', 'v', 'b', 'n', 'v', 'n', 'c', 'v', 'n', 'wp', 'v', 'n', 'u', 'a', 'n', 'wp', 'v', 'n', 'u', 'v', 'v', 'wp', 'v', 'p', 'r', 'q', 'n', 'v', 'nd', 'p', 'd', 'v', 'u', 'n', 'd', 'v', 'm', 'q', 'wp', 'c', 'wp', 'd', 'v', 'd', 'a', 'wp', 'v', 'n', 'v', 'v', 'm', 'i', 'u', 'v', 'n', 'wp', 'r', 'v', 'c', 'v', 'd', 'v', 'r', 'a', 'p', 'r', 'n', 'a', 'v', 'c', 'd', 'v', 'n', 'wp', 'v', 'nd', 'm', 'q', 'wp', 'r', 'v', 'r', 'v', 'm', 'q', 'n', 'nd', 'wp', 'c', 'p', 'n', 'nd', 'v', 'p', 'nh', 'n', 'v', 'a', 'v', 'wp', 'p', 'u', 'v', 'v', 'u', 'n', 'v', 'v', 'c', 'v', 'v', 'n', 'wp', 'v', 'u', 'n', 'v', 'v', 'wp', 'nt', 'a', 'v', 'n', 'v', 'wp', 'p', 'v', 'wp', 'v', 'u', 'r', 'p', 'r', 'm', 'n', 'n', 'c', 'n', 'u', 'n', 'wp', 'v', 'u', 'm', 'q', 'n', 'u', 'a', 'u', 'v', 'n', 'wp', 'v', 'u', 'm', 'u', 'n', 'wp', 'v', 'r', 'n', 'd', 'v', 'r', 'a', 'u', 'v', 'n', 'wp', 'v', 'r', 'v', 'u', 'wp', 'v', 'v', 'n', 'wp', 'u', 'b', 'n', 'wp', 'p', 'nd', 'u', 'v', 'v', 'a', 'u', 'v', 'n', 'wp', 'c', 'wp', 'v', 'n', 'nd', 'v', 'd', 'v', 'n', 'v', 'nd', 'u', 'i', 'wp', 'r', 'v', 'v', 'v', 'n', 'wp', 'r', 'v', 'wp', 'v', 'nd', 'v', 'n', 'k', 'v', 'n', 'wp', 'nd', 'v', 'a', 'u', 'n', 'v', 'v', 'v', 'u', 'v', 'wp', 'r', 'n', 'p', 'm', 'n', 'u', 'n', 'd', 'v', 'wp', 'p', 'r', 'd', 'v', 'v', 'u', 'n', 'wp', 'r', 'v', 'p', 'r', 'a', 'n', 'd', 'v', 'r', 'wp', 'a', 'n', 'wp', 'p', 'r', 'wp', 'd', 'r', 'v', 'v', 'v', 'n', 'p', 'r', 'v', 'v', 'v', 'v', 'wp', 'c', 'v', 'r', 'p', 'b', 'n', 'nd', 'v', 'a', 'u', 'v', 'v', 'wp', 'r', 'wp', 'j', 'wp', 'u', 'n', 'v', 'v', 'n', 'd', 'v', 'a', 'c', 'n', 'v', 'v', 'wp', 'm', 'n', 'v', 'wp', 'm', 'n', 'u', 'n', 'd', 'v', 'v', 'wp', 'c', 'wp', 'v', 'n', 'wp', 'v', 'n', 'u', 'n', 'p', 'n', 'v', 'nd', 'd', 'v', 'd', 'a', 'u', 'wp', 'r', 'p', 'v', 'n', 'a', 'u', 'n', 'd', 'v', 'v', 'nd', 'v', 'u', 'n', 'wp', 'c', 'p', 'n', 'nd', 'v', 'v', 'u', 'n', 'wp', 'p', 'r', 'n', 'u', 'n', 'v', 'v', 'c', 'v', 'wp', 'nd', 'wp', 'r', 'n', 'r', 'p', 'n', 'nd', 'v', 'u', 'm', 'q', 'b', 'n', 'wp', 'wp', 'n', 'n', 'wp', 'c', 'wp', 'n', 'n', 'wp', 'wp', 'n', 'n', 'n', 'c', 'n', 'a', 'wp', 'c', 'd', 'v', 'm', 'v', 'v', 'v', 'v', 'u', 'n', 'wp', 'nt', 'r', 'a', 'p', 'v', 'n', 'c', 'r', 'n', 'v', 'a', 'u', 'n', 'wp', 'n', 'k', 'v', 'u', 'a', 'n', 'v', 'r', 'p', 'r', 'v', 'n', 'v', 'n', 'c', 'v', 'n', 'v', 'u', 'd', 'a', 'c', 'a', 'u', 'n', 'v', 'wp', 'r', 'd', 'v', 'a', 'wp', 'v', 'r', 'u', 'v', 'n', 'wp', 'm', 'wp', 'v', 'n', 'v', 'v', 'v', 'n', 'u', 'v', 'v', 'p', 'n', 'v', 'n', 'nd', 'n', 'v', 'v', 'u', 'a', 'n', 'wp', 'v', 'n', 'd', 'v', 'n', 'v', 'u', 'n', 'wp', 'd', 'v', 'n', 'v', 'v', 'v', 'u', 'n', 'nh', 'v', 'u', 'wp', 'wp', 'v', 'v', 'v', 'v', 'u', 'n', 'wp', 'wp', 'm', 'n', 'd', 'v', 'wp', 'v', 'p', 'n', 'u', 'v', 'wp', 'd', 'd', 'v', 'v', 'b', 'u', 'v', 'wp', 'v', 'v', 'v', 'n', 'n', 'wp', 'p', 'wp', 'v', 'n', 'wp', 'n', 'u', 'n', 'wp', 'r', 'v', 'p', 'n', 'v', 'r', 'v', 'v', 'u', 'n', 'wp', 'v', 'm', 'q', 'wp', 'r', 'p', 'v', 'n', 'v', 'u', 'n', 'nd', 'n', 'u', 'n', 'n', 'wp', 'c', 'p', 'a', 'v', 'n', 'v', 'n', 'v', 'v', 'v', 'wp', 'p', 'v', 'wp', 'v', 'wp', 'n', 'k', 'd', 'd', 'v', 'p', 'n', 'nd', 'c', 'p', 'nt', 'p', 'r', 'v', 'n', 'n', 'wp', 'c', 'r', 'd', 'd', 'p', 'wp', 'a', 'n', 'wp', 'u', 'n', 'p', 'r', 'v', 'm', 'r', 'u', 'v', 'wp', 'n', 'wp', 'b', 'nd', 'n', 'nd', 'u', 'n', 'v', 'u', 'a', 'u', 'v', 'wp', 'c', 'wp', 'r', 'd', 'v', 'v', 'v', 'u', 'n', 'n', 'v', 'wp', 'nt', 'v', 'v', 'wp', 'n', 'nd', 'n', 'v', 'v', 'wp', 'p', 'r', 'v', 'wp', 'v', 'n', 'k', 'u', 'b', 'v', 'd', 'a', 'wp', 'v', 'wp', 'p', 'v', 'n', 'wp', 'p', 'v', 'nd', 'v', 'wp', 'wp', 'n', 'z', 'wp', 'p', 'n', 'nd', 'i', 'n', 'd', 'v', 'v', 'n', 'wp', 'r', 'd', 'v', 'v', 'm', 'n', 'p', 'n', 'v', 'n', 'n', 'n', 'wp', 'n', 'n', 'd', 'v', 'wp', 'v', 'wp', 'n', 'v', 'wp', 'wp', 'wp', 'v', 'nl', 'wp', 'wp', 'wp', 'n', 'v', 'r', 'wp', 'wp', 'wp', 'v', 'v', 'n', 'wp', 'wp', 'wp', 'nt', 'a', 'v', 'wp', 'u', 'wp', 'v', 'n', 'p', 'n', 'n', 'nd', 'i', 'wp', 'v', 'v', 'u', 'n', 'wp', 'v', 'u', 'n', 'wp', 'v', 'n', 'p', 'r', 'n', 'u', 'a', 'u', 'wp', 'i', 'wp', 'm', 'q', 'm', 'n', 'u', 'v', 'j', 'v', 'd', 'v', 'wp', 'r', 'm', 'q', 'n', 'wp', 'd', 'v', 'r', 'n', 'nd', 'm', 'q', 'a', 'u', 'n', 'wp', 'd', 'v', 'r', 'i', 'v', 'u', 'a', 'n', 'wp', 'nt', 'wp', 'r', 'd', 'd', 'a', 'u', 'v', 'r', 'wp', 'v', 'n', 'wp', 'a', 'v', 'r', 'a', 'wp', 'd', 'd', 'wp']]

**就会让python停止工作。**
**是不是需要限制长度？哪里有相关的说明？具体限制在多长？**
**感谢！**

**Comment by WEN-MIN** [comment]
我也遇到类似的情况

**Comment by lGRlili** [comment]
我也遇到了类似的情况，请问最后是怎么解决的

**Comment by WEN-MIN** [comment]
> 我也遇到类似的情况

先分句然后再处理就没问题
