### ISSUE TITLE
windows pip install 安装的是pyltp 0.2.1 并不是pyltp 0.2.0

### ISSUE THREAD

**Issue by CholoeMoretz** [HIT-SCIR/pyltp#197]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

导致我下载的3.4.0的model无法正常使用，会弹出错误Process finished with exit code -1073740940 (0xC0000374)

## 运行环境

window 10
python 3.6.7

**Comment by lifuqiang2016** [comment]
解决了吗，我也遇见了

**Comment by gaozhengjie** [comment]
我也遇见了
