### ISSUE TITLE
本地分词（pyltp3.4.0）、webAPI的语义依存图返回结果和webAPI分词结果不一致

### ISSUE THREAD

**Issue by jiangweisuc** [HIT-SCIR/pyltp#201]
## 问题*类型*

最近调用了wbAPI语义依存图的分析结果，返回的结果只有索引，本来想结合本地分词（pyltp3.4分词模块3.4.0版本）输出文字，结果发现，webAPI返回的list大小和本地分词的list大小不一致，也就是说，两个版本分词不一样造成了不一致；然后又测试了webAPI版本的分词，和webAPI版本的语义依存分词也是不一样，造成无法输出文字依存关系。请问它们都是各自什么版本，有什么办法一致吗？非常感谢！

## 出错*场景*

部分不一致的句子如下：

句子3：  全信股份7亿收军工资产
webapi分词    全信  股份  7亿  收  军工  资产
本地分词       全信  股份7亿  收  军工  资产
------------------------------------------------------------
两个分词结果和webapi语义依存返回结果长度不一致

句子4：  世纪游轮逾300亿收购Alpha
webapi分词    世纪  游轮  逾  300亿  收购  Alpha
本地分词       世纪  游  轮  逾  300亿  收购  Alpha
------------------------------------------------------------
两个分词结果和webapi语义依存返回结果长度不一致

。。。。。。

## 运行环境

Ubuntu18
python3.6
pyltp3.4.0
## 期望结果

希望调用WEBAPI返回的索引，结合一个分词结果，可以输出文字依存关系。
谢谢您

**Comment by ReadyThalia** [comment]
遇到同样的问题，web页面上显示的句法分析结果与本地pyltp得到的结果不一致，请问云平台上使用的是哪个版本的API，求助。

**Comment by AlongWY** [comment]
目前已经更换为ltp4 base模型
