### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": 

### ISSUE THREAD

**Issue by duxingmoyu** [HIT-SCIR/pyltp#203]
报错：error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
- [ ] running install
- [ ]running bdist_egg
- [ ]running egg_info
- [ ]creating pyltp.egg-info
- [ ]writing pyltp.egg-info\PKG-INFO
- [ ]writing dependency_links to pyltp.egg-info\dependency_links.txt
- [ ]writing top-level names to pyltp.egg-info\top_level.txt
- [ ]writing manifest file 'pyltp.egg-info\SOURCES.txt'
- [ ]reading manifest file 'pyltp.egg-info\SOURCES.txt'
- [ ]reading manifest template 'MANIFEST.in'
- [ ]warning: no files found matching '*.hpp' under directory 'ltp\src\framework'
- [ ]warning: no files found matching '*.hpp' under directory 'ltp\src\segmentor'
- [ ]warning: no files found matching '*.hpp' under directory 'ltp\src\postagger'
- [ ]warning: no files found matching '*.hpp' under directory 'ltp\src\ner'
- [ ]warning: no files found matching '*.hpp' under directory 'ltp\src\parser.n'
- [ ]writing manifest file 'pyltp.egg-info\SOURCES.txt'
- [ ]installing library code to build\bdist.win32\egg
- [ ]running install_lib
- [ ]running build_ext
- [ ]building 'pyltp' extension
- [ ]error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": - [ ]https://visualstudio.microsoft.com/downloads/

## 代码片段

##安装了python3.7.3，使用git拖源码。python setup.py install的方式进行编译，编译错误。一开始是以为缺少c++编译器，因此安装了很多个版本的VS Studio及SDK，但是问题依然存在。安装步骤：将pyltp源码拖到本地，在路径AppData\Local\Programs\Python\Python37-32\Lib\site-packages\下，通过 git submodule inin/update在里面新建并更新了ltp的所有代码。
在路径AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pyltp下，运行 python setup.py install报错 。

## 期望结果
求更新3.7.3的安装包啊~~~ 

## 其他

个人怀疑，是不是ltp源代码中缺少了#.hpp的文件，我看了那几个报错的文件夹下，都只有.h的文件，是安装的列表没有更新，还是文件错误来着

是否需要将ltp源码先在本地编译了？？？按道理来说不应该啊

运行from pyltp import Segmentor时，
报错：No name 'Segmentor' in module 'pyltp'pylint(no-name-in-module)

**Comment by DraculaXly** [comment]
3.7.3 + VC14
https://github.com/DraculaXly/Python/tree/master/Wheel
我也弄了好久，还是环境的问题，用了没有装过VS的机器下载了那个VS Tool，改了一个51行的错误，然后才编译好的，希望对你有所帮助哈。

**Comment by ConeyYan** [comment]
> 3.7.3 + VC14
> https://github.com/DraculaXly/Python/tree/master/Wheel
> 我也弄了好久，还是环境的问题，用了没有装过VS的机器下载了那个VS Tool，改了一个51行的错误，然后才编译好的，希望对你有所帮助哈。

你的确实可用。点赞！

**Comment by johnny0213** [comment]
> 3.7.3 + VC14
> https://github.com/DraculaXly/Python/tree/master/Wheel
> 我也弄了好久，还是环境的问题，用了没有装过VS的机器下载了那个VS Tool，改了一个51行的错误，然后才编译好的，希望对你有所帮助哈。

很好很强大。谢谢你！

**Comment by kottravey** [comment]
谢谢，我这边安了VC14也无法成功，这个很有帮助
