### ISSUE TITLE
安装过程中出现'SplitSentence.h' file not found

### ISSUE THREAD

**Issue by kelly2016** [HIT-SCIR/pyltp#205]
## 问题*类型*
安装出错

## 出错*场景*
执行以下命令：
MACOSX_DEPLOYMENT_TARGET=10.7 python3 setup.py install

## 代码片段
src/pyltp.cpp:17:10: fatal error: 'SplitSentence.h' file not found
#include "SplitSentence.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
error: command 'clang++' failed with exit status 1

## 如何复现这一错误
macOS ,python3.7

## 运行环境
macOS 10.12.6 (16G2128) ,python3.7

## 期望结果
顺利安装完成

**Comment by Master-He** [comment]
我也遇到了类似的问题
环境：ubuntu:16.04, python3.7  
报错如下：
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/pyltp.cpp:17:27: fatal error: SplitSentence.h: 没有那个文件或目录
compilation terminated.
error: command 'gcc' failed with exit status 1
