### ISSUE TITLE
为什么不支持anaconda?现在支持了吗

### ISSUE THREAD

**Issue by XuZhen001** [HIT-SCIR/pyltp#207]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by liu946** [comment]
conda内置的编译器对C++11的支持不完善，无法编译ltp所需的扩展包。目前已知的解决方法是，在非conda下把pyltp安装好，之后吧pyltp的整个编译后项目移动到conda的包目录中。
