### ISSUE TITLE
python3.8安装pyltp错误

### ISSUE THREAD

**Issue by cllx** [HIT-SCIR/pyltp#209]
## 报如下错误
warning C4267: “初始化”: 从“size_t”转换到“unsigned int”，可能丢失数据
error C3861: “convert”: 找不到标识符
Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
“初始化”: 从“size_t”转换到“unsigned long”，可能丢失数据
  ltp\src\srl\DepSRL.cpp(114): warning C4018: “<”: 有符号/无符号不匹配
  ltp\src\srl\DepSRL.cpp(124): warning C4018: “<”: 有符号/无符号不匹配
  ltp\src\srl\DepSRL.cpp(127): warning C4018: “<”: 有符号/无符号不匹配
请问这种问题要怎么解决啊，弄了两天了都没找到方法

**Comment by DraculaXly** [comment]
不是不支持VS 2019吗，你可能需要用纯净的环境重新试下。
你可以尝试下我之前的方法，当时打包3.7.3成功的。
[(https://github.com/HIT-SCIR/pyltp/issues/206)]

**Comment by wqw547243068** [comment]
python 2.7 安装pyltp出错，linux环境
命令：
```shell
sudo pip install pyltp
```
错误信息：
>  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 246, in _error_catcher
>    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

源不行？

**Comment by liuyunwww** [comment]
源码安装成功，但运行自己的代码出错。
ImportError: can not import name 'Postagger' from 'pyltp' (unknown location)

**Comment by SkipperJK** [comment]
用python3.7版本安装不成功，python3.6安装成功。

**Comment by AlucardNosferatu** [comment]
> 用python3.7版本安装不成功，python3.6安装成功。

现在支持了吗？

**Comment by AlongWY** [comment]
可以自己编译安装
