### ISSUE TITLE
python3.8如何安装pyltp

### ISSUE THREAD

**Issue by cllx** [HIT-SCIR/pyltp#212]
如题，我装了最新版的python3.8，通过pip3 install pyltp安装不上，那么有python3.8对应的版本安装吗

**Comment by lvjingshu** [comment]
same question

**Comment by Minglemax** [comment]
how do that?

**Comment by mzh1996** [comment]
3.7同问

**Comment by carfly** [comment]
LTP更新到4.0版本了，提供了原生 Python 接口，可以试一下。

 

https://github.com/HIT-SCIR/ltp

**Comment by mzh1996** [comment]
> LTP更新到4.0版本了，提供了原生 Python 接口，可以试一下。 https://github.com/HIT-SCIR/ltp From: mzh1996 <notifications@github.com> Reply-To: HIT-SCIR/pyltp <reply@reply.github.com> Date: Monday, June 22, 2020 at 4:23 PM To: HIT-SCIR/pyltp <pyltp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [HIT-SCIR/pyltp] python3.8如何安装pyltp (#212) 3.7同问 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢 我去试试
