### ISSUE TITLE
运行example.py时，显示Segmentor: Model not loaded!

### ISSUE THREAD

**Issue by MrSleeping** [HIT-SCIR/pyltp#22]
加载cws.model好像没成功

**Comment by hermancn** [comment]
一般情况是模型加载路径有问题。

**Comment by MrSleeping** [comment]
模型加载路径应该是正确的，我是在windows下安装的

**Comment by endyul** [comment]
是否使用了repo下的`ltp_data`目录下的模型？
如果是的话，请不要使用这个。请下载`README`中百度云上的模型

**Comment by MrSleeping** [comment]
就是用的ltp_data，重新装了一遍还是报这个错误

**Comment by MrSleeping** [comment]
用的是百度云上的ltp模型，重装了下还是报这个错误

**Comment by endyul** [comment]
是用的3.3.0release吗？master上现在是3.3.1的开发版

发送自 Outlook Mobile




On Wed, Dec 23, 2015 at 6:03 AM -0800, "MrSleeping" <notifications@github.com> wrote:












用的是百度云上的ltp模型，重装了下还是报这个错误

**Comment by MrSleeping** [comment]
好吧，谢谢了！

**Comment by MrSleeping** [comment]
谢谢了，现在已经解决了。

**Comment by ElijahLai** [comment]
MrSleeping, 请问你是怎么解决这个问题的

**Comment by YoonaX** [comment]
要加转义符\\ 
我的路径是  D:\\\\Python\\\\3.4\\\\cws.model
