### ISSUE TITLE
Mac 10.15 安装 pyltp 出错- error: lipo command failed with exit code 1 

### ISSUE THREAD

**Issue by jiaziberry** [HIT-SCIR/pyltp#221]
## 问题*类型* ：< 构建失败>

执行setup.py文件 
$ cd pyltp
$ python setup.py install

## 出错*场景*

clang: error: lipo command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1**

## 代码片段

running install
running bdist_egg
running egg_info
writing pyltp.egg-info/PKG-INFO
writing dependency_links to pyltp.egg-info/dependency_links.txt
writing top-level names to pyltp.egg-info/top_level.txt
reading manifest file 'pyltp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.hpp' under directory 'ltp/src/framework'
warning: no files found matching '*.hpp' under directory 'ltp/src/segmentor'
warning: no files found matching '*.hpp' under directory 'ltp/src/postagger'
warning: no files found matching '*.hpp' under directory 'ltp/src/ner'
warning: no files found matching '*.hpp' under directory 'ltp/src/parser.n'
writing manifest file 'pyltp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_ext
building 'pyltp' extension
clang++ -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/pyltp.cpp -o build/temp.macosx-10.6-intel-3.6/src/pyltp.o -std=c++11 -Wno-c++11-narrowing -Wno-unused-local-typedef -Wno-unused-variable -Wno-reorder -Wno-sign-compare -stdlib=libc++
In file included from src/pyltp.cpp:15:
In file included from patch/include/boost/python.hpp:11:
In file included from patch/include/boost/python/args.hpp:25:
In file included from patch/include/boost/python/object_core.hpp:14:
In file included from patch/include/boost/python/call.hpp:15:
In file included from patch/include/boost/python/converter/arg_to_python.hpp:19:
In file included from patch/include/boost/python/object/function_handle.hpp:10:
patch/include/boost/python/object/py_function.hpp:167:18: warning: 
      'auto_ptr<boost::python::objects::py_function_impl_base>' is deprecated
      [-Wdeprecated-declarations]
    mutable std::auto_ptr<py_function_impl_base> m_impl;
                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2079:28: note: 
      'auto_ptr<boost::python::objects::py_function_impl_base>' has been
      explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 auto_ptr
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1054:39: note: 
      expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1043:48: note: 
      expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 warning generated.
In file included from src/pyltp.cpp:15:
In file included from patch/include/boost/python.hpp:11:
In file included from patch/include/boost/python/args.hpp:25:
In file included from patch/include/boost/python/object_core.hpp:14:
In file included from patch/include/boost/python/call.hpp:15:
In file included from patch/include/boost/python/converter/arg_to_python.hpp:19:
In file included from patch/include/boost/python/object/function_handle.hpp:10:
patch/include/boost/python/object/py_function.hpp:167:18: warning: 
      'auto_ptr<boost::python::objects::py_function_impl_base>' is deprecated
      [-Wdeprecated-declarations]
    mutable std::auto_ptr<py_function_impl_base> m_impl;
                 ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2079:28: note: 
      'auto_ptr<boost::python::objects::py_function_impl_base>' has been
      explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 auto_ptr
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1054:39: note: 
      expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1043:48: note: 
      expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 warning generated.
clang++ -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c ltp/thirdparty/boost/libs/regex/src/icu.cpp -o build/temp.macosx-10.6-intel-3.6/ltp/thirdparty/boost/libs/regex/src/icu.o -std=c++11 -Wno-c++11-narrowing -Wno-unused-local-typedef -Wno-unused-variable -Wno-reorder -Wno-sign-compare -stdlib=libc++

fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: can't create temporary output file: build/temp.macosx-10.6-intel-3.6/ltp/thirdparty/boost/libs/regex/src/icu.o.lipo (Permission denied)

**clang: error: lipo command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1**

## 运行环境

我用的是 MacOS Catalina 10.15.13
Python 用的是 3.6.8版

## 期望结果

成功安装 PYLTP

**Comment by xyjsjruiliu** [comment]
你可以参考这个链接下的说明，应该可以完成编译
https://blog.csdn.net/weixin_42274377/article/details/88725558
