### ISSUE TITLE
import pyltp error: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by wjx-git** [HIT-SCIR/pyltp#223]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

导入错误
## 出错*场景*

pip install pyltp成功，但是import pyltp出错。
pyltp==0.2.1
ImportError: /home/xxx/anaconda3/lib/python3.6/site-packages/pyltp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev
## 运行环境

ubuntu 20.4
python3.6
Anaconda 5.2.0
Pycharm 2020.1.3
gcc 9.3.0
## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by AlongWY** [comment]
请问你是自己编译安装的还是 pip 安装的

**Comment by wjx-git** [comment]
> 请问你是自己编译安装的还是 pip 安装的

pip安装的

**Comment by wjx-git** [comment]
安装pyltp==0.3.0就解决了。
目前 pip 只能安装 0.2.1 版本的，
0.3.0版本到按照 git 上源码编译方法安装。
