### ISSUE TITLE
debug时，导入pyltp出现错误

### ISSUE THREAD

**Issue by wjx-git** [HIT-SCIR/pyltp#224]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

报错如下：
ImportError: /home/wjx/anaconda3/lib/python3.6/site-packages/PyQt5/../../../libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/wjx/anaconda3/lib/python3.6/site-packages/pyltp-0.3.0-py3.6-linux-x86_64.egg/pyltp.cpython-36m-x86_64-linux-gnu.so)

找不到libstdc++.so.6文件，路径不完整，咋办。
## 出错*场景*
from pyltp import Segmentor, Postagger, Parser, NamedEntityRecognizer

代码run时不会报错，debug时出现error

## 运行环境

ubuntu 20.4
anaconda 5.2.0
python3.6
gcc 9.0
pyltp 0.3.0
## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by AlongWY** [comment]
一些资料显示该问题是某些版本的gcc导致的，是否可以尝试下其他版本的编译器

**Comment by AlongWY** [comment]
ubuntu 18.04
gcc 4.8.5
编译通过
