### ISSUE TITLE
分词加载自己字典，用load_with_lexicon，导入出错，有三个参数，第一个是模型路径，第二个是字典路径，第三个呢？只传两个会报错

### ISSUE THREAD

**Issue by MAJIN123** [HIT-SCIR/pyltp#226]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by AlongWY** [comment]
已经对代码进行了修改，同时在example中也进行了说明
