### ISSUE TITLE
只安装pyltp是否可以独立运行？

### ISSUE THREAD

**Issue by hiber-niu** [HIT-SCIR/pyltp#23]
windows 7下只用pip成功安装了pyltp，在注释掉加载lib文件的那行代码后，成功运行example.py。我想问的是，仅仅安装pyltp情况下，是否可以正确执行ltp的所有功能？

**Comment by endyul** [comment]
可以，记得下载百度云上的模型文件

pyltp只是封装了ltp，实际上pip安装过程中会自动下载编译ltp的。
ltp的训练部分功能pyltp暂未提供



On Wed, Dec 16, 2015 at 6:36 PM -0800, "hermancn" <notifications@github.com> wrote:












windows 7下只用pip成功安装了pyltp，在注释掉加载lib文件的那行代码后，成功运行examplepy。我想问的是，仅仅安装pyltp情况下，是否可以正确执行ltp的所有功能？

**Comment by hermancn** [comment]
感谢这么快的回复，那ltp的训练功能有准备加入的时间点吗？

**Comment by endyul** [comment]
暂时没有，那个不适合作为编程接口。如要使用还是得编一下ltp。
打算ltp下个版本开始提供win的二进制程序下载

发送自 Outlook Mobile




On Wed, Dec 16, 2015 at 7:13 PM -0800, "hermancn" <notifications@github.com> wrote:












感谢这么快的回复，那ltp的训练功能有准备加入的时间点吗？

**Comment by hermancn** [comment]
那很棒，不过其实现在python用的人这么多，估计很多人都希望出个完整的python版本的。有没有重写一下，ltp出个python版本的计划？
