### ISSUE TITLE
分词结果错误

### ISSUE THREAD

**Issue by yasewang987** [HIT-SCIR/pyltp#237]
## 问题*类型*
分词结果错误

## 出错*场景*
分析句子：以她为名，延安精神成为中国共党的宝贵精神财富。

## 运行环境
cpu：鲲鹏920
系统：统信UOS Server 20 1040d 20210719
python版本：python3.6
pyltp版本：0.4.0

## 错误分词
![image](https://user-images.githubusercontent.com/22265036/133366464-af33268a-facb-4ac4-be1e-5f1d3163903b.png)

## 期望结果
![image](https://user-images.githubusercontent.com/22265036/133366494-dac3cd4d-1641-409e-ab2a-2c1dc0ec2c42.png)

**Comment by AlongWY** [comment]
应该是载入模型的时候出现了大小端不匹配的问题

**Comment by mqy9787** [comment]
> 应该是载入模型的时候出现了大小端不匹配的问题

请问这个该如何解决呢，目前国产化arrch架构的cpu 飞腾 鲲鹏都有这个问题，而x86架构的海光可以正常显示分词结果。

**Comment by AlongWY** [comment]
可以尝试一下 ltp 4.2 的 legacy 模型？如果无法载入的话，可以在x86平台将模型保存为json格式，然后再在arm平台进行载入
