### ISSUE TITLE
macos build failed

### ISSUE THREAD

**Issue by songsh** [HIT-SCIR/pyltp#238]
在提问之前，请确认以下几点:
- [ ] 如果您对算法或C++实现有问题，请在https://github.com/HIT-SCIR/ltp/issues提问
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*
构建失败

## 出错*场景*
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/dony/pyltp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dony/pyltp/build/lib.macosx-10.13-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/local/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
## 如何复现这一错误

	$ git clone https://github.com/HIT-SCIR/pyltp
	$ cd pyltp
	$ git submodule init
	$ git submodule update
	$ python setup.py install

## 运行环境

macos python3.7
## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] If there is an algorithm or native (c++) problem. Go to https://github.com/HIT-SCIR/ltp/issues
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by AlongWY** [comment]
好的我检查一下

**Comment by AlongWY** [comment]
已经解决该问题
