### ISSUE TITLE
could not process directory files

### ISSUE THREAD

**Issue by hittle2015** [HIT-SCIR/pyltp#24]
Dear All,

Thanks for your work. I recently tried to use pyltp  to process some new data and found it no longer working. It looks like the program stops at the iteration over the second file in the directory. I used to have more than two thousand files processed with pyltp  a few months ago. 
I have tried to used file pointer as well, still got nothing but the first file result. Could you guys have a look at my shabby python code? 
Best regards,
Y.
	        
[srllabeller4.txt](https://github.com/HIT-SCIR/pyltp/files/139643/srllabeller4.txt)

*******************************************************************************************************************************

**Comment by endyul** [comment]
could you please reformat your code

**Comment by hittle2015** [comment]
sorry, just update it as a separate attachment.

**Comment by hittle2015** [comment]
I just found out it was due to the first line of the second file is blank. Just adding one line of code to check empty string will be fine.
