### ISSUE TITLE
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:     1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)

### ISSUE THREAD

**Issue by SuxinTong** [HIT-SCIR/pyltp#243]
class LtpParser:
    def __init__(self):
        LTP_DIR = "./ltp_data"
        self.segmentor = Segmentor()
        self.segmentor.load(os.path.join(LTP_DIR, "cws.model"))

        self.postagger = Postagger()
        self.postagger.load(os.path.join(LTP_DIR, "pos.model"))

        self.parser = Parser()
        self.parser.load(os.path.join(LTP_DIR, "parser.model"))

        self.recognizer = NamedEntityRecognizer()
        self.recognizer.load(os.path.join(LTP_DIR, "ner.model"))

        self.labeller = SementicRoleLabeller()
        self.labeller.load(os.path.join(LTP_DIR, 'pisrl.model'))
---------------------------------------------------------------------------
......
~\paper\EventTriplesExtraction-master\sentence_parser.py in __init__(self)
     10     def __init__(self):
     11         LTP_DIR = "./ltp_data"
---> 12         self.segmentor = Segmentor()
     13         self.segmentor.load(os.path.join(LTP_DIR, "cws.model"))
     14 

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyltp.Segmentor(model_path: str, lexicon_path: str = None, force_lexicon_path: str = None)

Invoked with:

**Comment by AlongWY** [comment]
可以看一下这个样例 [Example](https://github.com/HIT-SCIR/pyltp/blob/master/example/example.py)
