### ISSUE TITLE
分词输出结果是空的

### ISSUE THREAD

**Issue by jingjinjingjin** [HIT-SCIR/pyltp#26]
`>>> from pyltp import Segmentor`
`>>> segmentor = Segmentor()`
`>>> segmentor.load("d:/data/ltp/cws.model")`
`>>> words = segmentor.segment("元芳你怎么看")`
`>>> print "|".join(words)`

`>>>`
我的环境是win7 64位。 Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32

**Comment by endyul** [comment]
你好，输入的句子需要是utf-8编码

**Comment by jingjinjingjin** [comment]
谢谢这么快就回复我
`Traceback (most recent call last):·
  File "<pyshell#6>", line 1, in <module>
    words = segmentor.segment(u"元芳你怎么看")
ArgumentError: Python argument types in
    Segmentor.segment(Segmentor, unicode)
did not match C++ signature:
    segment(struct Segmentor {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)`

**Comment by endyul** [comment]
`u"元芳你怎么看"`是unicode，你需要写成`u"元芳你怎么看".encode('utf-8')`

**Comment by jingjinjingjin** [comment]
多谢endyul。解决问题了。
技术太菜了，不好意思哈
