### ISSUE TITLE
python3安装pyltp出错,求教

### ISSUE THREAD

**Issue by hxcomet** [HIT-SCIR/pyltp#3]
环境: ubuntu 14.04 x64, 下载
系统默认python 为 python2.7
cmake 也用apt安装了
1. 安装 python3, python3-dev, 并修改了默认的python: 在 /usr/bin 下将python3 复制改名为 python, python3-config复制改名为 python-config
   1.测试了以下命令, 都和所说明的一致
   python --version
   Python 3.4.0

python-config --includes
-I/usr/include/python3.4m -I/usr/include/python3.4m

2.运行cmake -DLTP_HOME=/home/he/ltp-3.1.2 出错, 信息如下

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindPythonLibs.cmake:208 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  boost_python/CMakeLists.txt:1 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Call Stack (most recent call first)

请问该如何解决,谢谢

**Comment by luciferz2012** [comment]
反馈一下，在windows 10 + Python 3.5 x64上用pip安装没有问题。

谢谢你们的工作！
