### ISSUE TITLE
提供分句接口

### ISSUE THREAD

**Issue by endyul** [HIT-SCIR/pyltp#33]

**Comment by Amyinclude** [comment]
请问现在有分句接口吗？

**Comment by endyul** [comment]
有的，请参考文档

**Comment by Amyinclude** [comment]
感谢您的回复，关于分句问题，还有一个问题需要请教：
官方文档中，只有如下例子
        from pyltp import SentenceSplitter
        sents = SentenceSplitter.split('元芳你怎么看？我就趴窗口上看呗！')  # 分句
        print '\n'.join(sents)
我也试了一下别的句子，推测这个函数是通过感叹号和句号切分句子的，请问pyltp是否能通过其他函数或者设置，实现使用其他符号切分句子呢？

**Comment by endyul** [comment]
确实是通过标点符号切分。暂未提供设置自定义符号的功能

**Comment by Amyinclude** [comment]
明白了，谢谢你的回复~
