### ISSUE TITLE
pip install pyltp fail.

### ISSUE THREAD

**Issue by h404bi** [HIT-SCIR/pyltp#35]
Anaconda virtualenv, Python 2.7.11

```
(venv) $ pip install pyltp
Collecting pyltp
  Downloading pyltp-0.1.8.tar.gz (3.4MB)
Installing collected packages: pyltp
  Running setup.py install for pyltp: started
    Running setup.py install for pyltp: finished with status 'error'
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build/temp.macosx-10.5-x86_64-2.7
    creating build/temp.macosx-10.5-x86_64-2.7/src
    creating build/temp.macosx-10.5-x86_64-2.7/ltp
    creating build/temp.macosx-10.5-x86_64-2.7/ltp/thirdparty
    creating build/temp.macosx-10.5-x86_64-2.7/ltp/thirdparty/boost
    
    ... ...
    
    ltp/src/ner/decoder.cpp:27:7: error: use of undeclared identifier 'rep'
          rep.insert(from * T + to);
          ^
    ltp/src/ner/decoder.cpp:38:10: error: use of undeclared identifier 'rep'
      return rep.find(code) != rep.end();
             ^
    ltp/src/ner/decoder.cpp:38:28: error: use of undeclared identifier 'rep'
      return rep.find(code) != rep.end();
                               ^
    In file included from ltp/src/ner/decoder.cpp:1:
    In file included from ltp/src/ner/decoder.h:7:
    ltp/src/utils/smartmap.hpp:72:5: warning: field '_cap_entries' will be initialized after field '_num_buckets' [-Wreorder]
        _cap_entries(INIT_CAP_ENTRIES),
        ^
    ltp/src/utils/smartmap.hpp:589:3: note: in instantiation of member function 'ltp::utility::SmartMap<int, ltp::utility::__Default_CharArray_HashFunction, ltp::utility::__Default_CharArray_EqualFunction>::SmartMap' requested here
      IndexableSmartMap() : entries(0), cap_entries(0) {}
      ^
    ltp/src/utils/smartmap.hpp:75:5: warning: field '_len_key_buffer' will be initialized after field '_hash_buckets' [-Wreorder]
        _len_key_buffer(0),
        ^
    ltp/src/utils/smartmap.hpp:79:5: warning: field '_val_buffer' will be initialized after field '_hash_buckets_volumn' [-Wreorder]
        _val_buffer(0),
        ^
    In file included from ltp/src/ner/decoder.cpp:1:
    In file included from ltp/src/ner/decoder.h:6:
    In file included from ltp/src/framework/decoder.h:5:
    ltp/src/utils/math/sparsevec.h:154:10: warning: private field 'norm' is not used [-Wunused-private-field]
      double norm;
             ^
    12 warnings and 8 errors generated.
    error: command 'gcc' failed with exit status 1
```

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by Oneplus** [comment]
cc换clang试试呢？

**Comment by endyul** [comment]
#17 里修复了
pypi上的源码没有更新；可以下载master上的源码然后`python setup.py install`

**Comment by Oneplus** [comment]
@endyul 打算什么时候release 3.3.2 + pyltp 0.19

**Comment by endyul** [comment]
@Oneplus 这周末前我把文档补全就发...

**Comment by h404bi** [comment]
@endyul 感谢！可用了。另外请问在 Windows 下有没有较为简易的 pyltp 安装方法？

**Comment by endyul** [comment]
@h404bi Windows 下也可以使用 pip 安装

**Comment by h404bi** [comment]
@endyul 嗯，我知道这个。因为需要进行编译，但我机器上尚无安装 visual studio，visual studio又很庞大，而且我没有在 Windows 下编译 python package 的经验，后面可能还需要打包 exe，所以问有没有简易的方法，现成可用安装包或者其它编译手段什么的。不过看似只有编译了，我先试试吧。Thanks.

**Comment by endyul** [comment]
@h404bi 不需要安装 VS，只需安装 [Microsoft Visual C++ Compiler for Python 2.7]
(https://www.microsoft.com/en-us/download/details.aspx?id=44266)

另外 PyPI 上也可以下载到我们编译好的 pyltp 的[安装包](https://pypi.python.org/pypi/pyltp/0.1.8)，目前只提供了 Python 2.7 的 64 位

**Comment by zhouhbs** [comment]
running install
running bdist_egg
running egg_info
writing top-level names to pyltp.egg-info/top_level.txt
writing pyltp.egg-info/PKG-INFO
writing dependency_links to pyltp.egg-info/dependency_links.txt
reading manifest file 'pyltp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.hpp' under directory 'ltp/src/framework'
warning: no files found matching '*.hpp' under directory 'ltp/src/segmentor'
warning: no files found matching '*.hpp' under directory 'ltp/src/postagger'
warning: no files found matching '*.hpp' under directory 'ltp/src/ner'
warning: no files found matching '*.hpp' under directory 'ltp/src/parser.n'
warning: no files found matching '*.hpp' under directory 'ltp/src/srl'
writing manifest file 'pyltp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_ext
building 'pyltp' extension
creating build/temp.macosx-10.6-x86_64-3.5
creating build/temp.macosx-10.6-x86_64-3.5/src
creating build/temp.macosx-10.6-x86_64-3.5/ltp
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty/boost
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty/boost/libs
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty/boost/libs/regex
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty/boost/libs/regex/src
creating build/temp.macosx-10.6-x86_64-3.5/ltp/thirdparty/maxent
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/splitsnt
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/segmentor
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/postagger
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/ner
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/parser.n
creating build/temp.macosx-10.6-x86_64-3.5/ltp/src/srl
creating build/temp.macosx-10.6-x86_64-3.5/patch
creating build/temp.macosx-10.6-x86_64-3.5/patch/libs
creating build/temp.macosx-10.6-x86_64-3.5/patch/libs/python
creating build/temp.macosx-10.6-x86_64-3.5/patch/libs/python/src
creating build/temp.macosx-10.6-x86_64-3.5/patch/libs/python/src/object
creating build/temp.macosx-10.6-x86_64-3.5/patch/libs/python/src/converter
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/user/anaconda/include -arch x86_64 -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ -I/Users/user/anaconda/include/python3.5m -c src/pyltp.cpp -o build/temp.macosx-10.6-x86_64-3.5/src/pyltp.o -std=c++11 -Wno-c++11-narrowing -stdlib=libc++
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'clang++' failed with exit status 1

**Comment by IUYshengqian** [comment]
我也碰到这种windows上pip安装pyltp报错要我安装visual studio,但是我装了vs以后还是报错,有没有哪位大佬知道要怎么配置下吗

**Comment by h404bi** [comment]
@IUYshengqian 按我此前的编译经验，不需要 VS 也行，你要安装 https://github.com/HIT-SCIR/pyltp/issues/35#issuecomment-211045017 其中说的 Microsoft Visual C++ Compiler for Python 2.7 以及 Python 2.7。不过我当时编译的是对于现在来说很老的 0.1.9 版本。最新的得看[最新的依赖情况](https://github.com/HIT-SCIR/pyltp#%E4%BE%9D%E8%B5%96%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5)。
