### ISSUE TITLE
Fail to load cws.model

### ISSUE THREAD

**Issue by lingng** [HIT-SCIR/pyltp#36]
按照如下命令安装 pyltp 之后：
> $ git clone https://github.com/HIT-SCIR/pyltp
> $ git submodule init
> $ git submodule update
> $ python setup.py install

不论是否对 ltp_data 进行替换，我这一直显示如下信息并造成Python崩溃：

$ python example.py
Segmentor: Model not loaded!

����P��S�
Python(10114,0x7fff7f118000) malloc: *** error for object 0x10c721bd8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

将 postagger、parser、recognizer 及 labeller 注释之后 Python **不再崩溃**，但是仍旧显示 “**Segmentor: Model not loaded!**”

Python process 及机器信息如下：

_Process:               Python [10123]_
_Path:                  /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python_
_Identifier:            Python_
_Version:               2.7.11 (2.7.11)_
_Code Type:             X86-64 (Native)_
_Parent Process:        bash [9210]_
_Responsible:           iTerm [7398]_

_Model: MacBookPro12,1, BootROM MBP121.0167.B16, 2 processors, Intel Core i7, 3.1 GHz, 16 GB, SMC 2.28f7_
_Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In_
_Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445424533303445422D45474346202020_
_Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80CE, __0x4B3445424533303445422D45474346202020_
_Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1_

**Comment by endyul** [comment]
错误原因是模型没有被正确加载，请确认

- 从百度云上下载了正确版本的模型 - pyltp 0.1.8 对应的模型版本是 3.3.0
- `segmentor.load` 的参数正确指向了 `cws.model` 的**绝对路径**

**Comment by lingng** [comment]
Problem solved. Thanks a lot!
