### ISSUE TITLE
python2.7版本输出出现乱码

### ISSUE THREAD

**Issue by leefionglee** [HIT-SCIR/pyltp#37]
下面是示例：

`sentence = "中国进出口银行与中国银行加强合作"
segmentor = Segmentor()
segmentor.load(os.path.join(MODELDIR, "cws.model"))
words = segmentor.segment(sentence)
print "\t".join(words)
`

输出的内容是： 涓浗	杩涘嚭鍙�	閾惰	涓�	涓浗閾惰	鍔犲己	鍚堜綔

如果我用：
sentence = u"中国进出口银行与中国银行加强合作"

程序又会报错。

请问2.7应该如果使用？ 感谢！

**Comment by endyul** [comment]
windows 的 terminal 无法正确显示 utf-8 编码
请将输出重定向到文件
