### ISSUE TITLE
句法分析结果怎么看？

### ISSUE THREAD

**Issue by leefionglee** [HIT-SCIR/pyltp#38]
用例子获得了下面的结果， 但是第三行的句法分析的结果怎么看，有人可以每个给解释一下吗？
例如：
中国，3：ATT， 是说 ‘中国’ 和 ‘与’这两个词是ATT关系吗，ATT是定中的意思？ 中国 <-与？
与， 5：LAD， 是说 '与' 和 ‘加强’ 这两个词是LAD关系吗，LAD就是左附加关系， 与<-加强？   

我的理解对吗？ 但是感觉结果好像不太对啊， ‘与’不是应该和'中国银行'是左附加关系么？

中国	进出口	银行	与	中国银行	加强	合作
ns	v	n	c	ni	v	v
3:ATT	3:ATT	6:SBV	5:LAD	3:COO	0:HED	6:VOB

**Comment by endyul** [comment]
句子索引从 1 开始
索引 0 是 `HEAD`

**Comment by leefionglee** [comment]
明白了，谢谢@endyul， 咱这个有啥文档查阅吗？ 要不遇到这些基本问题总是提问怕浪费你们的时间。

**Comment by endyul** [comment]
@leefionglee 可以先参考这个 http://pyltp.readthedocs.io/zh_CN/feature-doc-27/api.html
还在完善
