### ISSUE TITLE
句法分析结果路径查看

### ISSUE THREAD

**Issue by leefionglee** [HIT-SCIR/pyltp#41]
![example](https://cloud.githubusercontent.com/assets/12542056/15137731/1e07ac58-16be-11e6-972d-134f6e52497c.jpg)

有人知道，根据上面的结果， 如何找到手机对应的词--->有瑕疵吗？  应该从哪几个路劲入手？

非常感谢！

**Comment by carfly** [comment]
没理解你的问题……

**Comment by leefionglee** [comment]
@carfly  第一个图是python生成的结果，但是和官网的demo的结果不一样，试了好几个例子，都会有差别。 请问哪个版本会和官网的demo结果一样，试了几个，感觉官网的更准确一点。

**Comment by lxj0276** [comment]
@leefionglee 这个有问题的
