### ISSUE TITLE
按照文档方法安装在使用的时候出现问题

### ISSUE THREAD

**Issue by lxj0276** [HIT-SCIR/pyltp#44]
错误信息：Boost.Python.ArgumentError: Python argument types in
    Segmentor.segment(Segmentor, unicode)
did not match C++ signature:
    segment(struct Segmentor {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)
方便说一下怎么回事吗

**Comment by Oneplus** [comment]
请提供系统情况，python版本，c++情况。

**Comment by lxj0276** [comment]
系统win7 64bit 
上述错误是python2.7.11,vs2010出现的
我用 anaconda 的时候直接pip install pyltp出现
    C:\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ -Ic:\anaconda2\include -Ic:\anaconda2\PC -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
    gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
    gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
    gcc.exe: error: /EHsc: No such file or directory
    error: command 'C:\\Anaconda2\\Scripts\\gcc.bat' failed with exit status 1
不知道怎么回事

**Comment by Oneplus** [comment]
可能是因为用anaconda，能不能试试msvc提供的python extension在普通cmd环境下编译？

**Comment by Oneplus** [comment]
或者把setup.py里面/EHsc删掉

**Comment by lxj0276** [comment]
已经安装成功了~\(^o^)/

**Comment by lxj0276** [comment]
我分词可以的，但是分句的时候出现问题
Boost.Python.ArgumentError: Python argument types in
SentenceSplitter.split(unicode)
did not match C++ signature:
split(class std::basic_string,class std::allocator >)

**Comment by endyul** [comment]
@lxj0276 参数需要为utf-8编码

**Comment by endyul** [comment]
传入的字符串需要是utf-8编码

**Comment by dapeng2018** [comment]
@lxj0276  我也遇到同样的问题, 怎么安装成功的, 谢谢

**Comment by dapeng2018** [comment]
@lxj0276 @Oneplus 我也遇到同样的问题, 怎么安装成功的, 谢谢

**Comment by lxj0276** [comment]
@dapeng2018 我用原生的python安装的，anaconda安装不行

**Comment by Oneplus** [comment]
@dapeng2018 现在不能用conda安装 https://github.com/HIT-SCIR/pyltp/issues/60，请使用原生Python安装。conda的问题比较诡异，暂时还没有好的解决方法。

**Comment by GabrielLin** [comment]
请问什么时候可以解决，很想用，我就是anaconda用户，整个Python环境都是，其他很多东西都要用anaconda啊。

**Comment by lxj0276** [comment]
anaconda无法顺利安装，望知悉

**Comment by GabrielLin** [comment]
@lxj0276  谢谢分享经验，我希望官方可以给出解决方案。

**Comment by GabrielLin** [comment]
我又试了一下，在CentOS 7下的Anaconda2直接pip是可以安装的。我的Windows是64bit的10，装了VS2015 Update3.

**Comment by zhililab** [comment]
原来是 ananconda 的问题，昨天试了半天都不行 T_T，anaconda下已经尝试的方法（失败）：

1. pip

```bash
conda install pip 
pip install pyltp
```

2. github源码安装

```git
git clone https://github.com/HIT-SCIR/pyltp
git submodule init
git submodule update
python setup.py install 
```

谢谢经验分享 @lxj0276 ， 我试下python原生安装 ；）

**Comment by liu946** [comment]
支持列表已经放在repo主页了。大家源码安装时注意一下。

**Comment by realVegetable** [comment]
@liu946 请求官方能够封装一些wheel包，win32的（网上有win64的3.6和3.5的wheel，但是没有win32的）
