### ISSUE TITLE
加载本地词典出现问题

### ISSUE THREAD

**Issue by lxj0276** [HIT-SCIR/pyltp#46]
segmentor = Segmentor()
segmentor.load_with_lexicon('E:/code/LTP/ltp_data/cws.model','E:/code/python_code/extractEventsTestApi/searchTrigger/dict/mydict.txt')，mydict.txt是u8编码，格式如下
恒生
农银信用债
等等
出现Segmentor: Model not loaded!， 是怎么回事
我不清楚是不是我的用法有问题啊

**Comment by endyul** [comment]
请确认pyltp版本和模型版本是否对应

Regards --
On 周四, 5月 26, 2016 at 09:38, lxj0276 <notifications@github.com> wrote:
segmentor = Segmentor()
segmentor.load_with_lexicon('E:/code/LTP/ltp_data/cws.model','E:/code/python_code/extractEventsTestApi/searchTrigger/dict/mydict.txt')，mydict.txt是u8编码，格式如下
恒生
农银信用债
等等
出现Segmentor: Model not loaded!， 是怎么回事
我不清楚是不是我的用法有问题啊

**Comment by lxj0276** [comment]
我用的pyltp是0.1.9.1版本，直接用pip install pyltp安装的，模型是3.3.1版本

**Comment by endyul** [comment]
@lxj0276 如果不带自定义词典是否有问题？

**Comment by lxj0276** [comment]
如果不用自定义词典没有问题，加上就会报错。我不清楚是不是我用的方法是否正确

**Comment by endyul** [comment]
@lxj0276 lexicon需要是UTF-8 without BOM编码，请再确认一下

**Comment by lxj0276** [comment]
确认的，就是UTF-8 without BOM编码的

**Comment by endyul** [comment]
暂时无法重现
