### ISSUE TITLE
python 调用模型失败。

### ISSUE THREAD

**Issue by leefionglee** [HIT-SCIR/pyltp#47]
环境： windows10, python2.7

`segmentor = Segmentor()
segmentor.load('E:/LTP/3.3.0/ltp_data/cws.model')

postagger = Postagger()
postagger.load('E:/LTP/3.3.0/ltp_data/pos.model')

parser = Parser()
parser.load('E:/LTP/3.3.0/ltp_data/parser.model')`

我在用上面代码调用的时候，程序出现这个错误： 
**Process finished with exit code -1073741819 (0xC0000005)**

查了一遍，实在不知道错误出现在哪里。 使用anaconda安装的，之前用的版本0.1.8是没问题的，这两天换了新的机子， 用pip install安装，刚刚看了一下，安装的版本是： Anaconda2\Lib\site-packages\pyltp-0.1.9.1.dist-info。

请问是什么原因呢？  谢谢！！

**Comment by endyul** [comment]
0.1.9需要下载3.3.1的模型，见文档

Regards --
On 周四, 5月 26, 2016 at 14:41, leefionglee <notifications@github.com> wrote:
环境： windows10, python2.7

`segmentor = Segmentor()
segmentor.load('E:/LTP/3.3.0/ltp_data/cws.model')

postagger = Postagger()
postagger.load('E:/LTP/3.3.0/ltp_data/pos.model')

parser = Parser()
parser.load('E:/LTP/3.3.0/ltp_data/parser.model')`

我在用上面代码调用的时候，程序出现这个错误：
Process finished with exit code -1073741819 (0xC0000005)

查了一遍，实在不知道错误出现在哪里。 使用anaconda安装的，之前用的版本0.1.8是没问题的，这两天换了新的机子， 用pip install安装，刚刚看了一下，安装的版本是： Anaconda2\Lib\site-packages\pyltp-0.1.9.1.dist-info。

请问是什么原因呢？ 谢谢！！

**Comment by leefionglee** [comment]
已经解决。谢谢。

**Comment by xiaoxiaoyuan8github** [comment]
貌似也遇到类似问题，请问你是如何解决的？

**Comment by chaoyue729** [comment]
> 已经解决。谢谢。

请问如何解决模型引入异常退出问题
