### ISSUE TITLE
关于分词问题

### ISSUE THREAD

**Issue by lxj0276** [HIT-SCIR/pyltp#48]
比如：阿里联手工商破获重庆亿元刷单案，分词结果是：阿里|联手|工商|破获|重庆亿|元|刷单|案，怎么来解决“重庆亿”粘合的问题，我加了自定义词典了，还是会出现这个问题。

**Comment by endyul** [comment]
自定义词典功能不保证模型完全按照词典切分

**Comment by lxj0276** [comment]
@endyul 有没有什么方法可以解决这个问题呢，希望可以指点一下

**Comment by endyul** [comment]
可以尝试编写额外的代码来强制切开
