### ISSUE TITLE
安装失败，能帮忙看一看吗？

### ISSUE THREAD

**Issue by HITFishily** [HIT-SCIR/pyltp#49]
mac系统下python2.7.11；Linux－ubuntu系统下python2.7.6，两个系统下两种安装方法都安装失败了，而且错误都是编译器的问题？求高人指导！
![2016-06-01 4 50 34](https://cloud.githubusercontent.com/assets/19208832/15703872/4d60ea60-281a-11e6-8ca0-3b09220805ba.png)

![2016-06-01 4 54 33](https://cloud.githubusercontent.com/assets/19208832/15703894/65717bb0-281a-11e6-8dc0-25b01140a4c8.png)

**Comment by Oneplus** [comment]
是不是没装c++编译器？
http://ubuntuforums.org/showthread.php?t=345201

**Comment by HITFishily** [comment]
装完之后再试了一次依然失败，还有就是pip install命令需要在特定文件夹吗？
![2016-06-01 6 03 53](https://cloud.githubusercontent.com/assets/19208832/15705834/7850f496-2823-11e6-9ef2-b93a626c8d2a.png)

**Comment by Oneplus** [comment]
还得装python-devel

**Comment by HITFishily** [comment]
成功安装，谢谢！！

**Comment by wang150973** [comment]
我也是相同的错误，请问怎么解决的？ @HITFishily

**Comment by pipi2012** [comment]
大神，您好，请问是怎么解决的呢
