### ISSUE TITLE
Python版本"元芳你怎么看"分词分不开

### ISSUE THREAD

**Issue by breadada** [HIT-SCIR/pyltp#50]
Hi, 我用主页上的demo"元芳你怎么看"想看分词效果，使用的ltp_data/cws.model，发现词分不开，是一整句，这是什么原因？

另外，example.py中"中国进出口银行与中国银行加强合作。"可以实现分词，我把这个换成“元芳你怎么看”，也是分不开的。

Python2.7, gcc 4.4.6

![1](https://cloud.githubusercontent.com/assets/11451898/16642320/55f0317a-443c-11e6-9b21-9b016ca5a83d.png)
![2](https://cloud.githubusercontent.com/assets/11451898/16642327/6335f298-443c-11e6-800c-66df3d3aee39.png)

**Comment by endyul** [comment]
请根据文档下载完整模型

**Comment by breadada** [comment]
不好意思，没看清楚。下载完整模型之后可以了，谢谢！
