### ISSUE TITLE
分词不成功

### ISSUE THREAD

**Issue by songtailun** [HIT-SCIR/pyltp#53]
![screen shot 2016-08-19 at 12 50 08 pm](https://cloud.githubusercontent.com/assets/14933335/17817240/8677e310-660b-11e6-9a4a-4e14ff370a3f.png)

**Comment by endyul** [comment]
是否下载了完整模型
http://pyltp.readthedocs.io/zh_CN/latest/install.html#pip

**Comment by songtailun** [comment]
我是直接下载的你们repo，使用了ltp_data里的模型，是不是那个模型不是完整的？

**Comment by endyul** [comment]
嗯，那个是测试模型。
忘记在文档里说明了

**Comment by songtailun** [comment]
谢谢endyul解答，还有一个问题是：
```
>>> words = segmentor.segment('元芳你怎么看')
>>> type(words)
<class 'pyltp.VectorOfString'>
**>>> words_list = list(words)**
>>> type(words_list)
<type 'list'>
```

我使用python2.7 没办法直接直接转成list
TypeError: 'list' object is not callable

**Comment by endyul** [comment]
能提供完整代码吗？

**Comment by songtailun** [comment]
![screen shot 2016-08-19 at 1 11 01 pm](https://cloud.githubusercontent.com/assets/14933335/17817801/67c40888-660e-11e6-9227-59547ed316a0.png)

**Comment by endyul** [comment]
`type(list)`的结果是什么？

**Comment by songtailun** [comment]
word_list = list(words) 已经报错了。没有type(list)的结果

**Comment by endyul** [comment]
`type(list)`是额外的，不在这些代码里，建议放到`word_list = list(words)`前一行输出一下，想看下你的环境的结果

**Comment by songtailun** [comment]
![screen shot 2016-08-19 at 1 22 50 pm](https://cloud.githubusercontent.com/assets/14933335/17818109/0c39639e-6610-11e6-8260-b1b015b990ad.png)

**Comment by endyul** [comment]
`list`被覆盖为一个对象了
前面有没有`list = [1,2,3]`这样的代码？

**Comment by songtailun** [comment]
对的，我之前初始化过一个叫list 的list，现在好了，谢谢解答
