### ISSUE TITLE
运用几个功能返回结果为空，但是并未报错。

### ISSUE THREAD

**Issue by 940851993** [HIT-SCIR/pyltp#55]
命名实体识别，语义角色标注在调用后返回为空。分词，词性标注，分词仍然能用。
用的anaconda自带的Spyder编辑器，python 3.5
`from pyltp import Parser,Postagger,Segmentor,NamedEntityRecognizer,SementicRoleLabeller

segmentor = Segmentor()  # 分词
segmentor.load('E:\ltp-data-v3.3.1(1)\ltp_data\cws.model')  # 加载模型
words = segmentor.segment('运用几个功能返回结果为空，但是并未报错。')  # 分词
print ('\t'.join(words))
segmentor.release()  # 释放模型

postagger=Postagger()#词性标注
postagger.load('E:\ltp-data-v3.3.1(1)\ltp_data\pos.model')
postages=postagger.postag(words)
print( '\t'.join(postages))
postagger.release()

parser = Parser() # 依存句法分析
parser.load('E:\ltp-data-v3.3.1(1)\ltp_data\parser.model')  # 加载模型
arcs = parser.parse(words, postages)  # 句法分析
print ("\t".join("%d:%s" % (arc.head, arc.relation) for arc in arcs))
parser.release()  # 释放模型
# 命名实体识别

recognizer = NamedEntityRecognizer() # 命名实体识别
recognizer.load('E:\ltp-data-v3.3.1(1)\ltp_data\ner.model')  # 加载模型
netags = recognizer.recognize(words, postages)  # 命名实体识别
print ('\t'.join(netags))
recognizer.release() 

labeller = SementicRoleLabeller() # 语义角色标注
labeller.load('E:\ltp-data-v3.3.1(1)\ltp_data\srl')  # 加载模型
roles = labeller.label(words, postages, netags, arcs)  # 语义角色标注
for role in roles:
    print (role.index, "".join(
        ["%s:(%d,%d)" % (arg.name, arg.range.start, arg.range.end) for arg in role.arguments]))
labeller.release()  # 释放模型
`
返回结果为
`运用      几       个       功能      返回      结果      为       空       ，       但是      并       未       报错      。
v       m       q       n       v       n       v       a       wp      c       d       d       v       wp
0:HED   3:ATT   4:ATT   1:VOB   1:COO   5:VOB   5:COO   7:VOB   1:WP    13:ADV  13:ADV  13:ADV  1:COO   1:WP

`

**Comment by endyul** [comment]
一句话中可能不包含命名实体或语义角色

Regards --
On 周二, 9月 20, 2016 at 13:15, 940851993 <notifications@github.com> wrote:
命名实体识别，语义角色标注在调用后返回为空。分词，词性标注，分词仍然能用。
用的anaconda自带的Spyder编辑器，python 3.5
`from pyltp import Parser,Postagger,Segmentor,NamedEntityRecognizer,SementicRoleLabeller

segmentor = Segmentor() # 分词
segmentor.load('E:\ltp-data-v3.3.1(1)\ltp_data\cws.model') # 加载模型
words = segmentor.segment('运用几个功能返回结果为空，但是并未报错。') # 分词
print ('\t'.join(words))
segmentor.release() # 释放模型

postagger=Postagger()#词性标注
postagger.load('E:\ltp-data-v3.3.1(1)\ltp_data\pos.model')
postages=postagger.postag(words)
print( '\t'.join(postages))
postagger.release()

parser = Parser() # 依存句法分析
parser.load('E:\ltp-data-v3.3.1(1)\ltp_data\parser.model') # 加载模型
arcs = parser.parse(words, postages) # 句法分析
print ("\t".join("%d:%s" % (arc.head, arc.relation) for arc in arcs))
parser.release() # 释放模型

#命名实体识别
recognizer = NamedEntityRecognizer() # 命名实体识别
recognizer.load('E:\ltp-data-v3.3.1(1)\ltp_data\ner.model') # 加载模型
netags = recognizer.recognize(words, postages) # 命名实体识别
print ('\t'.join(netags))
recognizer.release()

labeller = SementicRoleLabeller() # 语义角色标注
labeller.load('E:\ltp-data-v3.3.1(1)\ltp_data\srl') # 加载模型
roles = labeller.label(words, postages, netags, arcs) # 语义角色标注
for role in roles:
print (role.index, "".join(
["%s:(%d,%d)" % (arg.name, arg.range.start, arg.range.end) for arg in role.arguments]))
labeller.release() # 释放模型

返回结果为
运用 几 个 功能 返回 结果 为 空 ， 但是 并 未 报错 。
v m q n v n v a wp c d d v wp
0:HED 3:ATT 4:ATT 1:VOB 1:COO 5:VOB 5:COO 7:VOB 1:WP 13:ADV 13:ADV 13:ADV 1:COO 1:WP

`

**Comment by 940851993** [comment]
张三把苹果吃了……也没显示。

**Comment by Oneplus** [comment]
1. 请首先确认输入的句子是有实体与语义角色的
2. 机器学习模型不能保证输出结果完全正确
3. 请了解ltp能够识别的实体类型以及语义角色类型。
