### ISSUE TITLE
mac os 提示安装成功，但是 from pyltp import Segmentor的时候 说 no module named pyltp

### ISSUE THREAD

**Issue by sherlockhoatszx** [HIT-SCIR/pyltp#56]
mac os 通过pip install 安装成功了，但是在程序中无法调用pyltp 我又安装git的方法试了一次，还是不行。这是为什么呢

**Comment by sherlockhoatszx** [comment]
我用git的办法安装，python setup.py install 之后 返回的结果是

clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'clang++' failed with exit status 1

**Comment by NanoToybox** [comment]
same problem here.

**Comment by NanoToybox** [comment]
@sherlockhoatszx  试试这个帖子里的两种办法 https://github.com/HIT-SCIR/pyltp/issues/52

**Comment by endyul** [comment]
是否可能是Python环境问题？是否安装过非系统自带的Python？尝试一下用virtualenv

**Comment by NanoToybox** [comment]
setup.py 中增加target ＝ 10.8 （＃52中提到的办法）后解决了这个问题  我的py…… 我想不起来了 好像的确不是best practice的安装

**Comment by BerlinChan** [comment]
@sherlockhoatszx 
我的Mac安装同样的问题，后来用IDE PyCharm删了包pyltp再从IDE里面安装就好了，见图
![2017-04-19 2 16 27](https://cloud.githubusercontent.com/assets/14348629/25146529/ca723a34-24a6-11e7-98d5-a15348369963.png)

**Comment by myallen** [comment]
跟python版本有关系，目前貌似只支持到python3.5，从python3.6降版本才解决的-_#

**Comment by forDaniel** [comment]
macOS 10.13
python 2.7 环境下使用，使用
MACOSX_DEPLOYMENT_TARGET=10.7 python setup.py install
安装可以通过编译。

**Comment by jiayuhemx** [comment]
![image](https://user-images.githubusercontent.com/32517978/47540011-a7517f00-d905-11e8-911d-737966dc0eff.png)
有大神知道我这个是python环境配置问题导致pyltp无法安装成功吗？
