### ISSUE TITLE
pyltp 0.1.9.1 conflict with anaconda 4.2.0 

### ISSUE THREAD

**Issue by waterblas** [HIT-SCIR/pyltp#58]
I intall pyltp by pip in anaconda 4.2.0  Ubuntu16.04 LTS envirnment, I get a problem when I run `import pyltp`:
```
... undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE
```
and then I install by source, still have the same problem.  I try to use `sudo python setup.py intall` and add package path in sys.path like:
```
import sys
sys.path.append(/usr/local/lib/python2.7/dist-packages/pyltp-0.1.9.1-py2.7-linux-x86_64.egg)
import pyltp
```
error message become:

```
 /home/?/anaconda2/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/lib/python2.7/dist-packages/pyltp-0.1.9.1-py2.7-linux-x86_64.egg/pyltp.so)
```
So I think the problem come from anaconda 4.2.0 envirnment libstdc++,  I run ` strings /home/ldy/anaconda2/bin/../lib/libstdc++.so.6 | grep GLIBCXX`

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
There is no `GLIBCXX_3.4.20`  in anaconda 4.2.0 libstdc++

**Solution**:
my solution is sample:
```
cd ~/anaconda2/lib
rm libstdc++.so.6.0.19
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6.0.19
```

check `strings libstdc++.so.6 | grep GLIBCXX`, you will find the following info:
```
...
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

I write down this to help other people who meet the same problem.

**Comment by endyul** [comment]
thanks for reporting

**Comment by zhhongzhi** [comment]
Thank you very much!

**Comment by santiagomvc** [comment]
Thank you very much! I had this problem with libsass and after a lot of searching your answer finally helped me.

**Comment by keaideii** [comment]
thank you very much!

**Comment by Oneplus** [comment]
Thanks for reporting this. However, I believe it's not a problem with pyltp but generic a linux linking problem. So I will close this issue for an archive.
