### ISSUE TITLE
pyltp不能安装

### ISSUE THREAD

**Issue by wangshang19911011** [HIT-SCIR/pyltp#59]
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  error: command 'clang++' failed with exit status 1
  
  ----------------------------------------
  **Failed building wheel for pyltp**
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command /Users/wangshang1011/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0y/9qm2kz4s1jz3ghpbhqt6chg00000gn/T/pip-build-oagyNZ/pyltp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/0y/9qm2kz4s1jz3ghpbhqt6chg00000gn/T/pip-Wljke6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build/temp.macosx-10.6-x86_64-2.7
    creating build/temp.macosx-10.6-x86_64-2.7/src
    creating build/temp.macosx-10.6-x86_64-2.7/ltp
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty/boost
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty/boost/libs
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty/boost/libs/regex
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty/boost/libs/regex/src
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/thirdparty/maxent
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/splitsnt
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/segmentor
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/postagger
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/ner
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/parser.n
    creating build/temp.macosx-10.6-x86_64-2.7/ltp/src/srl
    creating build/temp.macosx-10.6-x86_64-2.7/patch
    creating build/temp.macosx-10.6-x86_64-2.7/patch/libs
    creating build/temp.macosx-10.6-x86_64-2.7/patch/libs/python
    creating build/temp.macosx-10.6-x86_64-2.7/patch/libs/python/src
    creating build/temp.macosx-10.6-x86_64-2.7/patch/libs/python/src/object
    creating build/temp.macosx-10.6-x86_64-2.7/patch/libs/python/src/converter
    clang++ -fno-strict-aliasing -I/Users/wangshang1011/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ -I/Users/wangshang1011/anaconda/include/python2.7 -c src/pyltp.cpp -o build/temp.macosx-10.6-x86_64-2.7/src/pyltp.o -std=c++11 -Wno-c++11-narrowing -stdlib=libc++
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    error: command 'clang++' failed with exit status 1

**Comment by endyul** [comment]
please refer to #52
