### ISSUE TITLE
缺少空字符串判断

### ISSUE THREAD

**Issue by Nick-Alam** [HIT-SCIR/pyltp#61]
给定的例子程序中，如果传入全为空的字符串，抛出 ```fragment err```段错误，程序崩溃退出。

**Comment by endyul** [comment]
thanks for reporting. It will be fixed in next version

**Comment by Oneplus** [comment]
空字符串检测最好是由用户来做。短期内我们不会添加这个功能。如果以后计划添加，请reopen这个issue。
