### ISSUE TITLE
分词功能外部词典不work

### ISSUE THREAD

**Issue by opcoder** [HIT-SCIR/pyltp#63]
你好，我用`segment.load_with_lexicon('ltp.model/cws.model', 'extras/test.txt')`调用外部词典，test.txt只有一行`俄外长拉夫罗夫`， 但分词结果为 `俄, 外长, 拉夫罗夫`,。是我使用姿势不对吗？

**Comment by endyul** [comment]
外部词典是作为额外的feature提供给分词器，所以不能保证结果会完全依照外部词典切分。
另外由于ltp采用的分词标准是细粒度的，词的长度一般不超过5，所以像`俄外长拉夫罗夫`这样长度的词，ltp也不会认为是一个整体

**Comment by opcoder** [comment]
那有什么可以优先使用外部词典，并且放宽长度限制的方法吗，比如修改源码之类的？多谢~

**Comment by endyul** [comment]
暂时没有办法直接修改外部词典feature的权重
长度限制可以在`src/segmentor/segmentor.cpp`的`Segmentor::buid_lexicon_match_state`方法中进行hack

**Comment by suchenglong** [comment]
像你说的外部词典载入了也不一定使用外部词典的词，请问这个外部词典权重问题不会修复了吗。目前试了下部分外部词典可以，
