### ISSUE TITLE
There are some problem when the segmentor encounter with space

### ISSUE THREAD

**Issue by ericwtlin** [HIT-SCIR/pyltp#64]
In the code below,  there is a space in the string "我是 中国人", but after segmentation by pyltp, the space is missing.

the space is reserved when I use jieba.

`

    s = u'我是 中国人'
    #sent = s.encode('utf-8')
    sent = '我是 中国人'

    sent_seg = segmentor.segment(sent)
    sent_list = list(sent_seg)
    print("".join(sent_list))       #"我是中国人"

    segments = []
    for seg in sent_seg:
        segments.append(seg.decode('utf-8'))

    print(len(s))       # 6
    print(len("".join(segments)))   # 5
    print("|".join(segments))   #"我|是|中国|人"

    print("|".join(jieba.lcut(s)))  #"我|是| |中国|人"
`

**Comment by Oneplus** [comment]
In the near future, we won't take space as a word.
