### ISSUE TITLE
多次载入词典？

### ISSUE THREAD

**Issue by yangqinj** [HIT-SCIR/pyltp#65]
你好，我知道可以通过segmentor.load_with_lexicon()函数载入用户自定义的词典。然后我现在需要再已经载入用户词典的基础上，再次更新用户词典。我看segmentor.load_with_lexicon()函数里面，好像不允许这样做。请问有什么解决方法吗？谢谢。

**Comment by endyul** [comment]
抱歉，暂时没有提供增量添加词典或者reload词典的api。目前只能重新load一个模型了

**Comment by yangqinj** [comment]
那我可以这样做吗？先释放掉segmentor，然后重新load_with_lexicon()载入一个新的词典。但是旧词典中的词是不是就不在了？只有新词典中的词？
`  
segmentor.release()  
segmentor = Segmentor()  
segmentor.load_with_lexicon('./ltp_model/cws.model', loc_userdict)`

**Comment by endyul** [comment]
可以，是的…

**Comment by yangqinj** [comment]
好的，谢谢。
