### ISSUE TITLE
词性说明

### ISSUE THREAD

**Issue by yangqinj** [HIT-SCIR/pyltp#66]
你好，我在说明文档中看到ltp的词性说明，其中wp代表标点符号，但是是否有二级词性，能够标注是哪个标点符号，比如句号、感叹号、问号之类的？另外，说明文档中说ltp使用863词性标注集，但是我没有找到相关的资料，请问这是个什么词性标注集呢？谢谢。

**Comment by endyul** [comment]
抱歉，没有二级词性。词性标注集请参考ltp文档附录

**Comment by yangqinj** [comment]
好的，谢谢。
