### ISSUE TITLE
如何改变文本处理长度上限？pyltp在对文本中读取的长句进行命名实体识别时，报错“Kernel died, restarting”

### ISSUE THREAD

**Issue by Amyinclude** [HIT-SCIR/pyltp#67]
在对本地文本进行处理时，分词及词性标注都没有问题，可以正常输出。
但是一旦使用 命名实体识别recognizer.recognize(words, postags) ，就会直接报错“Kernel died, restarting”。
测试时发现，文本中有大量短句时，不会报错，猜测主要是因为长句问题。

请问如何设置才能解决这个问题？万分感谢

ps:
编程环境windows64位，python2.7，Spyder编译器。

**Comment by endyul** [comment]
暂时没有办法直接设置。建议用分句接口先分一下句

**Comment by Amyinclude** [comment]
好的，再次感谢
