### ISSUE TITLE
win10 64 anaconda2.7安装出现出现问题

### ISSUE THREAD

**Issue by genesis-git** [HIT-SCIR/pyltp#68]
系统win10 64位，python使用anaconda 2.7.10 安装了CMAKE，未安装VS软件，但是安装了VCForPython27.msi    参考了http://blog.csdn.net/laoyaotask/article/details/45312905
的链接但是依然没有解决问题，是直接pip安装么pyltp，pyltp页面给出的版本对应是什么意思？
pyltp 版本：0.1.9
LTP 版本：3.3.2
模型版本：3.3.1
模型3.3.1我能理解，LTP3.3.2是什么意思？pyltp内部不包含ltp么？难道安装pyltp之前还要先安装ltp？？

cmd中pip安装报错信息如下：
C:\Users\feilong>pip install pyltp
Collecting pyltp
  Using cached pyltp-0.1.9.1.tar.gz
Building wheels for collected packages: pyltp
  Running setup.py bdist_wheel for pyltp ... error
  Complete output from command "d:\program files\anaconda\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-jhmv0n\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\feilong\appdata\local\temp\tmp5rnzqgpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'pyltp' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\ltp
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\src
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
  creating build\temp.win-amd64-2.7\Release\ltp\src
  creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
  creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
  creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
  creating build\temp.win-amd64-2.7\Release\ltp\src\ner
  creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
  creating build\temp.win-amd64-2.7\Release\ltp\src\srl
  creating build\temp.win-amd64-2.7\Release\patch
  creating build\temp.win-amd64-2.7\Release\patch\libs
  creating build\temp.win-amd64-2.7\Release\patch\libs\python
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
  D:\Program Files\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ "-Id:\program files\anaconda\include" "-Id:\program files\anaconda\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
  gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
  gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
  gcc.exe: error: /EHsc: No such file or directory
  error: command 'D:\\Program Files\\Anaconda\\Scripts\\gcc.bat' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command "d:\program files\anaconda\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-jhmv0n\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\feilong\appdata\local\temp\pip-0qpvag-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\ltp
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\src
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
    creating build\temp.win-amd64-2.7\Release\ltp\src
    creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
    creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
    creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
    creating build\temp.win-amd64-2.7\Release\ltp\src\ner
    creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
    creating build\temp.win-amd64-2.7\Release\ltp\src\srl
    creating build\temp.win-amd64-2.7\Release\patch
    creating build\temp.win-amd64-2.7\Release\patch\libs
    creating build\temp.win-amd64-2.7\Release\patch\libs\python
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
    D:\Program Files\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ "-Id:\program files\anaconda\include" "-Id:\program files\anaconda\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
    gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
    gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
    gcc.exe: error: /EHsc: No such file or directory
    error: command 'D:\\Program Files\\Anaconda\\Scripts\\gcc.bat' failed with exit status 1

    ----------------------------------------
Command ""d:\program files\anaconda\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-jhmv0n\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\feilong\appdata\local\temp\pip-0qpvag-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\feilong\appdata\local\temp\pip-build-jhmv0n\pyltp\

C:\Users\feilong>

**Comment by endyul** [comment]
现在anaconda安装确实有问题。

另外不用先安装ltp。pyltp里面有包含

**Comment by endyul** [comment]
能告知一下anaconda的版本吗？
`python --version`

**Comment by genesis-git** [comment]
我试一下更新anaconda，我的anaconda是2.3版本 python 2.7.10，可能是我的版本太老了，谢谢endyul，非常感谢

**Comment by genesis-git** [comment]
https://www.continuum.io/downloads#windows
官网下载Python 2.7.13 :: Anaconda 4.3.1 (64-bit)   win10系统，运行pip失败
C:\Users\feilong>pip install pyltp
Collecting pyltp
  Using cached pyltp-0.1.9.1.tar.gz
Building wheels for collected packages: pyltp
  Running setup.py bdist_wheel for pyltp ... error
  Complete output from command "D:\Program Files\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-3wekg1\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\feilong\appdata\local\temp\tmp9h0fzipip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'pyltp' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\ltp
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\src
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
  creating build\temp.win-amd64-2.7\Release\ltp\src
  creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
  creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
  creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
  creating build\temp.win-amd64-2.7\Release\ltp\src\ner
  creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
  creating build\temp.win-amd64-2.7\Release\ltp\src\srl
  creating build\temp.win-amd64-2.7\Release\patch
  creating build\temp.win-amd64-2.7\Release\patch\libs
  creating build\temp.win-amd64-2.7\Release\patch\libs\python
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
  gcc -DMS_WIN64 -mdll -O -Wall -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ "-ID:\Program Files\anaconda2\include" "-ID:\Program Files\anaconda2\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
  error: command 'gcc' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command "D:\Program Files\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-3wekg1\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\feilong\appdata\local\temp\pip-omculj-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\ltp
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\src
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
    creating build\temp.win-amd64-2.7\Release\ltp\src
    creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
    creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
    creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
    creating build\temp.win-amd64-2.7\Release\ltp\src\ner
    creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
    creating build\temp.win-amd64-2.7\Release\ltp\src\srl
    creating build\temp.win-amd64-2.7\Release\patch
    creating build\temp.win-amd64-2.7\Release\patch\libs
    creating build\temp.win-amd64-2.7\Release\patch\libs\python
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
    gcc -DMS_WIN64 -mdll -O -Wall -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/srl/ -Ipatch/include/ "-ID:\Program Files\anaconda2\include" "-ID:\Program Files\anaconda2\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
    error: command 'gcc' failed: No such file or directory

    ----------------------------------------
Command ""D:\Program Files\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\feilong\\appdata\\local\\temp\\pip-build-3wekg1\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\feilong\appdata\local\temp\pip-omculj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\feilong\appdata\local\temp\pip-build-3wekg1\pyltp\

**Comment by genesis-git** [comment]
经过尝试版本  Python 2.7.12 :: Anaconda 4.2.0 (64-bit) ，问题得到解决，pip成功安装，谢谢endyul

**Comment by endyul** [comment]
谢谢反馈。4.3.1版本的问题还需寻找一下原因
