### ISSUE TITLE
增量训练模型加载进来似乎有问题

### ISSUE THREAD

**Issue by fseasy** [HIT-SCIR/pyltp#71]
用`otcws`个性化训练了一个增量模型，使用`otcws`的`customized-test`预测正常，但是使用pyltp的`CustomizedSegmenter().load_with_lexicon(base_path, incremental_path, lexicon_path)`之后发现分出来的词基本都是单字...

```
otcws
现在	使用	的	是	4G	的	自选套餐
pyltp
现  在  使  用  的  是  4G  的  自  选  套  餐
```

不知道是我操作有问题还是怎么了 = =； 使用`Segmentor().load_with_lexicon(base_path, lexicon_path)`效果是正常的。

**Comment by endyul** [comment]
`otcws`用的哪个版本，`pyltp`是哪个版本，`base_model`是哪个版本啊

**Comment by endyul** [comment]
现在`otcws`和dll接口backend的代码不一样，还得差一下原因..

**Comment by memeda** [comment]
sorry， 反馈得太马虎。
`otcws`使用的是最新主分支编译的版本(3.3.2)，`pyltp`应该是`0.1.9`,  `base_model`是3.3.1;
不急不急，就是反馈一下~ 毕设要紧 😭

**Comment by lounily** [comment]
Hello，你训练的增量模型最后试验成功了吗？我用customized_segmentor.load(base_model,incremental_model)加载的时候一直显示 “CustomizedSegmentor: Model not loaded!"

**Comment by wangtianyiftd** [comment]
@endyul  大神，求解答。

**Comment by endyul** [comment]
@lounily 检查一下模型路径是否正确

**Comment by lounily** [comment]
模型路径好像没有问题，
![image](https://user-images.githubusercontent.com/23011806/27064019-933e0708-5027-11e7-8442-e0d15cdceb26.png)

**Comment by lounily** [comment]
@endyul 模型路径好像没有问题，
![image](https://user-images.githubusercontent.com/23011806/27064512-5a8be918-502a-11e7-967b-8f037bc736fd.png)

**Comment by kenataccosys** [comment]
@endyul 我也有同一個問題

**Comment by lounily** [comment]
@endyul 上述程序在Linux环境下可以正常运行，但是windows下一直显示 “CustomizedSegmentor: Model not loaded!"是否存在编码问题，有什么方法可以解决，求解答，谢谢！

**Comment by hitweijinlong** [comment]
@endyul  模型 3.4.0 otcws3.4.0 otcws customized-learn 其中 --baseline-model 指定为cws.model ，训练出来增量模型通过CustomizedSegmentor加载之后传一个句子进去分词，返回的是整个句子,并没有进行分词处理，用otcws learn 指定 --dump-details true 训练自己的模型文件，再通过 otcws customized-learn 训练增量模型啊发现可以正常工作，请问是否 --baseline-model 不能指定为cws.model ？能否有解决方案，支持增加模型可成功执行

**Comment by AacidChan** [comment]
请问解决了吗 @memeda

**Comment by memeda** [comment]
@AacidChan 我这边没有哈

**Comment by AacidChan** [comment]
好吧，我也遇到了同样的问题，最后把otcws的customized-test重定向输出了

**Comment by xueyouluo** [comment]
测试了一下，3.4的版本，把custom model和baseline model的位置换一下就好了
`customized_segmentor.load('/path to your customized model', cws_model_path)`
