### ISSUE TITLE
pip install pyltp安装失败 win10 64位 Python 2.7.13 :: Anaconda 4.3.0 (64-bit)

### ISSUE THREAD

**Issue by xinan711456** [HIT-SCIR/pyltp#73]
Failed building wheel for pyltp
Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
Running setup.py install for pyltp ... error
Complete output from command D:\unclosed\Anaconda27\python.exe -u -c "import setuptools, tokenize;file='c:\users\30913\appdata\local\temp\pip-build-r8b0bt\pyltp\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\30913\appdata\local\temp\pip-ftqiqy-record\install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_ext
building 'pyltp' extension
error: INCLUDE environment variable is empty

----------------------------------------
Command "D:\unclosed\Anaconda27\python.exe -u -c "import setuptools, tokenize;file='c:\users\30913\appdata\local\temp\pip-build-r8b0bt\pyltp\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record c:\users\30913\appdata\local\temp\pip-ftqiqy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\30913\appdata\local\temp\pip-build-r8b0bt\pyltp\

**Comment by endyul** [comment]
anaconda 4.3 安装问题还没有解决  
有可能的话可以使用4.2版本，参考 #68

**Comment by xinan711456** [comment]
谢谢，换了anaconda 4.2版本，成功了，谢谢！

**Comment by xiaoying291228** [comment]
还是没有解决

**Comment by xiaoying291228** [comment]
Failed building wheel for pyltp
换成了您说的版本还是没有解决呢

**Comment by xinan711456** [comment]
https://github.com/HIT-SCIR/pyltp/issues/108 
应该是没问题的，试一下不同anaconda版本，或试一下pyltp最新版本。
tips:
（1）已成功在python2和python3上安装pyltp
（2）python2需要vcforpython2.7（根据报错找到相应软件安装即可）
（3）python3需要visualcppbuildtools_full2015（（根据报错找到相应软件安装即可））
（4）如果还是不行，清理pip cache内容重新安装：c:\用户(你的用户名)\AppData\Local\pip\cache\目录
（5）成功在python2和python3上安装成功pyltp，是没有pyltp文件夹的，只有pyltp.pyc和pyltp-info文件夹

**Comment by xiaoying291228** [comment]
Running setup.py install for pyltp ... error
请问这个错误怎么解决

**Comment by xinan711456** [comment]
直接pip install pyltp或pip install pyltp==0.1.9 或pip install pyltp==0.2.0 （版本不是很清楚）
你的问题我不是很清楚，你多试验一下，后来我安装过很多次都成功的

**Comment by xiaoying291228** [comment]
> 直接pip install pyltp或pip install pyltp==0.1.9 或pip install pyltp==0.2.0 （版本不是很清楚）
> 你的问题我不是很清楚，你多试验一下，后来我安装过很多次都成功的

嗯，好的，vcforpython2.7下载之后还要安装？还有安装的位置有要求吗

**Comment by xinan711456** [comment]
都是默认安装的，似乎没有提示让你选择安装路径。

**Comment by xiaoying291228** [comment]
换个版本成功了，非常感谢你的耐心解答
