### ISSUE TITLE
已经空格分割的子串不应该再次处理

### ISSUE THREAD

**Issue by microhuang** [HIT-SCIR/pyltp#74]
对"我爱自然语言处理元芳 怎么看"进行分词：
期待结果：
我 爱 自然 语言 处理 元芳 怎么看
实际结果：
我 爱 自然 语言 处理 元芳 怎么 看
请问如何支持“上游”已经分词后对结果不再分词这一需求？

**Comment by endyul** [comment]
无法判断上游是否已经分词。
你这个例子也有点问题，「怎么看」按照分词粒度应该是切开的

**Comment by microhuang** [comment]
我的意思就是，是否支持人为指定分词分割符，这样，如果我上游明确使用空格作为分词界限，在ltp处理的时候，就可以通知，对分词界限标记的词不再处理，方便多个分词算法进行串联，改善效果。

上面举的列子确实不太好，只是为了强调我逻辑上就是想把“怎么看”分在一起而已--因为它在上游已经分隔好了--其实就是我人为分的。

**Comment by endyul** [comment]
抱歉，没有限制边界的接口。
你可以从上游分好的每个子串中，选取你需要进一步分词的子串传入给ltp进行分词。

**Comment by microhuang** [comment]
明白，多谢。
