### ISSUE TITLE
pyltp安装成功，但是import pyltp的时候报错undefined symbol: _ZTVNSt__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by HelloLiulian** [HIT-SCIR/pyltp#75]
Ubuntu16.04.4，Anacoda 4.3.1 python 2.7.13 gcc 5.4.0环境下，python setup.py install成功，中间出现warning，没有error，最后出现了Finished processing dependencies for pyltp=0.1.9.1，import 出现上述错误

**Comment by HelloLiulian** [comment]
undefined symbol: _ZTVNSt__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE

**Comment by endyul** [comment]
try this #58

**Comment by HelloLiulian** [comment]
已经解决，感谢啦～
