### ISSUE TITLE
win7 64 anaconda2.7安装出现问题 

### ISSUE THREAD

**Issue by nash100** [HIT-SCIR/pyltp#78]
系统是win7 64位; python版本：Python 2.7.12 :: Anaconda 4.2.0 (64-bit)(之前是在Python 2.7.12 :: Anaconda custom (64-bit)同样报错),已安装cmake-3.8.1-win64-x64.msi和VCForPython27.msi.但是无论是在anaconda prompt还是cmd里  pip install pyltp还是报错：
C:\Users\pc>pip install pyltp
Collecting pyltp
  Using cached pyltp-0.1.9.1.tar.gz
Building wheels for collected packages: pyltp
  Running setup.py bdist_wheel for pyltp ... error
  Complete output from command "d:\program files\anaconda2\python.exe" -u -c "im
port setuptools, tokenize;__file__='c:\\users\\pc\\appdata\\local\\temp\\pip-bui
ld-dpplss\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.r
ead().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdi
st_wheel -d c:\users\pc\appdata\local\temp\tmppxyuwxpip-wheel- --python-tag cp27
:
  running bdist_wheel
  running build
  running build_ext
  building 'pyltp' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\ltp
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\src
  creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
  creating build\temp.win-amd64-2.7\Release\ltp\src
  creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
  creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
  creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
  creating build\temp.win-amd64-2.7\Release\ltp\src\ner
  creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
  creating build\temp.win-amd64-2.7\Release\ltp\src\srl
  creating build\temp.win-amd64-2.7\Release\patch
  creating build\temp.win-amd64-2.7\Release\patch\libs
  creating build\temp.win-amd64-2.7\Release\patch\libs\python
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
  creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
  D:\Program Files\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/inc
lude/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdpa
rty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagg
er/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src
/srl/ -Ipatch/include/ "-Id:\program files\anaconda2\include" "-Id:\program file
s\anaconda2\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o
 /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
  gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
  gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
  gcc.exe: error: /EHsc: No such file or directory
  error: command 'D:\\Program Files\\Anaconda2\\Scripts\\gcc.bat' failed with ex
it status 1

  ----------------------------------------
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command "d:\program files\anaconda2\python.exe" -u -c "
import setuptools, tokenize;__file__='c:\\users\\pc\\appdata\\local\\temp\\pip-b
uild-dpplss\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f
.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" i
nstall --record c:\users\pc\appdata\local\temp\pip-llimrn-record\install-record.
txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\src
    creating build\temp.win-amd64-2.7\Release\ltp
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\boost\libs\regex\sr
c
    creating build\temp.win-amd64-2.7\Release\ltp\thirdparty\maxent
    creating build\temp.win-amd64-2.7\Release\ltp\src
    creating build\temp.win-amd64-2.7\Release\ltp\src\splitsnt
    creating build\temp.win-amd64-2.7\Release\ltp\src\segmentor
    creating build\temp.win-amd64-2.7\Release\ltp\src\postagger
    creating build\temp.win-amd64-2.7\Release\ltp\src\ner
    creating build\temp.win-amd64-2.7\Release\ltp\src\parser.n
    creating build\temp.win-amd64-2.7\Release\ltp\src\srl
    creating build\temp.win-amd64-2.7\Release\patch
    creating build\temp.win-amd64-2.7\Release\patch\libs
    creating build\temp.win-amd64-2.7\Release\patch\libs\python
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
    creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
    D:\Program Files\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/i
nclude/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/third
party/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/posta
gger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/s
rc/srl/ -Ipatch/include/ "-Id:\program files\anaconda2\include" "-Id:\program fi
les\anaconda2\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp
.o /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
    gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
    gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
    gcc.exe: error: /EHsc: No such file or directory
    error: command 'D:\\Program Files\\Anaconda2\\Scripts\\gcc.bat' failed with
exit status 1

    ----------------------------------------
Command ""d:\program files\anaconda2\python.exe" -u -c "import setuptools, token
ize;__file__='c:\\users\\pc\\appdata\\local\\temp\\pip-build-dpplss\\pyltp\\setu
p.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n',
'\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users
\pc\appdata\local\temp\pip-llimrn-record\install-record.txt --single-version-ext
ernally-managed --compile" failed with error code 1 in c:\users\pc\appdata\local
\temp\pip-build-dpplss\pyltp\

**Comment by nash100** [comment]
尝试本地安装python setup.py install，也不行:
running install
running bdist_egg
running egg_info
creating pyltp.egg-info
writing pyltp.egg-info\PKG-INFO
writing top-level names to pyltp.egg-info\top_level.txt
writing dependency_links to pyltp.egg-info\dependency_links.txt
writing manifest file 'pyltp.egg-info\SOURCES.txt'
reading manifest file 'pyltp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.h' under directory 'ltp\src'
warning: no files found matching '*.h' under directory 'ltp\src\framework'
warning: no files found matching '*.hpp' under directory 'ltp\src\framework'
warning: no files found matching '*.h' under directory 'ltp\src\utils'
warning: no files found matching '*.hpp' under directory 'ltp\src\utils'
warning: no files found matching '*.tab' under directory 'ltp\src\utils'
warning: no files found matching '*.cpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.h' under directory 'ltp\src\segmentor'
warning: no files found matching '*.hpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.cpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.h' under directory 'ltp\src\postagger'
warning: no files found matching '*.hpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.cpp' under directory 'ltp\src\ner'
warning: no files found matching '*.h' under directory 'ltp\src\ner'
warning: no files found matching '*.hpp' under directory 'ltp\src\ner'
warning: no files found matching '*.cpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.h' under directory 'ltp\src\parser.n'
warning: no files found matching '*.hpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.cpp' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\src\srl'
warning: no files found matching '*.hpp' under directory 'ltp\src\srl'
warning: no files found matching '*.hh' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.hpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*' under directory 'ltp\thirdparty\eigen-3.2.4
'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\maxent'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\maxent'

writing manifest file 'pyltp.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'pyltp' extension
creating build
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\src
creating build\temp.win-amd64-2.7\Release\patch
creating build\temp.win-amd64-2.7\Release\patch\libs
creating build\temp.win-amd64-2.7\Release\patch\libs\python
creating build\temp.win-amd64-2.7\Release\patch\libs\python\src
creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\object
creating build\temp.win-amd64-2.7\Release\patch\libs\python\src\converter
D:\Program Files\Anaconda2\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -Iltp/inclu
de/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/eigen-3.2.4 -Iltp/thirdpart
y/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger
/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/utils/ -Iltp/src/s
rl/ -Ipatch/include/ "-ID:\Program Files\Anaconda2\include" "-ID:\Program Files\
Anaconda2\PC" -c src\pyltp.cpp -o build\temp.win-amd64-2.7\Release\src\pyltp.o /
DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
gcc.exe: error: /DBOOST_PYTHON_SOURCE: No such file or directory
gcc.exe: error: /DBOOST_PYTHON_STATIC_LIB: No such file or directory
gcc.exe: error: /EHsc: No such file or directory
error: command 'D:\\Program Files\\Anaconda2\\Scripts\\gcc.bat' failed with exit
 status 1

**Comment by RingWong** [comment]
我遇到的问题和您一样，请问您是怎么解决的？
