### ISSUE TITLE
切词遇到空格会被忽略掉

### ISSUE THREAD

**Issue by wangtianyiftd** [HIT-SCIR/pyltp#79]
sentence = “渣  一点都不好”
分词后的结果为：['渣一点', '都', '不好']，两个空格都不见了。这使得切词后的句子无法完备对应回原始句子？

**Comment by ReiraLeung** [comment]
因为中文语言习惯里面没有空格的表达吧，，，我们都是使用标点符号分割的，我猜

**Comment by Oneplus** [comment]
我们短期内不打算把空格当成词

**Comment by Oneplus** [comment]
reference: https://github.com/HIT-SCIR/pyltp/issues/64

**Comment by liyi193328** [comment]
请问中英文混杂的时候，有些英文名字是有空格的， 分词把空格省略了， 恢复原始句子还得重新处理一遍？ 望回复， 谢谢

**Comment by ReiraLeung** [comment]
抱歉没有用过英文，切词的问题倒是很恶心，，，主要就是模型不识别，你用多少空格都没用，，，我建议你用下划线取代空格链接，这样说不定会被当做特殊词汇划到一起。

**Comment by xiaotanzhuying** [comment]
空格的问题关键是切词前后字符数量不一致！！影响后续处理流程
