### ISSUE TITLE
依存句法用得太多会因内存错误而崩溃掉？

### ISSUE THREAD

**Issue by wangtianyiftd** [HIT-SCIR/pyltp#80]
在使用过程中发现一件事情，好像是因为依存句法的关系，在批量操作（切词+词性+依存句法）一定量，这个量不一定，有的时候几百行，有的时候上万行，会导致程序崩溃掉，内存访问错误。这个请问有什么解决方法么？

Ps：严重的时候尝试过处理100行就sleep几秒，释放一下模型，但依然有可能崩溃掉/(ㄒoㄒ)/~~

**Comment by endyul** [comment]
能否提供一下您的代码

**Comment by wangtianyiftd** [comment]
@endyul  
已发现问题，其实是命名实体的缘故，因为是一起做的，所以以为是依存句法，是个误会，大量使用命名实体确实有导致崩溃的风险。
