### ISSUE TITLE
Can pyltp support mutil-threads in the origin ltp

### ISSUE THREAD

**Issue by miaobug** [HIT-SCIR/pyltp#82]
I noticed that the ltp_test command-line script support such feature
>usage: ./ltp_test <options>
>options:
> --threads arg           The number of threads [default=1].

Can pyltp do such thing?

**Comment by endyul** [comment]
i'm sorry that multithread is not supported by pyltp api.  
However you should implement it by your own with Python's multithread or multiprocess, for that analysis of pyltp is thread safe
