### ISSUE TITLE
ubuntu虚拟机安装pyltp不成功

### ISSUE THREAD

**Issue by zemu121** [HIT-SCIR/pyltp#87]
按照官网教程，使用git方法安装，安装失败……

**Comment by endyul** [comment]
错误信息？

**Comment by zemu121** [comment]
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-7004.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  http://packages.python.org/distribute/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by endyul** [comment]
这是您用户权限问题导致的。请参考错误信息内的解决方案

Regards --
On Fri, Jun 16, 2017 at 15:44, zemu121 <notifications@github.com> wrote:
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

[Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-7004.pth'


The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

/usr/local/lib/python2.7/dist-packages/


Perhaps your account does not have write access to this directory? If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account. If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

http://packages.python.org/distribute/easy_install.html [http://packages.python.org/distribute/easy_install.html]

Please make the appropriate changes for your system and try again.

**Comment by zemu121** [comment]
在ubuntu上安装pyltp，之前需要安装其他依赖吗

**Comment by endyul** [comment]
不需要其它依赖

Regards --
On Fri, Jun 16, 2017 at 15:47, zemu121 <notifications@github.com> wrote:
在ubuntu上安装pyltp，之前需要安装其他依赖吗

**Comment by zemu121** [comment]
利用sudo python setup.py install 重新安装，出现如下错误信息：
patch/include/boost/python/detail/wrap_python.hpp:75:24: fatal error: patchlevel.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by endyul** [comment]
可能因为虚拟机内存不足，编译器无法申请到内存。请扩容后重试

Regards --
On Fri, Jun 16, 2017 at 15:49, zemu121 <notifications@github.com> wrote:
利用sudo python setup.py install 重新安装，出现如下错误信息：
patch/include/boost/python/detail/wrap_python.hpp:75:24: fatal error: patchlevel.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by zemu121** [comment]
OK，thanks very much！另外，这个包还在升级吗

**Comment by endyul** [comment]
还在维护，近期会有一次更新

**Comment by zemu121** [comment]
太好了，点赞
