### ISSUE TITLE
Python 3.5.2   |  Anaconda 4.2.0    win10  64bit 无法pip install pyltp

### ISSUE THREAD

**Issue by xinan711456** [HIT-SCIR/pyltp#88]
谢谢你们的热心，已经解决了。pip安装在Anaconda 4.2.0 python2.7和3.5都是可以的。（我的是这个版本，其它版本没测试过。还有安装的是pyltp 0.1.9）
如果是编译报错，根据提示下载vcforpython安装即可；
如果再报错，或者是之前cache包冲突，清理c:\用户\(你的用户名)\AppData\Local\pip\cache\目录下的内容，然后再pip安装即可.

您好！
（1）请问有特定版本的Anaconda3支持pyltp吗？
（2）我试验了单独的python3也无法安装pyltp，不知道是不是版本不对。
谢谢！

**Comment by zhaosanjin** [comment]
可以的，用pip进行安装

**Comment by liyi193328** [comment]
visual studio 2017 应该是不行吧？只支持到vs 2015？

**Comment by FannyChung** [comment]
我在python3.6,64位下安装也是不成功的，不管是用pip命令还是msi文件，有谁知道怎么弄吗？

**Comment by liyi193328** [comment]
@FannyChung 下载源码， python setup.py install这种方式可以成功（中间可能有些编译错误的问题， 但是google一下都可以解决）， pip install 不好使

**Comment by FannyChung** [comment]
@liyi193328 感谢，好像之前的代码能安装成功，但是更新到pyltp0.2.0之后好像不能用python setup.py这个方式了。出现安装到一半卡了不动的情况，请问有什么解决方法吗？
![image](https://user-images.githubusercontent.com/5433467/33823979-d5853c2c-de97-11e7-85b6-58feed4f2422.png)

**Comment by liu946** [comment]
以下是我们ci工具编译同样一个文件通过的结果。注意一下其中一个版本号的位置，看到您编译中生成的头文件地址中这个位置没有被正确生成，可能和这个有关。
如果您解决了此问题。还请您在这里回复一下您的解决方法以帮助其他人。
<img width="906" alt="2017-12-11 11 13 47" src="https://user-images.githubusercontent.com/7871150/33838018-2abc1608-dec9-11e7-8476-c456feb048fc.png">

**Comment by SunflowerSmileYY** [comment]
anaconda3 pylpt0.18可以安装成功，实在不行可以试试这个下面的wheel文件http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/
