### ISSUE TITLE
运行过程中报了一个段错误是怎么回事啊

### ISSUE THREAD

**Issue by yuye2133** [HIT-SCIR/pyltp#89]
/tmp/hudson4444762354510794047.sh: line 2: 31177 Segmentation fault
这是错误提示。这个错误并不是一直 有，而是跑了很长一段时间后才发生的，请问这个要怎么解决啊。

**Comment by endyul** [comment]
您好，请问能提供运行的代码吗。

**Comment by xiaoxiaoyuan8github** [comment]
我在centos上用pyltp也遇到类似问题：
kernel: python3[14522]: segfault at 35 ip 00007efd1ed3cd12 sp 00007efccc833ab0 error 4 in pyltp.cpython-36m-x86_64-linux-gnu.so
本人对c/c++的也不熟，请问一般是什么原因导致，如何解决？谢谢

**Comment by liu946** [comment]
一般是内存访问越界引起的。请您检查一下是否有相关问题。如果还是不能解决，可以开新的issue，并提供更详细的信息，以便解决问题。
