### ISSUE TITLE
 “CustomizedSegmentor: Model not loaded!”问题（Python 3.6.1 | Anaconda 4.4.0 win7 64bit）

### ISSUE THREAD

**Issue by wanli2014** [HIT-SCIR/pyltp#90]
@endyul 您好！最近在使用pyltp个性化分词功能，遇到了`“CustomizedSegmentor: Model not loaded!”`问题，代码如下所示。经调试确认，代码是在执行代码`“CustomizedSegmentor.segment(str)”`时报出上述错误。请教一下，该如何解决？

```python
# -*- coding: utf-8 -*-
import os
from pyltp import CustomizedSegmentor

LTP_DATA_DIR = './'  # ltp模型目录的路径
cws_model_path = os.path.join(LTP_DATA_DIR, 'cws.model')  # 分词模型路径，模型名称为`cws.model`
custom_model_path = os.path.join(LTP_DATA_DIR, 'selfcws-30.model')

customized_segmentor = CustomizedSegmentor()  # 初始化实例
customized_segmentor.load(cws_model_path, custom_model_path)
words = customized_segmentor.segment('亚硝酸盐是一种化学物质')
print ('\t'.join(words))
customized_segmentor.release()
```
运行环境如下所示：
> - 操作系统：win7 64位
> - 安装环境：Python 3.6.1 | Anaconda 4.4.0(64-bit)
> - pyltp版本：0.1.9.1

另外，在linux环境下pyltp个性化分词可以正常运行，使用模型文件、pyltp版本和win7环境下完全一致。

**Comment by weitingyuk** [comment]
你好 我也遇到同样的问题，请问怎么解决的？

**Comment by djblovecxc** [comment]
+1 我也遇到了这样的问题

**Comment by wanli2014** [comment]
@endyul 调试源代码发现segment_dll.cpp加载个性化模型时，没有指定参数为binary，导致了个性化模型加载失败；添加该参数以后，就可以正常加载个性化模型了。

**Comment by y00282200** [comment]
请问你是怎么制定这参数为binary的？

**Comment by lxy444** [comment]
@wanli2014 同问，是怎么指定参数为 binary 的？

**Comment by c123853648** [comment]
> @endyul 调试源代码发现segment_dll.cpp加载个性化模型时，没有指定参数为binary，导致了个性化模型加载失败；添加该参数以后，就可以正常加载个性化模型了。

请问这个参数如何添加啊？

**Comment by movinglang** [comment]
请问一下，问题解决了吗？
