### ISSUE TITLE
无法加载SRL model

### ISSUE THREAD

**Issue by HikaruL** [HIT-SCIR/pyltp#91]
我是用的是百度云下载的ltp_data, 附截图，不知道如何解决， 谢谢！ 其他模块均能正常使用。
![sketch](https://user-images.githubusercontent.com/19523304/27610589-cf887636-5b43-11e7-89da-19a422462a59.png)

**Comment by HughWen** [comment]
+1

**Comment by HikaruL** [comment]
已解决，版本问题，参考https://github.com/HIT-SCIR/ltp/issues/229
