### ISSUE TITLE
Windows 64位安装时出错，

### ISSUE THREAD

**Issue by ReiraLeung** [HIT-SCIR/pyltp#92]
我的Windows是装了最新的VS(2017)，在cmd终端中使用cl语句是有效的。
不管使用pip安装还是setup.py安装都会遇到这个问题：
## Microsoft Visual C++ 9.0 is required.

不知道这种问题有没有可行的方法解决。拜托了。

应该是可是在windows环境下安装的吧，，，，，，

**Comment by ReiraLeung** [comment]
嗯嗯，那个比较讽刺的是，我刚发这个帖子，似乎就安装成功了，
解决的方法是下载并运行VC++ for python27
就是这位博主提出的。
http://blog.csdn.net/roler_/article/details/40398789

下载的网址是：https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

**Comment by endyul** [comment]
感谢反馈

**Comment by lambdaphy** [comment]
请问python 3环境可以安装吗？还是只能安装python2.7？
