### ISSUE TITLE
setup.py 安装失败

### ISSUE THREAD

**Issue by kotomo** [HIT-SCIR/pyltp#94]
running install
running bdist_egg
running egg_info
writing dependency_links to pyltp.egg-info\dependency_links.txt
writing pyltp.egg-info\PKG-INFO
writing top-level names to pyltp.egg-info\top_level.txt
reading manifest file 'pyltp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.h' under directory 'ltp\src'
warning: no files found matching '*.h' under directory 'ltp\src\framework'
warning: no files found matching '*.hpp' under directory 'ltp\src\framework'
warning: no files found matching '*.h' under directory 'ltp\src\utils'
warning: no files found matching '*.hpp' under directory 'ltp\src\utils'
warning: no files found matching '*.tab' under directory 'ltp\src\utils'
warning: no files found matching '*.cpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.h' under directory 'ltp\src\segmentor'
warning: no files found matching '*.hpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.cpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.h' under directory 'ltp\src\postagger'
warning: no files found matching '*.hpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.cpp' under directory 'ltp\src\ner'
warning: no files found matching '*.h' under directory 'ltp\src\ner'
warning: no files found matching '*.hpp' under directory 'ltp\src\ner'
warning: no files found matching '*.cpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.h' under directory 'ltp\src\parser.n'
warning: no files found matching '*.hpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.cpp' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\src\srl'
warning: no files found matching '*.hpp' under directory 'ltp\src\srl'
warning: no files found matching '*.hh' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.hpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*' under directory 'ltp\thirdparty\eigen-3.2.4'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\maxent'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\maxent'
writing manifest file 'pyltp.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'pyltp' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/third
party/eigen-3.2.4 -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp
/src/utils/ -Iltp/src/srl/ -Ipatch/include/ -IC:\ProgramData\Anaconda3\envs\tensorflow\include -IC:\ProgramData\Anaconda3\envs\tensorflow\include "-IC:\Program Files (x86
)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\includ
e\um" "-IC:\Program Files (x86)\Microsoft Visual Studio .NET 2003\SDK\v1.1\include\" /EHsc /Tpsrc\pyltp.cpp /Fobuild\temp.win-amd64-3.5\Release\src\pyltp.obj /DBOOST_PYTH
ON_SOURCE /DBOOST_PYTHON_STATIC_LIB /EHsc
cl : Command line error D8003 : missing source filename
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by FannyChung** [comment]
我在安装pyltp0.2.0的时候也遇到这个问题，请问你解决了吗？我是卡在倒数第四行：.../EHsc了

**Comment by guanleiui** [comment]
一摸一样，pip也不行

**Comment by liu946** [comment]
请问你们遇到的是什么问题，能否给出报错信息呢？开issue的同学是在7月份编译的，当时还没有上0.2.0版本。

**Comment by wh93hz** [comment]
win10 64位，安装的python版本是3.6，VS2015。pip 安装pyltp提示
src\pyltp.cpp(17): fatal error C1083: Cannot open include file: 'SplitSentence.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by wh93hz** [comment]
python3.6.3,64位，安装visual studio 2017 community之后，也还是提示cl.exe' failed with exit status 2.
具体提示信息如下：
D:\我的软件\pyltp-master>python setup.py install
running install
running bdist_egg
running egg_info
writing pyltp.egg-info\PKG-INFO
writing dependency_links to pyltp.egg-info\dependency_links.txt
writing top-level names to pyltp.egg-info\top_level.txt
reading manifest file 'pyltp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.h' under directory 'ltp\src'
warning: no files found matching '*.h' under directory 'ltp\src\framework'
warning: no files found matching '*.hpp' under directory 'ltp\src\framework'
warning: no files found matching '*.h' under directory 'ltp\src\utils'
warning: no files found matching '*.hpp' under directory 'ltp\src\utils'
warning: no files found matching '*.tab' under directory 'ltp\src\utils'
warning: no files found matching '*.cpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.h' under directory 'ltp\src\segmentor'
warning: no files found matching '*.hpp' under directory 'ltp\src\segmentor'
warning: no files found matching '*.cpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.h' under directory 'ltp\src\postagger'
warning: no files found matching '*.hpp' under directory 'ltp\src\postagger'
warning: no files found matching '*.cpp' under directory 'ltp\src\ner'
warning: no files found matching '*.h' under directory 'ltp\src\ner'
warning: no files found matching '*.hpp' under directory 'ltp\src\ner'
warning: no files found matching '*.cpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.h' under directory 'ltp\src\parser.n'
warning: no files found matching '*.hpp' under directory 'ltp\src\parser.n'
warning: no files found matching '*.cpp' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\src\srl'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.hpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*.ipp' under directory 'ltp\thirdparty\boost'
warning: no files found matching '*' under directory 'ltp\thirdparty\eigen'
warning: no files found matching '*' under directory 'ltp\thirdparty\dynet'
warning: no files found matching '*.h' under directory 'ltp\thirdparty\maxent'
warning: no files found matching '*.cpp' under directory 'ltp\thirdparty\maxent'
writing manifest file 'pyltp.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'pyltp' extension
D:\VS2017\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -ID:\SOFTWARE\Python\include -ID:\SOFTWARE\Python\include -ID:\VS2017\VC\Tools\MSVC\14.12.25827\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tpsrc\pyltp.cpp /Fobuild\temp.win-amd64-3.6\Release\src\pyltp.obj /DNOMINMAX /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /DBOOST_ALL_NO_LIB /D_WINDOWS /EHsc
pyltp.cpp
Unknown compiler version - please run the configure tests and report the results
patch/include/boost/python/detail/caller.hpp(55): warning C4244: “return”: 从“Py_ssize_t”转换到“unsigned int”，可能丢失 数据
src\pyltp.cpp(17): fatal error C1083: 无法打开包括文件: “SplitSentence.h”: No such file or directory
error: command 'D:\\VS2017\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by wangchenwei2000** [comment]
building 'pyltp' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -I/home/ubuntu/anaconda3/include/python3.6m -c src/pyltp.cpp -o build/temp.linux-x86_64-3.6/src/pyltp.o -std=c++0x
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/pyltp.cpp:17:27: fatal error: SplitSentence.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by ELI95** [comment]
building 'pyltp' extension
gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -I/root/anaconda3/include/python3.6m -c src/pyltp.cpp -o build/temp.linux-x86_64-3.6/src/pyltp.o -std=c++0x
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/pyltp.cpp:17:27: fatal error: SplitSentence.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by WilliamPython** [comment]
我的环境：win10 64位 python 3.6.4（32）
C:\Users\001>pip install pyltp
Collecting pyltp
  Using cached pyltp-0.2.1.tar.gz
Building wheels for collected packages: pyltp
  Running setup.py bdist_wheel for pyltp ... error
  Complete output from command c:\users\001\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\001\\AppData\\Local\\Temp\\pip-build-u9fp4s2s\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\001\AppData\Local\Temp\tmp15mijfm5pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyltp' extension
  creating build
  creating build\temp.win32-3.6
  creating build\temp.win32-3.6\Release
  creating build\temp.win32-3.6\Release\src
  creating build\temp.win32-3.6\Release\ltp
  creating build\temp.win32-3.6\Release\ltp\thirdparty
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\regex
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\regex\src
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\program_options
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\program_options\src
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\serialization
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\serialization\src
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\smart_ptr
  creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\smart_ptr\src
  creating build\temp.win32-3.6\Release\ltp\thirdparty\dynet
  creating build\temp.win32-3.6\Release\ltp\thirdparty\dynet\dynet
  creating build\temp.win32-3.6\Release\ltp\thirdparty\maxent
  creating build\temp.win32-3.6\Release\ltp\src
  creating build\temp.win32-3.6\Release\ltp\src\splitsnt
  creating build\temp.win32-3.6\Release\ltp\src\segmentor
  creating build\temp.win32-3.6\Release\ltp\src\postagger
  creating build\temp.win32-3.6\Release\ltp\src\ner
  creating build\temp.win32-3.6\Release\ltp\src\parser.n
  creating build\temp.win32-3.6\Release\ltp\src\srl
  creating build\temp.win32-3.6\Release\ltp\src\srl\common
  creating build\temp.win32-3.6\Release\ltp\src\srl\common\model
  creating build\temp.win32-3.6\Release\ltp\src\srl\common\structure
  creating build\temp.win32-3.6\Release\ltp\src\srl\include
  creating build\temp.win32-3.6\Release\ltp\src\srl\include\base
  creating build\temp.win32-3.6\Release\ltp\src\srl\Srl
  creating build\temp.win32-3.6\Release\ltp\src\srl\Srl\model
  creating build\temp.win32-3.6\Release\patch
  creating build\temp.win32-3.6\Release\patch\libs
  creating build\temp.win32-3.6\Release\patch\libs\python
  creating build\temp.win32-3.6\Release\patch\libs\python\src
  creating build\temp.win32-3.6\Release\patch\libs\python\src\object
  creating build\temp.win32-3.6\Release\patch\libs\python\src\converter
  D:\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -Ic:\users\001\appdata\local\programs\python\python36-32\include -Ic:\users\001\appdata\local\programs\python\python36-32\include /EHsc /Tpsrc\pyltp.cpp /Fobuild\temp.win32-3.6\Release\src\pyltp.obj /DNOMINMAX /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /DBOOST_ALL_NO_LIB /D_WINDOWS /EHsc
  pyltp.cpp
  src\pyltp.cpp(13): fatal error C1083: Cannot open include file: 'iostream': No such file or directory
  error: command 'D:\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyltp
  Running setup.py clean for pyltp
Failed to build pyltp
Installing collected packages: pyltp
  Running setup.py install for pyltp ... error
    Complete output from command c:\users\001\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\001\\AppData\\Local\\Temp\\pip-build-u9fp4s2s\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\001\AppData\Local\Temp\pip-zdphpwhk-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'pyltp' extension
    creating build
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\src
    creating build\temp.win32-3.6\Release\ltp
    creating build\temp.win32-3.6\Release\ltp\thirdparty
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\regex
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\regex\src
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\program_options
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\program_options\src
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\serialization
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\serialization\src
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\smart_ptr
    creating build\temp.win32-3.6\Release\ltp\thirdparty\boost\libs\smart_ptr\src
    creating build\temp.win32-3.6\Release\ltp\thirdparty\dynet
    creating build\temp.win32-3.6\Release\ltp\thirdparty\dynet\dynet
    creating build\temp.win32-3.6\Release\ltp\thirdparty\maxent
    creating build\temp.win32-3.6\Release\ltp\src
    creating build\temp.win32-3.6\Release\ltp\src\splitsnt
    creating build\temp.win32-3.6\Release\ltp\src\segmentor
    creating build\temp.win32-3.6\Release\ltp\src\postagger
    creating build\temp.win32-3.6\Release\ltp\src\ner
    creating build\temp.win32-3.6\Release\ltp\src\parser.n
    creating build\temp.win32-3.6\Release\ltp\src\srl
    creating build\temp.win32-3.6\Release\ltp\src\srl\common
    creating build\temp.win32-3.6\Release\ltp\src\srl\common\model
    creating build\temp.win32-3.6\Release\ltp\src\srl\common\structure
    creating build\temp.win32-3.6\Release\ltp\src\srl\include
    creating build\temp.win32-3.6\Release\ltp\src\srl\include\base
    creating build\temp.win32-3.6\Release\ltp\src\srl\Srl
    creating build\temp.win32-3.6\Release\ltp\src\srl\Srl\model
    creating build\temp.win32-3.6\Release\patch
    creating build\temp.win32-3.6\Release\patch\libs
    creating build\temp.win32-3.6\Release\patch\libs\python
    creating build\temp.win32-3.6\Release\patch\libs\python\src
    creating build\temp.win32-3.6\Release\patch\libs\python\src\object
    creating build\temp.win32-3.6\Release\patch\libs\python\src\converter
    D:\Microsoft Visual Studio 14.0\VC\bin\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -Ic:\users\001\appdata\local\programs\python\python36-32\include -Ic:\users\001\appdata\local\programs\python\python36-32\include /EHsc /Tpsrc\pyltp.cpp /Fobuild\temp.win32-3.6\Release\src\pyltp.obj /DNOMINMAX /DBOOST_PYTHON_SOURCE /DBOOST_PYTHON_STATIC_LIB /DBOOST_ALL_NO_LIB /D_WINDOWS /EHsc
    pyltp.cpp
    src\pyltp.cpp(13): fatal error C1083: Cannot open include file: 'iostream': No such file or directory
    error: command 'D:\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\001\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\001\\AppData\\Local\\Temp\\pip-build-u9fp4s2s\\pyltp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\001\AppData\Local\Temp\pip-zdphpwhk-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\001\AppData\Local\Temp\pip-build-u9fp4s2s\pyltp\

**Comment by yaleimeng** [comment]
Window环境+python3的各位：请参考[这篇博文](http://mlln.cn/2018/01/31/pyltp在windows下的编译安装/)里面提到的两个whl文件。
[pyltp-0.2.1-cp35-cp35m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp35-cp35m-win_amd64.whl)
[pyltp-0.2.1-cp36-cp36m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp36-cp36m-win_amd64.whl)
直接pip安装很方便。不过只有py3.5与3.6两个版本的，也够用了。

我试用官方示例能够运行，用到的模型当然要另外下载准备好。

**Comment by keyboardWitch** [comment]
the same problem

**Comment by yaleimeng** [comment]
@tcclks 我用pycharm执行没有问题。 你电脑上是否多个版本python共存？很可能你默认的python版本跟pycharm设置不一样。

**Comment by Noval11** [comment]
> building 'pyltp' extension
> gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iltp/include/ -Iltp/thirdparty/boost/include/ -Iltp/thirdparty/dynet/ -Iltp/thirdparty/eigen/ -Iltp/thirdparty/maxent/ -Iltp/src/ -Iltp/src/splitsnt -Iltp/src/segmentor/ -Iltp/src/postagger/ -Iltp/src/ner/ -Iltp/src/parser.n/ -Iltp/src/srl/ -Iltp/src/srl/common/ -Iltp/src/srl/include/ -Iltp/src/srl/Pi/ -Iltp/src/srl/Srl/ -Iltp/src/srl/tool/ -Iltp/src/utils/ -Ipatch/include/ -I/home/ubuntu/anaconda3/include/python3.6m -c src/pyltp.cpp -o build/temp.linux-x86_64-3.6/src/pyltp.o -std=c++0x
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> src/pyltp.cpp:17:27: fatal error: SplitSentence.h: No such file or directory
> compilation terminated.
> error: command 'gcc' failed with exit status 1

这个原因是找不到SplitSentence.h文件，需要在ltp空文件夹下放入https://github.com/HIT-SCIR/ltp 下的所有文件

**Comment by jiangpeng12345** [comment]
> Window环境+python3的各位：请参考[这篇博文](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/)里面提到的两个whl文件。 [pyltp-0.2.1-cp35-cp35m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp35-cp35m-win_amd64.whl) [pyltp-0.2.1-cp36-cp36m-win_amd64.whl](http://mlln.cn/2018/01/31/pyltp%E5%9C%A8windows%E4%B8%8B%E7%9A%84%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85/pyltp-0.2.1-cp36-cp36m-win_amd64.whl) 直接pip安装很方便。不过只有py3.5与3.6两个版本的，也够用了。
> 
> 我试用官方示例能够运行，用到的模型当然要另外下载准备好。

请问linux怎么安装

**Comment by yaleimeng** [comment]
@jiangpeng12345  有几年没关注了。Ubuntu、CentOS环境一般pip install pyltp直接安装就行了。pypi上有编译好的[whl文件](https://pypi.org/project/pyltp/#files) 可以下载。
