### ISSUE TITLE
请问以后能把模型传上GitHub吗

### ISSUE THREAD

**Issue by dwy904** [HIT-SCIR/pyltp#97]
在境外用百度云下载模型速度很慢，不知道以后能否把更新模型放上来GitHub，谢谢。

**Comment by liu946** [comment]
现在ltp的下载源正在迁移至 七牛云。请参考 https://github.com/HIT-SCIR/ltp/issues/233。

**Comment by dwy904** [comment]
链接好像点不开了

**Comment by liu946** [comment]
可以参考首页内容在官网找到下载。http://ltp.ai/download.html

**Comment by dwy904** [comment]
谢谢
