### ISSUE TITLE
Segmentor:Model not loaded!

### ISSUE THREAD

**Issue by weitingyuk** [HIT-SCIR/pyltp#98]
运行的时候报错，这是什么问题？

**Comment by djblovecxc** [comment]
+1

**Comment by djblovecxc** [comment]
CustomizedSegmentor: Model not loaded!

**Comment by Yevgnen** [comment]
同问。根本无法加载，加了也说没加。

**Comment by djblovecxc** [comment]
@Yevgnen 对  在linux上没有这个错误 但是加了不起作用了分词

**Comment by Oneplus** [comment]
windows下如果路径里有中文是没法加载模型的。

不起作用可能是没有下载完整模型。

**Comment by pinweihelai** [comment]
一般情况下都是路径不对，不行就使用绝对路径吧

**Comment by y00282200** [comment]
CustomizedSegmentor: Model not loaded! 
解决没？ 我也碰到这个问题

**Comment by wss211** [comment]
把路径改成全英文的就OK了

**Comment by y00282200** [comment]
已经是全英文了
