### ISSUE TITLE
win7 x64 编译虽然成功，但使用时报错：Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by skyhiter** [HIT-SCIR/pyltp#99]
os：win7 x64
python：Anaconda2-4.4.0 x64
               python 2.7.13 x64
compiler： Microsoft Visual C++ Compiler for Python 2.7
model：3.3.1
编译时虽然好多warning，最终编译成功。
![image](https://user-images.githubusercontent.com/3953193/28520145-ef03eb9a-70a0-11e7-8426-b8659dfd56c8.png)

-----做分词时报错如下-----
./ltp_data_v3.3.1\cws.model
Traceback (most recent call last):
  File "f:\iflyTech\GuBaContents\ltp_test.py", line 13, in <module>
    segmentor.load(cws_model_path)  # 加载模型
Boost.Python.ArgumentError: Python argument types in
    Segmentor.load(Segmentor, unicode)
did not match C++ signature:
    load(struct Segmentor {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)

**Comment by endyul** [comment]
模型路径需要用utf8编码

**Comment by skyhiter** [comment]
模型路径用utf-8编码后果然可以了，十分感谢~~~@endyul

**Comment by yanzi6969** [comment]
请问如何指定utf-8编码呢？

**Comment by endyul** [comment]
@yanzi6969  
`u'这是unicode编码的字符串'.encode('utf-8')`

**Comment by yanzi6969** [comment]
Loading the network...Traceback (most recent call last):
  File "demo.py", line 49, in <module>
    net = caffe.Net(args.prototxt, args.model, caffe.TEST)
Boost.Python.ArgumentError: Python argument types in
    Net.__init__(Net, str, str, int)
did not match C++ signature:
    __init__(boost::python::api::object, std::string, std::string, int)
    __init__(boost::python::api::object, std::string network_file, int phase, int level=0, boost::python::api::object stages=None, boost::python::api::object weights=None)
我在linux下运行的，加载一个caffe model。不知道是不是和你们的问题是一样的
